// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/admin/user_management_service.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Users are used to dynamically manage the rights given to Daml applications.
// They are stored and managed per participant node.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user identifier, which must be a non-empty string of at most 128
	// characters that are either alphanumeric ASCII characters or one of the symbols "@^$.!`-#+'~_|:()".
	//
	// Required
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The primary party as which this user reads and acts by default on the ledger
	// *provided* it has the corresponding “CanReadAs(primary_party)“ or
	// “CanActAs(primary_party)“ rights.
	// Ledger API clients SHOULD set this field to a non-empty value for all users to
	// enable the users to act on the ledger using their own Daml party.
	// Users for participant administrators MAY have an associated primary party.
	// Modifiable
	//
	// Optional
	PrimaryParty string `protobuf:"bytes,2,opt,name=primary_party,json=primaryParty,proto3" json:"primary_party,omitempty"`
	// When set, then the user is denied all access to the Ledger API.
	// Otherwise, the user has access to the Ledger API as per the user's rights.
	// Modifiable
	//
	// Optional
	IsDeactivated bool `protobuf:"varint,3,opt,name=is_deactivated,json=isDeactivated,proto3" json:"is_deactivated,omitempty"`
	// The metadata of this user.
	// Note that the “metadata.resource_version“ tracks changes to the properties described by the “User“ message and not the user's rights.
	// Modifiable
	//
	// Optional
	Metadata *ObjectMeta `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The ID of the identity provider configured by “Identity Provider Config“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,5,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPrimaryParty() string {
	if x != nil {
		return x.PrimaryParty
	}
	return ""
}

func (x *User) GetIsDeactivated() bool {
	if x != nil {
		return x.IsDeactivated
	}
	return false
}

func (x *User) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

// A right granted to a user.
type Right struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Right_ParticipantAdmin_
	//	*Right_CanActAs_
	//	*Right_CanReadAs_
	//	*Right_IdentityProviderAdmin_
	//	*Right_CanReadAsAnyParty_
	//	*Right_CanExecuteAs_
	//	*Right_CanExecuteAsAnyParty_
	Kind          isRight_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right) Reset() {
	*x = Right{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right) ProtoMessage() {}

func (x *Right) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right.ProtoReflect.Descriptor instead.
func (*Right) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1}
}

func (x *Right) GetKind() isRight_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Right) GetParticipantAdmin() *Right_ParticipantAdmin {
	if x != nil {
		if x, ok := x.Kind.(*Right_ParticipantAdmin_); ok {
			return x.ParticipantAdmin
		}
	}
	return nil
}

func (x *Right) GetCanActAs() *Right_CanActAs {
	if x != nil {
		if x, ok := x.Kind.(*Right_CanActAs_); ok {
			return x.CanActAs
		}
	}
	return nil
}

func (x *Right) GetCanReadAs() *Right_CanReadAs {
	if x != nil {
		if x, ok := x.Kind.(*Right_CanReadAs_); ok {
			return x.CanReadAs
		}
	}
	return nil
}

func (x *Right) GetIdentityProviderAdmin() *Right_IdentityProviderAdmin {
	if x != nil {
		if x, ok := x.Kind.(*Right_IdentityProviderAdmin_); ok {
			return x.IdentityProviderAdmin
		}
	}
	return nil
}

func (x *Right) GetCanReadAsAnyParty() *Right_CanReadAsAnyParty {
	if x != nil {
		if x, ok := x.Kind.(*Right_CanReadAsAnyParty_); ok {
			return x.CanReadAsAnyParty
		}
	}
	return nil
}

func (x *Right) GetCanExecuteAs() *Right_CanExecuteAs {
	if x != nil {
		if x, ok := x.Kind.(*Right_CanExecuteAs_); ok {
			return x.CanExecuteAs
		}
	}
	return nil
}

func (x *Right) GetCanExecuteAsAnyParty() *Right_CanExecuteAsAnyParty {
	if x != nil {
		if x, ok := x.Kind.(*Right_CanExecuteAsAnyParty_); ok {
			return x.CanExecuteAsAnyParty
		}
	}
	return nil
}

type isRight_Kind interface {
	isRight_Kind()
}

type Right_ParticipantAdmin_ struct {
	// The user can administer the participant node.
	ParticipantAdmin *Right_ParticipantAdmin `protobuf:"bytes,1,opt,name=participant_admin,json=participantAdmin,proto3,oneof"`
}

type Right_CanActAs_ struct {
	// The user can act as a specific party.
	CanActAs *Right_CanActAs `protobuf:"bytes,2,opt,name=can_act_as,json=canActAs,proto3,oneof"`
}

type Right_CanReadAs_ struct {
	// The user can read ledger data visible to a specific party.
	CanReadAs *Right_CanReadAs `protobuf:"bytes,3,opt,name=can_read_as,json=canReadAs,proto3,oneof"`
}

type Right_IdentityProviderAdmin_ struct {
	// The user can administer users and parties assigned to the same identity provider as the one of the user.
	IdentityProviderAdmin *Right_IdentityProviderAdmin `protobuf:"bytes,4,opt,name=identity_provider_admin,json=identityProviderAdmin,proto3,oneof"`
}

type Right_CanReadAsAnyParty_ struct {
	// The user can read as any party on a participant
	CanReadAsAnyParty *Right_CanReadAsAnyParty `protobuf:"bytes,5,opt,name=can_read_as_any_party,json=canReadAsAnyParty,proto3,oneof"`
}

type Right_CanExecuteAs_ struct {
	// The user can prepare and execute submissions as a specific party.
	CanExecuteAs *Right_CanExecuteAs `protobuf:"bytes,6,opt,name=can_execute_as,json=canExecuteAs,proto3,oneof"`
}

type Right_CanExecuteAsAnyParty_ struct {
	// The user can prepare and execute submissions as any party on a participant.
	CanExecuteAsAnyParty *Right_CanExecuteAsAnyParty `protobuf:"bytes,7,opt,name=can_execute_as_any_party,json=canExecuteAsAnyParty,proto3,oneof"`
}

func (*Right_ParticipantAdmin_) isRight_Kind() {}

func (*Right_CanActAs_) isRight_Kind() {}

func (*Right_CanReadAs_) isRight_Kind() {}

func (*Right_IdentityProviderAdmin_) isRight_Kind() {}

func (*Right_CanReadAsAnyParty_) isRight_Kind() {}

func (*Right_CanExecuteAs_) isRight_Kind() {}

func (*Right_CanExecuteAsAnyParty_) isRight_Kind() {}

// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(user.identity_provider_id)“
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to create.
	//
	// Required
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The rights to be assigned to the user upon creation,
	// which SHOULD include appropriate rights for the “user.primary_party“.
	//
	// Optional: can be empty
	Rights        []*Right `protobuf:"bytes,2,rep,name=rights,proto3" json:"rights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetRights() []*Right {
	if x != nil {
		return x.Rights
	}
	return nil
}

type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created user.
	//
	// Required
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id) OR IsAuthenticatedUser(user_id)“
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user whose data to retrieve.
	// If set to empty string (the default), then the data for the authenticated user will be retrieved.
	//
	// Optional
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The id of the “Identity Provider“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,2,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Retrieved user.
	//
	// Required
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(user.identity_provider_id)“
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to update.
	// Modifiable
	//
	// Required
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// An update mask specifies how and which properties of the “User“ message are to be updated.
	// An update mask consists of a set of update paths.
	// A valid update path points to a field or a subfield relative to the “User“ message.
	// A valid update mask must:
	//
	// 1. contain at least one update path,
	// 2. contain only valid update paths.
	//
	// Fields that can be updated are marked as “Modifiable“.
	// An update path can also point to a non-“Modifiable“ fields such as 'id' and 'metadata.resource_version'
	// because they are used:
	//
	// 1. to identify the user resource subject to the update,
	// 2. for concurrent change control.
	//
	// Examples of valid update paths: 'primary_party', 'metadata', 'metadata.annotations'.
	// For additional information see the documentation for standard protobuf3's “google.protobuf.FieldMask“.
	// For similar Ledger API see “com.daml.ledger.api.v2.admin.UpdatePartyDetailsRequest“.
	//
	// Required
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user
	//
	// Required
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)“
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to delete.
	//
	// Required
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The id of the “Identity Provider“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,2,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserRequest) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

// Does not (yet) contain any data.
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{9}
}

// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)“
type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination token to determine the specific page to fetch.
	// Leave empty to fetch the first page.
	//
	// Optional
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Maximum number of results to be returned by the server. The server will return no more than that many results, but it might return fewer.
	// If 0, the server will decide the number of results to be returned.
	//
	// Optional
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The id of the “Identity Provider“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,4,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A subset of users of the participant node that fit into this page.
	// Can be empty if no more users
	//
	// Optional: can be empty
	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Pagination token to retrieve the next page.
	// Empty, if there are no further results.
	//
	// Optional
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Add the rights to the set of rights granted to the user.
//
// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)“
type GrantUserRightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to whom to grant rights.
	//
	// Required
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The rights to grant.
	//
	// Optional: can be empty
	Rights []*Right `protobuf:"bytes,2,rep,name=rights,proto3" json:"rights,omitempty"`
	// The id of the “Identity Provider“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,3,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GrantUserRightsRequest) Reset() {
	*x = GrantUserRightsRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantUserRightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantUserRightsRequest) ProtoMessage() {}

func (x *GrantUserRightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantUserRightsRequest.ProtoReflect.Descriptor instead.
func (*GrantUserRightsRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{12}
}

func (x *GrantUserRightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantUserRightsRequest) GetRights() []*Right {
	if x != nil {
		return x.Rights
	}
	return nil
}

func (x *GrantUserRightsRequest) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

type GrantUserRightsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rights that were newly granted by the request.
	//
	// Optional: can be empty
	NewlyGrantedRights []*Right `protobuf:"bytes,1,rep,name=newly_granted_rights,json=newlyGrantedRights,proto3" json:"newly_granted_rights,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GrantUserRightsResponse) Reset() {
	*x = GrantUserRightsResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantUserRightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantUserRightsResponse) ProtoMessage() {}

func (x *GrantUserRightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantUserRightsResponse.ProtoReflect.Descriptor instead.
func (*GrantUserRightsResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{13}
}

func (x *GrantUserRightsResponse) GetNewlyGrantedRights() []*Right {
	if x != nil {
		return x.NewlyGrantedRights
	}
	return nil
}

// Remove the rights from the set of rights granted to the user.
//
// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)“
type RevokeUserRightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user from whom to revoke rights.
	//
	// Required
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The rights to revoke.
	//
	// Optional: can be empty
	Rights []*Right `protobuf:"bytes,2,rep,name=rights,proto3" json:"rights,omitempty"`
	// The id of the “Identity Provider“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,3,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevokeUserRightsRequest) Reset() {
	*x = RevokeUserRightsRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserRightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserRightsRequest) ProtoMessage() {}

func (x *RevokeUserRightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserRightsRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserRightsRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeUserRightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeUserRightsRequest) GetRights() []*Right {
	if x != nil {
		return x.Rights
	}
	return nil
}

func (x *RevokeUserRightsRequest) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

type RevokeUserRightsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rights that were actually revoked by the request.
	//
	// Optional: can be empty
	NewlyRevokedRights []*Right `protobuf:"bytes,1,rep,name=newly_revoked_rights,json=newlyRevokedRights,proto3" json:"newly_revoked_rights,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevokeUserRightsResponse) Reset() {
	*x = RevokeUserRightsResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserRightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserRightsResponse) ProtoMessage() {}

func (x *RevokeUserRightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserRightsResponse.ProtoReflect.Descriptor instead.
func (*RevokeUserRightsResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{15}
}

func (x *RevokeUserRightsResponse) GetNewlyRevokedRights() []*Right {
	if x != nil {
		return x.NewlyRevokedRights
	}
	return nil
}

// Required authorization: “HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id) OR IsAuthenticatedUser(user_id)“
type ListUserRightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user for which to list the rights.
	// If set to empty string (the default), then the rights for the authenticated user will be listed.
	//
	// Required
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The id of the “Identity Provider“
	// If not set, assume the user is managed by the default identity provider.
	//
	// Optional
	IdentityProviderId string `protobuf:"bytes,2,opt,name=identity_provider_id,json=identityProviderId,proto3" json:"identity_provider_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListUserRightsRequest) Reset() {
	*x = ListUserRightsRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRightsRequest) ProtoMessage() {}

func (x *ListUserRightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRightsRequest.ProtoReflect.Descriptor instead.
func (*ListUserRightsRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListUserRightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserRightsRequest) GetIdentityProviderId() string {
	if x != nil {
		return x.IdentityProviderId
	}
	return ""
}

type ListUserRightsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All rights of the user.
	//
	// Optional: can be empty
	Rights        []*Right `protobuf:"bytes,1,rep,name=rights,proto3" json:"rights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRightsResponse) Reset() {
	*x = ListUserRightsResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRightsResponse) ProtoMessage() {}

func (x *ListUserRightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRightsResponse.ProtoReflect.Descriptor instead.
func (*ListUserRightsResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserRightsResponse) GetRights() []*Right {
	if x != nil {
		return x.Rights
	}
	return nil
}

// Required authorization: “HasRight(ParticipantAdmin)“
type UpdateUserIdentityProviderIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User to update
	//
	// Required
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Current identity provider ID of the user
	// If omitted, the default IDP is assumed
	//
	// Optional
	SourceIdentityProviderId string `protobuf:"bytes,2,opt,name=source_identity_provider_id,json=sourceIdentityProviderId,proto3" json:"source_identity_provider_id,omitempty"`
	// Target identity provider ID of the user
	// If omitted, the default IDP is assumed
	//
	// Optional
	TargetIdentityProviderId string `protobuf:"bytes,3,opt,name=target_identity_provider_id,json=targetIdentityProviderId,proto3" json:"target_identity_provider_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateUserIdentityProviderIdRequest) Reset() {
	*x = UpdateUserIdentityProviderIdRequest{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserIdentityProviderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserIdentityProviderIdRequest) ProtoMessage() {}

func (x *UpdateUserIdentityProviderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserIdentityProviderIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserIdentityProviderIdRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateUserIdentityProviderIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserIdentityProviderIdRequest) GetSourceIdentityProviderId() string {
	if x != nil {
		return x.SourceIdentityProviderId
	}
	return ""
}

func (x *UpdateUserIdentityProviderIdRequest) GetTargetIdentityProviderId() string {
	if x != nil {
		return x.TargetIdentityProviderId
	}
	return ""
}

type UpdateUserIdentityProviderIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserIdentityProviderIdResponse) Reset() {
	*x = UpdateUserIdentityProviderIdResponse{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserIdentityProviderIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserIdentityProviderIdResponse) ProtoMessage() {}

func (x *UpdateUserIdentityProviderIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserIdentityProviderIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserIdentityProviderIdResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{19}
}

// The right to administer the participant node.
type Right_ParticipantAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_ParticipantAdmin) Reset() {
	*x = Right_ParticipantAdmin{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_ParticipantAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_ParticipantAdmin) ProtoMessage() {}

func (x *Right_ParticipantAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_ParticipantAdmin.ProtoReflect.Descriptor instead.
func (*Right_ParticipantAdmin) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 0}
}

type Right_CanActAs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The right to authorize commands for this party.
	//
	// Required
	Party         string `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_CanActAs) Reset() {
	*x = Right_CanActAs{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_CanActAs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_CanActAs) ProtoMessage() {}

func (x *Right_CanActAs) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_CanActAs.ProtoReflect.Descriptor instead.
func (*Right_CanActAs) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Right_CanActAs) GetParty() string {
	if x != nil {
		return x.Party
	}
	return ""
}

type Right_CanReadAs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The right to read ledger data visible to this party.
	//
	// Required
	Party         string `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_CanReadAs) Reset() {
	*x = Right_CanReadAs{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_CanReadAs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_CanReadAs) ProtoMessage() {}

func (x *Right_CanReadAs) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_CanReadAs.ProtoReflect.Descriptor instead.
func (*Right_CanReadAs) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Right_CanReadAs) GetParty() string {
	if x != nil {
		return x.Party
	}
	return ""
}

type Right_CanExecuteAs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The right to prepare and execute submissions as this party.
	// This right does not entitle the user to perform any reads.
	// If reading is required, a separate ReadAs right must be added.
	// Right to execute as a party is also implicitly contained in the CanActAs right.
	//
	// Required
	Party         string `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_CanExecuteAs) Reset() {
	*x = Right_CanExecuteAs{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_CanExecuteAs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_CanExecuteAs) ProtoMessage() {}

func (x *Right_CanExecuteAs) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_CanExecuteAs.ProtoReflect.Descriptor instead.
func (*Right_CanExecuteAs) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Right_CanExecuteAs) GetParty() string {
	if x != nil {
		return x.Party
	}
	return ""
}

// The right to administer the identity provider that the user is assigned to.
// It means, being able to manage users and parties that are also assigned
// to the same identity provider.
type Right_IdentityProviderAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_IdentityProviderAdmin) Reset() {
	*x = Right_IdentityProviderAdmin{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_IdentityProviderAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_IdentityProviderAdmin) ProtoMessage() {}

func (x *Right_IdentityProviderAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_IdentityProviderAdmin.ProtoReflect.Descriptor instead.
func (*Right_IdentityProviderAdmin) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 4}
}

// The rights of a participant's super reader. Its utility is predominantly for
// feeding external tools, such as PQS, continually without the need to change subscriptions
// as new parties pop in and out of existence.
type Right_CanReadAsAnyParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_CanReadAsAnyParty) Reset() {
	*x = Right_CanReadAsAnyParty{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_CanReadAsAnyParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_CanReadAsAnyParty) ProtoMessage() {}

func (x *Right_CanReadAsAnyParty) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_CanReadAsAnyParty.ProtoReflect.Descriptor instead.
func (*Right_CanReadAsAnyParty) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 5}
}

// The rights of a user to prepare and execute transactions as any party.
// Its utility is predominantly for users that perform interactive submissions
// on behalf of many parties.
type Right_CanExecuteAsAnyParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Right_CanExecuteAsAnyParty) Reset() {
	*x = Right_CanExecuteAsAnyParty{}
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Right_CanExecuteAsAnyParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Right_CanExecuteAsAnyParty) ProtoMessage() {}

func (x *Right_CanExecuteAsAnyParty) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Right_CanExecuteAsAnyParty.ProtoReflect.Descriptor instead.
func (*Right_CanExecuteAsAnyParty) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP(), []int{1, 6}
}

var File_com_daml_ledger_api_v2_admin_user_management_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDesc = "" +
	"\n" +
	":com/daml/ledger/api/v2/admin/user_management_service.proto\x12\x1ccom.daml.ledger.api.v2.admin\x1a.com/daml/ledger/api/v2/admin/object_meta.proto\x1a google/protobuf/field_mask.proto\"\xda\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rprimary_party\x18\x02 \x01(\tR\fprimaryParty\x12%\n" +
	"\x0eis_deactivated\x18\x03 \x01(\bR\risDeactivated\x12D\n" +
	"\bmetadata\x18\x04 \x01(\v2(.com.daml.ledger.api.v2.admin.ObjectMetaR\bmetadata\x120\n" +
	"\x14identity_provider_id\x18\x05 \x01(\tR\x12identityProviderId\"\x86\a\n" +
	"\x05Right\x12c\n" +
	"\x11participant_admin\x18\x01 \x01(\v24.com.daml.ledger.api.v2.admin.Right.ParticipantAdminH\x00R\x10participantAdmin\x12L\n" +
	"\n" +
	"can_act_as\x18\x02 \x01(\v2,.com.daml.ledger.api.v2.admin.Right.CanActAsH\x00R\bcanActAs\x12O\n" +
	"\vcan_read_as\x18\x03 \x01(\v2-.com.daml.ledger.api.v2.admin.Right.CanReadAsH\x00R\tcanReadAs\x12s\n" +
	"\x17identity_provider_admin\x18\x04 \x01(\v29.com.daml.ledger.api.v2.admin.Right.IdentityProviderAdminH\x00R\x15identityProviderAdmin\x12i\n" +
	"\x15can_read_as_any_party\x18\x05 \x01(\v25.com.daml.ledger.api.v2.admin.Right.CanReadAsAnyPartyH\x00R\x11canReadAsAnyParty\x12X\n" +
	"\x0ecan_execute_as\x18\x06 \x01(\v20.com.daml.ledger.api.v2.admin.Right.CanExecuteAsH\x00R\fcanExecuteAs\x12r\n" +
	"\x18can_execute_as_any_party\x18\a \x01(\v28.com.daml.ledger.api.v2.admin.Right.CanExecuteAsAnyPartyH\x00R\x14canExecuteAsAnyParty\x1a\x12\n" +
	"\x10ParticipantAdmin\x1a \n" +
	"\bCanActAs\x12\x14\n" +
	"\x05party\x18\x01 \x01(\tR\x05party\x1a!\n" +
	"\tCanReadAs\x12\x14\n" +
	"\x05party\x18\x01 \x01(\tR\x05party\x1a$\n" +
	"\fCanExecuteAs\x12\x14\n" +
	"\x05party\x18\x01 \x01(\tR\x05party\x1a\x17\n" +
	"\x15IdentityProviderAdmin\x1a\x13\n" +
	"\x11CanReadAsAnyParty\x1a\x16\n" +
	"\x14CanExecuteAsAnyPartyB\x06\n" +
	"\x04kind\"\x88\x01\n" +
	"\x11CreateUserRequest\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.admin.UserR\x04user\x12;\n" +
	"\x06rights\x18\x02 \x03(\v2#.com.daml.ledger.api.v2.admin.RightR\x06rights\"L\n" +
	"\x12CreateUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.admin.UserR\x04user\"[\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14identity_provider_id\x18\x02 \x01(\tR\x12identityProviderId\"I\n" +
	"\x0fGetUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.admin.UserR\x04user\"\x88\x01\n" +
	"\x11UpdateUserRequest\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.admin.UserR\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"L\n" +
	"\x12UpdateUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.admin.UserR\x04user\"^\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14identity_provider_id\x18\x02 \x01(\tR\x12identityProviderId\"\x14\n" +
	"\x12DeleteUserResponse\"\x80\x01\n" +
	"\x10ListUsersRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x120\n" +
	"\x14identity_provider_id\x18\x04 \x01(\tR\x12identityProviderId\"u\n" +
	"\x11ListUsersResponse\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".com.daml.ledger.api.v2.admin.UserR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa0\x01\n" +
	"\x16GrantUserRightsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\x06rights\x18\x02 \x03(\v2#.com.daml.ledger.api.v2.admin.RightR\x06rights\x120\n" +
	"\x14identity_provider_id\x18\x03 \x01(\tR\x12identityProviderId\"p\n" +
	"\x17GrantUserRightsResponse\x12U\n" +
	"\x14newly_granted_rights\x18\x01 \x03(\v2#.com.daml.ledger.api.v2.admin.RightR\x12newlyGrantedRights\"\xa1\x01\n" +
	"\x17RevokeUserRightsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\x06rights\x18\x02 \x03(\v2#.com.daml.ledger.api.v2.admin.RightR\x06rights\x120\n" +
	"\x14identity_provider_id\x18\x03 \x01(\tR\x12identityProviderId\"q\n" +
	"\x18RevokeUserRightsResponse\x12U\n" +
	"\x14newly_revoked_rights\x18\x01 \x03(\v2#.com.daml.ledger.api.v2.admin.RightR\x12newlyRevokedRights\"b\n" +
	"\x15ListUserRightsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14identity_provider_id\x18\x02 \x01(\tR\x12identityProviderId\"U\n" +
	"\x16ListUserRightsResponse\x12;\n" +
	"\x06rights\x18\x01 \x03(\v2#.com.daml.ledger.api.v2.admin.RightR\x06rights\"\xbc\x01\n" +
	"#UpdateUserIdentityProviderIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12=\n" +
	"\x1bsource_identity_provider_id\x18\x02 \x01(\tR\x18sourceIdentityProviderId\x12=\n" +
	"\x1btarget_identity_provider_id\x18\x03 \x01(\tR\x18targetIdentityProviderId\"&\n" +
	"$UpdateUserIdentityProviderIdResponse2\xe9\b\n" +
	"\x15UserManagementService\x12o\n" +
	"\n" +
	"CreateUser\x12/.com.daml.ledger.api.v2.admin.CreateUserRequest\x1a0.com.daml.ledger.api.v2.admin.CreateUserResponse\x12f\n" +
	"\aGetUser\x12,.com.daml.ledger.api.v2.admin.GetUserRequest\x1a-.com.daml.ledger.api.v2.admin.GetUserResponse\x12o\n" +
	"\n" +
	"UpdateUser\x12/.com.daml.ledger.api.v2.admin.UpdateUserRequest\x1a0.com.daml.ledger.api.v2.admin.UpdateUserResponse\x12o\n" +
	"\n" +
	"DeleteUser\x12/.com.daml.ledger.api.v2.admin.DeleteUserRequest\x1a0.com.daml.ledger.api.v2.admin.DeleteUserResponse\x12l\n" +
	"\tListUsers\x12..com.daml.ledger.api.v2.admin.ListUsersRequest\x1a/.com.daml.ledger.api.v2.admin.ListUsersResponse\x12~\n" +
	"\x0fGrantUserRights\x124.com.daml.ledger.api.v2.admin.GrantUserRightsRequest\x1a5.com.daml.ledger.api.v2.admin.GrantUserRightsResponse\x12\x81\x01\n" +
	"\x10RevokeUserRights\x125.com.daml.ledger.api.v2.admin.RevokeUserRightsRequest\x1a6.com.daml.ledger.api.v2.admin.RevokeUserRightsResponse\x12{\n" +
	"\x0eListUserRights\x123.com.daml.ledger.api.v2.admin.ListUserRightsRequest\x1a4.com.daml.ledger.api.v2.admin.ListUserRightsResponse\x12\xa5\x01\n" +
	"\x1cUpdateUserIdentityProviderId\x12A.com.daml.ledger.api.v2.admin.UpdateUserIdentityProviderIdRequest\x1aB.com.daml.ledger.api.v2.admin.UpdateUserIdentityProviderIdResponseB\xa8\x02\n" +
	" com.com.daml.ledger.api.v2.adminB\x1aUserManagementServiceProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2/admin\xa2\x02\x06CDLAVA\xaa\x02\x1cCom.Daml.Ledger.Api.V2.Admin\xca\x02\x1cCom\\Daml\\Ledger\\Api\\V2\\Admin\xe2\x02(Com\\Daml\\Ledger\\Api\\V2\\Admin\\GPBMetadata\xea\x02!Com::Daml::Ledger::Api::V2::Adminb\x06proto3"

var (
	file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_com_daml_ledger_api_v2_admin_user_management_service_proto_goTypes = []any{
	(*User)(nil),                                 // 0: com.daml.ledger.api.v2.admin.User
	(*Right)(nil),                                // 1: com.daml.ledger.api.v2.admin.Right
	(*CreateUserRequest)(nil),                    // 2: com.daml.ledger.api.v2.admin.CreateUserRequest
	(*CreateUserResponse)(nil),                   // 3: com.daml.ledger.api.v2.admin.CreateUserResponse
	(*GetUserRequest)(nil),                       // 4: com.daml.ledger.api.v2.admin.GetUserRequest
	(*GetUserResponse)(nil),                      // 5: com.daml.ledger.api.v2.admin.GetUserResponse
	(*UpdateUserRequest)(nil),                    // 6: com.daml.ledger.api.v2.admin.UpdateUserRequest
	(*UpdateUserResponse)(nil),                   // 7: com.daml.ledger.api.v2.admin.UpdateUserResponse
	(*DeleteUserRequest)(nil),                    // 8: com.daml.ledger.api.v2.admin.DeleteUserRequest
	(*DeleteUserResponse)(nil),                   // 9: com.daml.ledger.api.v2.admin.DeleteUserResponse
	(*ListUsersRequest)(nil),                     // 10: com.daml.ledger.api.v2.admin.ListUsersRequest
	(*ListUsersResponse)(nil),                    // 11: com.daml.ledger.api.v2.admin.ListUsersResponse
	(*GrantUserRightsRequest)(nil),               // 12: com.daml.ledger.api.v2.admin.GrantUserRightsRequest
	(*GrantUserRightsResponse)(nil),              // 13: com.daml.ledger.api.v2.admin.GrantUserRightsResponse
	(*RevokeUserRightsRequest)(nil),              // 14: com.daml.ledger.api.v2.admin.RevokeUserRightsRequest
	(*RevokeUserRightsResponse)(nil),             // 15: com.daml.ledger.api.v2.admin.RevokeUserRightsResponse
	(*ListUserRightsRequest)(nil),                // 16: com.daml.ledger.api.v2.admin.ListUserRightsRequest
	(*ListUserRightsResponse)(nil),               // 17: com.daml.ledger.api.v2.admin.ListUserRightsResponse
	(*UpdateUserIdentityProviderIdRequest)(nil),  // 18: com.daml.ledger.api.v2.admin.UpdateUserIdentityProviderIdRequest
	(*UpdateUserIdentityProviderIdResponse)(nil), // 19: com.daml.ledger.api.v2.admin.UpdateUserIdentityProviderIdResponse
	(*Right_ParticipantAdmin)(nil),               // 20: com.daml.ledger.api.v2.admin.Right.ParticipantAdmin
	(*Right_CanActAs)(nil),                       // 21: com.daml.ledger.api.v2.admin.Right.CanActAs
	(*Right_CanReadAs)(nil),                      // 22: com.daml.ledger.api.v2.admin.Right.CanReadAs
	(*Right_CanExecuteAs)(nil),                   // 23: com.daml.ledger.api.v2.admin.Right.CanExecuteAs
	(*Right_IdentityProviderAdmin)(nil),          // 24: com.daml.ledger.api.v2.admin.Right.IdentityProviderAdmin
	(*Right_CanReadAsAnyParty)(nil),              // 25: com.daml.ledger.api.v2.admin.Right.CanReadAsAnyParty
	(*Right_CanExecuteAsAnyParty)(nil),           // 26: com.daml.ledger.api.v2.admin.Right.CanExecuteAsAnyParty
	(*ObjectMeta)(nil),                           // 27: com.daml.ledger.api.v2.admin.ObjectMeta
	(*fieldmaskpb.FieldMask)(nil),                // 28: google.protobuf.FieldMask
}
var file_com_daml_ledger_api_v2_admin_user_management_service_proto_depIdxs = []int32{
	27, // 0: com.daml.ledger.api.v2.admin.User.metadata:type_name -> com.daml.ledger.api.v2.admin.ObjectMeta
	20, // 1: com.daml.ledger.api.v2.admin.Right.participant_admin:type_name -> com.daml.ledger.api.v2.admin.Right.ParticipantAdmin
	21, // 2: com.daml.ledger.api.v2.admin.Right.can_act_as:type_name -> com.daml.ledger.api.v2.admin.Right.CanActAs
	22, // 3: com.daml.ledger.api.v2.admin.Right.can_read_as:type_name -> com.daml.ledger.api.v2.admin.Right.CanReadAs
	24, // 4: com.daml.ledger.api.v2.admin.Right.identity_provider_admin:type_name -> com.daml.ledger.api.v2.admin.Right.IdentityProviderAdmin
	25, // 5: com.daml.ledger.api.v2.admin.Right.can_read_as_any_party:type_name -> com.daml.ledger.api.v2.admin.Right.CanReadAsAnyParty
	23, // 6: com.daml.ledger.api.v2.admin.Right.can_execute_as:type_name -> com.daml.ledger.api.v2.admin.Right.CanExecuteAs
	26, // 7: com.daml.ledger.api.v2.admin.Right.can_execute_as_any_party:type_name -> com.daml.ledger.api.v2.admin.Right.CanExecuteAsAnyParty
	0,  // 8: com.daml.ledger.api.v2.admin.CreateUserRequest.user:type_name -> com.daml.ledger.api.v2.admin.User
	1,  // 9: com.daml.ledger.api.v2.admin.CreateUserRequest.rights:type_name -> com.daml.ledger.api.v2.admin.Right
	0,  // 10: com.daml.ledger.api.v2.admin.CreateUserResponse.user:type_name -> com.daml.ledger.api.v2.admin.User
	0,  // 11: com.daml.ledger.api.v2.admin.GetUserResponse.user:type_name -> com.daml.ledger.api.v2.admin.User
	0,  // 12: com.daml.ledger.api.v2.admin.UpdateUserRequest.user:type_name -> com.daml.ledger.api.v2.admin.User
	28, // 13: com.daml.ledger.api.v2.admin.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 14: com.daml.ledger.api.v2.admin.UpdateUserResponse.user:type_name -> com.daml.ledger.api.v2.admin.User
	0,  // 15: com.daml.ledger.api.v2.admin.ListUsersResponse.users:type_name -> com.daml.ledger.api.v2.admin.User
	1,  // 16: com.daml.ledger.api.v2.admin.GrantUserRightsRequest.rights:type_name -> com.daml.ledger.api.v2.admin.Right
	1,  // 17: com.daml.ledger.api.v2.admin.GrantUserRightsResponse.newly_granted_rights:type_name -> com.daml.ledger.api.v2.admin.Right
	1,  // 18: com.daml.ledger.api.v2.admin.RevokeUserRightsRequest.rights:type_name -> com.daml.ledger.api.v2.admin.Right
	1,  // 19: com.daml.ledger.api.v2.admin.RevokeUserRightsResponse.newly_revoked_rights:type_name -> com.daml.ledger.api.v2.admin.Right
	1,  // 20: com.daml.ledger.api.v2.admin.ListUserRightsResponse.rights:type_name -> com.daml.ledger.api.v2.admin.Right
	2,  // 21: com.daml.ledger.api.v2.admin.UserManagementService.CreateUser:input_type -> com.daml.ledger.api.v2.admin.CreateUserRequest
	4,  // 22: com.daml.ledger.api.v2.admin.UserManagementService.GetUser:input_type -> com.daml.ledger.api.v2.admin.GetUserRequest
	6,  // 23: com.daml.ledger.api.v2.admin.UserManagementService.UpdateUser:input_type -> com.daml.ledger.api.v2.admin.UpdateUserRequest
	8,  // 24: com.daml.ledger.api.v2.admin.UserManagementService.DeleteUser:input_type -> com.daml.ledger.api.v2.admin.DeleteUserRequest
	10, // 25: com.daml.ledger.api.v2.admin.UserManagementService.ListUsers:input_type -> com.daml.ledger.api.v2.admin.ListUsersRequest
	12, // 26: com.daml.ledger.api.v2.admin.UserManagementService.GrantUserRights:input_type -> com.daml.ledger.api.v2.admin.GrantUserRightsRequest
	14, // 27: com.daml.ledger.api.v2.admin.UserManagementService.RevokeUserRights:input_type -> com.daml.ledger.api.v2.admin.RevokeUserRightsRequest
	16, // 28: com.daml.ledger.api.v2.admin.UserManagementService.ListUserRights:input_type -> com.daml.ledger.api.v2.admin.ListUserRightsRequest
	18, // 29: com.daml.ledger.api.v2.admin.UserManagementService.UpdateUserIdentityProviderId:input_type -> com.daml.ledger.api.v2.admin.UpdateUserIdentityProviderIdRequest
	3,  // 30: com.daml.ledger.api.v2.admin.UserManagementService.CreateUser:output_type -> com.daml.ledger.api.v2.admin.CreateUserResponse
	5,  // 31: com.daml.ledger.api.v2.admin.UserManagementService.GetUser:output_type -> com.daml.ledger.api.v2.admin.GetUserResponse
	7,  // 32: com.daml.ledger.api.v2.admin.UserManagementService.UpdateUser:output_type -> com.daml.ledger.api.v2.admin.UpdateUserResponse
	9,  // 33: com.daml.ledger.api.v2.admin.UserManagementService.DeleteUser:output_type -> com.daml.ledger.api.v2.admin.DeleteUserResponse
	11, // 34: com.daml.ledger.api.v2.admin.UserManagementService.ListUsers:output_type -> com.daml.ledger.api.v2.admin.ListUsersResponse
	13, // 35: com.daml.ledger.api.v2.admin.UserManagementService.GrantUserRights:output_type -> com.daml.ledger.api.v2.admin.GrantUserRightsResponse
	15, // 36: com.daml.ledger.api.v2.admin.UserManagementService.RevokeUserRights:output_type -> com.daml.ledger.api.v2.admin.RevokeUserRightsResponse
	17, // 37: com.daml.ledger.api.v2.admin.UserManagementService.ListUserRights:output_type -> com.daml.ledger.api.v2.admin.ListUserRightsResponse
	19, // 38: com.daml.ledger.api.v2.admin.UserManagementService.UpdateUserIdentityProviderId:output_type -> com.daml.ledger.api.v2.admin.UpdateUserIdentityProviderIdResponse
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_admin_user_management_service_proto_init() }
func file_com_daml_ledger_api_v2_admin_user_management_service_proto_init() {
	if File_com_daml_ledger_api_v2_admin_user_management_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_admin_object_meta_proto_init()
	file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes[1].OneofWrappers = []any{
		(*Right_ParticipantAdmin_)(nil),
		(*Right_CanActAs_)(nil),
		(*Right_CanReadAs_)(nil),
		(*Right_IdentityProviderAdmin_)(nil),
		(*Right_CanReadAsAnyParty_)(nil),
		(*Right_CanExecuteAs_)(nil),
		(*Right_CanExecuteAsAnyParty_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_admin_user_management_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_admin_user_management_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_admin_user_management_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_admin_user_management_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_admin_user_management_service_proto = out.File
	file_com_daml_ledger_api_v2_admin_user_management_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_admin_user_management_service_proto_depIdxs = nil
}
