[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Pin these settings to ensure deterministic contract address
solc = "0.8.30"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
