package builder_test

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"testing"

	xc "github.com/cordialsys/crosschain"
	xcbuilder "github.com/cordialsys/crosschain/builder"
	xccall "github.com/cordialsys/crosschain/call"
	"github.com/cordialsys/crosschain/chain/solana/builder"
	"github.com/cordialsys/crosschain/chain/solana/call"
	"github.com/cordialsys/crosschain/chain/solana/tx"
	"github.com/cordialsys/crosschain/chain/solana/tx_input"
	"github.com/solana-foundation/solana-go/v2"
	"github.com/solana-foundation/solana-go/v2/rpc"
	"github.com/stretchr/testify/require"
)

// Independently generated by @solana/kit 8.0.0 using Ed25519 seeds [1;32]
// and [2;32], a zero blockhash, and the limits/amount below. Test keys only.
const kitV1Transfer = "gQEAAQ8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEDiojj3XQJ8ZX9UtstPLpdcspnCb8dlBIb83SIAbQPb1yBOXcOqH0XX1ajVGbDTH7My42KkbTuN6Jd9g9bj8mzlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiBMAAAAAAAAgTgAAAAABAAICDAAAAQIAAACAlpgAAAAAAEYKa3DGf99gTYm+67Ty082yWg80GUpeqx78SXqqa0LKp77S0ZUMlfT7Kc0DsnYB1q4WkTILl3kvUuWEphNk5g8="

func TestTransferVersions(t *testing.T) {
	key := solana.PrivateKey(ed25519.NewKeyFromSeed(bytes.Repeat([]byte{1}, 32)))
	recipient := solana.PrivateKey(ed25519.NewKeyFromSeed(bytes.Repeat([]byte{2}, 32))).PublicKey()
	cfg := xc.NewChainConfig(xc.SOL).Base()
	b, err := builder.NewTxBuilder(cfg)
	require.NoError(t, err)
	for _, version := range []string{"", "legacy", "v0", "v1"} {
		t.Run(version, func(t *testing.T) {
			input := tx_input.NewTxInput()
			input.TransactionVersion = version
			input.ComputeUnitLimit = 20_000
			input.LoadedAccountsDataSizeLimit = 65_536
			input.PrioritizationFee = xc.NewAmountBlockchainFromUint64(250_000)
			input.BaseFee = xc.NewAmountBlockchainFromUint64(5000)
			args, err := xcbuilder.NewTransferArgs(cfg, xc.Address(key.PublicKey().String()), xc.Address(recipient.String()), xc.NewAmountBlockchainFromUint64(10_000_000))
			require.NoError(t, err)
			built, err := b.Transfer(args, input)
			require.NoError(t, err)
			requests, err := built.Sighashes()
			require.NoError(t, err)
			require.Len(t, requests, 1)
			signature := ed25519.Sign(ed25519.PrivateKey(key), requests[0].Payload)
			require.NoError(t, built.SetSignatures(&xc.SignatureResponse{Signature: signature}))
			wire, err := built.Serialize()
			require.NoError(t, err)
			decoded, err := solana.TransactionFromBytes(wire)
			require.NoError(t, err)
			require.NoError(t, decoded.VerifySignatures())
			wantVersion, err := input.MessageVersion()
			require.NoError(t, err)
			require.Equal(t, wantVersion, decoded.Message.GetVersion())
			transfers := tx.NewDecoderFromNativeTx(decoded, &rpc.TransactionMeta{}).GetSystemTransfers()
			require.Len(t, transfers, 1)
			require.Equal(t, uint64(10_000_000), *transfers[0].Instruction.Lamports)
			if version == "v1" {
				require.Equal(t, byte(0x81), wire[0])
				require.Len(t, decoded.Message.Instructions, 1)
				require.Equal(t, kitV1Transfer, base64.StdEncoding.EncodeToString(wire))
				fee, _ := input.GetFeeLimit()
				require.Equal(t, uint64(10_000), fee.Uint64())
			}
		})
	}
}

func TestV1CallRoundTrip(t *testing.T) {
	wire, err := base64.StdEncoding.DecodeString(kitV1Transfer)
	require.NoError(t, err)
	solTx, err := solana.TransactionFromBytes(wire)
	require.NoError(t, err)
	raw, err := json.Marshal(call.Call{Transaction: wire})
	require.NoError(t, err)
	signer := xc.Address(solTx.Message.AccountKeys[0].String())
	c, err := call.NewCall(xc.NewChainConfig(xc.SOL).Base(), xccall.SolanaSignTransaction, raw, []xc.Address{signer})
	require.NoError(t, err)
	encoded, err := c.Serialize()
	require.NoError(t, err)
	require.Equal(t, wire, encoded)
	input := &tx_input.CallInput{TxInput: *tx_input.NewTxInput()}
	input.BaseFee = xc.NewAmountBlockchainFromUint64(5000)
	payload, ok := c.GetPayload()
	require.True(t, ok)
	require.NoError(t, input.SetCall(payload))
	fee, _ := input.GetFeeLimit()
	require.Equal(t, uint64(10_000), fee.Uint64())
	input.RecentBlockHash = solana.Hash{9}
	require.NoError(t, c.SetInput(input))
	requests, err := c.Sighashes()
	require.NoError(t, err)
	key := ed25519.NewKeyFromSeed(bytes.Repeat([]byte{1}, 32))
	require.NoError(t, c.SetSignatures(&xc.SignatureResponse{PublicKey: key.Public().(ed25519.PublicKey), Signature: ed25519.Sign(key, requests[0].Payload)}))
	encoded, err = c.Serialize()
	require.NoError(t, err)
	resigned, err := solana.TransactionFromBytes(encoded)
	require.NoError(t, err)
	require.NoError(t, resigned.VerifySignatures())
	require.Equal(t, solana.Hash{9}, resigned.Message.RecentBlockhash)
	require.Equal(t, solTx.Message.TransactionConfig, resigned.Message.TransactionConfig)
}

func TestV1FeePayerNonceAndTokenTransfers(t *testing.T) {
	cfg := xc.NewChainConfig(xc.SOL).Base()
	b, err := builder.NewTxBuilder(cfg)
	require.NoError(t, err)
	sender, payer, recipient := solana.NewWallet(), solana.NewWallet(), solana.NewWallet()
	for _, tokenTransfer := range []bool{false, true} {
		input := tx_input.NewTxInput()
		input.BaseFee = xc.NewAmountBlockchainFromUint64(5000)
		input.SignatureCount = 2
		input.ComputeUnitLimit = 100_000
		input.LoadedAccountsDataSizeLimit = 65_536
		input.DurableNonce = solana.Hash{7}
		input.DurableNonceAccount = solana.PublicKey{8}
		input.DurableNonceAuthority = sender.PublicKey()
		options := []xcbuilder.BuilderOption{
			xcbuilder.OptionFeePayer(xc.Address(payer.PublicKey().String()), payer.PublicKey().Bytes()),
			xcbuilder.OptionMemo("v1 regression"),
		}
		if tokenTransfer {
			input.TokenProgram = solana.Token2022ProgramID
			input.ShouldCreateATA = true
			options = append(options, xcbuilder.OptionContractAddress(xc.ContractAddress(solana.PublicKey{9}.String()), 6))
		}
		args, err := xcbuilder.NewTransferArgs(cfg, xc.Address(sender.PublicKey().String()), xc.Address(recipient.PublicKey().String()), xc.NewAmountBlockchainFromUint64(1_000_000), options...)
		require.NoError(t, err)
		built, err := b.Transfer(args, input)
		require.NoError(t, err)
		requests, err := built.Sighashes()
		require.NoError(t, err)
		require.Len(t, requests, 2)
		payerSig, err := payer.PrivateKey.Sign(requests[0].Payload)
		require.NoError(t, err)
		senderSig, err := sender.PrivateKey.Sign(requests[1].Payload)
		require.NoError(t, err)
		require.NoError(t, built.SetSignatures(&xc.SignatureResponse{Signature: payerSig[:]}, &xc.SignatureResponse{Signature: senderSig[:]}))
		wire, err := built.Serialize()
		require.NoError(t, err)
		decoded, err := solana.TransactionFromBytes(wire)
		require.NoError(t, err)
		require.NoError(t, decoded.VerifySignatures())
		require.Equal(t, solana.Hash{7}, decoded.Message.RecentBlockhash)
		require.Equal(t, payer.PublicKey(), decoded.Message.AccountKeys[0])
		decoder := tx.NewDecoderFromNativeTx(decoded, &rpc.TransactionMeta{})
		require.Len(t, decoder.GetMemos(), 1)
		for _, instruction := range decoder.GetResolvedInstructions() {
			require.NotEqual(t, solana.ComputeBudget, instruction.ProgramID)
		}
		if tokenTransfer {
			require.Len(t, decoder.GetTokenTransferCheckeds(), 1)
		} else {
			require.Len(t, decoder.GetSystemTransfers(), 1)
		}
		fee, _ := input.GetFeeLimit()
		require.Equal(t, uint64(10_000), fee.Uint64())
	}
}

func TestV1RejectMalformedWire(t *testing.T) {
	wire, err := base64.StdEncoding.DecodeString(kitV1Transfer)
	require.NoError(t, err)
	for length := 0; length < len(wire); length++ {
		_, err := solana.TransactionFromBytes(wire[:length])
		require.Error(t, err, "truncated transaction of length %d", length)
	}
	_, err = solana.TransactionFromBytes(append(append([]byte{}, wire...), 0))
	require.Error(t, err, "trailing bytes must be rejected")
	unknownConfig := append([]byte{}, wire...)
	unknownConfig[4] |= 0x20
	_, err = solana.TransactionFromBytes(unknownConfig)
	require.Error(t, err, "unknown config bits must be rejected")
}
