package tx_input

import (
	"encoding/binary"
	"encoding/json"
	"fmt"

	xc "github.com/cordialsys/crosschain"
	"github.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2/interactive"
	"github.com/cordialsys/crosschain/factory/drivers/registry"
)

const (
	CreateAccountStageAllocate = "allocate_external_party"
	CreateAccountStageAccept   = "accept_external_party_setup_proposal"
)

// Signature index constants callers use to address specific payloads.
const (
	SigIdxCreateAccount = 0
)

// CreateAccountInput holds the next Canton account-registration step that still
// requires an explicit external signature.
type CreateAccountInput struct {
	Stage string `json:"stage"`

	// Used only for conflict checking
	// The PartyID is the same as the address.
	PartyID string `json:"party_id"`

	// Need to make the tx submit -- likely we can compute this on our own
	// and drop it from the input
	PublicKeyFingerprint string `json:"public_key_fingerprint,omitempty"`

	// This is generated by the canton node and is rather opaque.
	TopologyTransactions [][]byte `json:"topology_transactions,omitempty"`

	// Server-prepared Canton interactive transaction for accepting the external
	// party setup proposal. It is hashed for external-party signing and later
	// submitted with the signature.
	SetupProposalPreparedTransaction *interactive.PreparedTransaction `json:"setup_proposal_prepared_transaction,omitempty"`
	SetupProposalHashing             interactive.HashingSchemeVersion `json:"setup_proposal_hashing,omitempty"`
	SetupProposalSubmissionID        string                           `json:"setup_proposal_submission_id,omitempty"`

	Signature []byte `json:"signature,omitempty"`
}

var _ xc.TxVariantInput = &CreateAccountInput{}
var _ xc.CreateAccountTxInput = &CreateAccountInput{}
var _ cantonConflictInput = &CreateAccountInput{}

func init() {
	registry.RegisterTxVariantInput(&CreateAccountInput{})
}

type createAccountInputInner CreateAccountInput

func (i *CreateAccountInput) MarshalJSON() ([]byte, error) {
	var prepared json.RawMessage
	if i.SetupProposalPreparedTransaction != nil {
		bz, err := MarshalPreparedTransactionJSON(i.SetupProposalPreparedTransaction)
		if err != nil {
			return nil, err
		}
		prepared = bz
	}
	type createAccountInputJSON struct {
		*createAccountInputInner
		SetupProposalPreparedTransaction json.RawMessage `json:"setup_proposal_prepared_transaction,omitempty"`
	}
	return json.Marshal(createAccountInputJSON{
		createAccountInputInner:          (*createAccountInputInner)(i),
		SetupProposalPreparedTransaction: prepared,
	})
}

func (i *CreateAccountInput) UnmarshalJSON(data []byte) error {
	type createAccountInputJSON struct {
		*createAccountInputInner
		SetupProposalPreparedTransaction json.RawMessage `json:"setup_proposal_prepared_transaction,omitempty"`
	}
	wire := createAccountInputJSON{
		createAccountInputInner: (*createAccountInputInner)(i),
	}
	if err := json.Unmarshal(data, &wire); err != nil {
		return err
	}
	i.SetupProposalPreparedTransaction = nil
	if len(wire.SetupProposalPreparedTransaction) > 0 && string(wire.SetupProposalPreparedTransaction) != "null" {
		prepared, err := UnmarshalPreparedTransactionJSON(wire.SetupProposalPreparedTransaction)
		if err != nil {
			return err
		}
		i.SetupProposalPreparedTransaction = prepared
	}
	return nil
}

func (*CreateAccountInput) CreatingAccount() {}

func (*CreateAccountInput) GetVariant() xc.TxVariantInputType {
	return xc.NewCreateAccountInputType(xc.DriverCanton, string(xc.Native))
}

func (*CreateAccountInput) GetDriver() xc.Driver {
	return xc.DriverCanton
}

func (*CreateAccountInput) SetGasFeePriority(_ xc.GasFeePriority) error {
	return nil
}

func (*CreateAccountInput) GetFeeLimit() (xc.AmountBlockchain, xc.ContractAddress) {
	return xc.NewAmountBlockchainFromUint64(0), ""
}

func (*CreateAccountInput) IsFeeLimitAccurate() bool {
	return true
}

func (i *CreateAccountInput) IndependentOf(other xc.TxInput) bool {
	return cantonIndependentOf(i, other)
}

func (i *CreateAccountInput) SafeFromDoubleSend(other xc.TxInput) bool {
	return cantonSafeFromDoubleSend(i, other)
}

func ParseCreateAccountInput(data []byte) (*CreateAccountInput, error) {
	if len(data) < 8 {
		return nil, fmt.Errorf("create-account input is too short")
	}

	metadataLen := binary.BigEndian.Uint64(data[:8])
	if metadataLen > uint64(len(data)-8) {
		return nil, fmt.Errorf("invalid create-account metadata length %d", metadataLen)
	}

	var input CreateAccountInput
	metadata := data[8 : 8+metadataLen]
	if err := json.Unmarshal(metadata, &input); err != nil {
		return nil, err
	}
	if input.Stage == "" {
		return nil, fmt.Errorf("missing create-account stage")
	}
	input.Signature = append([]byte(nil), data[8+metadataLen:]...)
	return &input, nil
}

func (i *CreateAccountInput) Serialize() ([]byte, error) {
	metadata, err := i.metadataBytes()
	if err != nil {
		return nil, err
	}

	payload := make([]byte, 8+len(metadata)+len(i.Signature))
	binary.BigEndian.PutUint64(payload[:8], uint64(len(metadata)))
	copy(payload[8:], metadata)
	copy(payload[8+len(metadata):], i.Signature)
	return payload, nil
}

func (i *CreateAccountInput) SetSignatures(sigs ...*xc.SignatureResponse) error {
	if len(sigs) != 1 {
		return fmt.Errorf("expected 1 signature, got %d", len(sigs))
	}
	i.Signature = sigs[SigIdxCreateAccount].Signature
	return nil
}

func (i *CreateAccountInput) VerifySignaturePayloads() error {
	if i.PartyID == "" {
		return fmt.Errorf("party ID is empty")
	}
	switch i.Stage {
	case CreateAccountStageAllocate:
		if len(i.TopologyTransactions) == 0 {
			return fmt.Errorf("topology transactions are empty")
		}
	case CreateAccountStageAccept:
		if i.SetupProposalPreparedTransaction == nil {
			return fmt.Errorf("setup proposal prepared transaction is empty")
		}
	default:
		return fmt.Errorf("unsupported create-account stage %q", i.Stage)
	}
	return nil
}

func (i *CreateAccountInput) cantonSubmissionID() string {
	if i == nil {
		return ""
	}
	return i.SetupProposalSubmissionID
}

func (i *CreateAccountInput) cantonConflictContractIDsKnown() bool {
	if i == nil {
		return false
	}
	switch i.Stage {
	case CreateAccountStageAllocate:
		return true
	case CreateAccountStageAccept:
		return i.SetupProposalPreparedTransaction != nil
	default:
		return false
	}
}

func (i *CreateAccountInput) cantonConflictContractIDs() []string {
	if i == nil || i.SetupProposalPreparedTransaction == nil {
		return nil
	}
	return consumingContractIDs(i.SetupProposalPreparedTransaction)
}

func (i *CreateAccountInput) cantonConflictKey() string {
	if i == nil || i.PartyID == "" || i.Stage == "" {
		return ""
	}
	return i.PartyID + "/" + i.Stage
}

func (i *CreateAccountInput) metadataBytes() ([]byte, error) {
	metadata := *i
	metadata.Signature = nil
	return json.Marshal(metadata)
}
