// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/command_service.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These commands are executed as a single atomic transaction.
type SubmitAndWaitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The commands to be submitted.
	//
	// Required
	Commands      *Commands `protobuf:"bytes,1,opt,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAndWaitRequest) Reset() {
	*x = SubmitAndWaitRequest{}
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndWaitRequest) ProtoMessage() {}

func (x *SubmitAndWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndWaitRequest.ProtoReflect.Descriptor instead.
func (*SubmitAndWaitRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitAndWaitRequest) GetCommands() *Commands {
	if x != nil {
		return x.Commands
	}
	return nil
}

// These commands are executed as a single atomic transaction.
type SubmitAndWaitForTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The commands to be submitted.
	//
	// Required
	Commands *Commands `protobuf:"bytes,1,opt,name=commands,proto3" json:"commands,omitempty"`
	// If no “transaction_format“ is provided, a default will be used where “transaction_shape“ is set to
	// TRANSACTION_SHAPE_ACS_DELTA, “event_format“ is defined with “filters_by_party“ containing wildcard-template
	// filter for all original “act_as“ and “read_as“ parties and the “verbose“ flag is set.
	//
	// Optional
	TransactionFormat *TransactionFormat `protobuf:"bytes,2,opt,name=transaction_format,json=transactionFormat,proto3" json:"transaction_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitAndWaitForTransactionRequest) Reset() {
	*x = SubmitAndWaitForTransactionRequest{}
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndWaitForTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndWaitForTransactionRequest) ProtoMessage() {}

func (x *SubmitAndWaitForTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndWaitForTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitAndWaitForTransactionRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAndWaitForTransactionRequest) GetCommands() *Commands {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *SubmitAndWaitForTransactionRequest) GetTransactionFormat() *TransactionFormat {
	if x != nil {
		return x.TransactionFormat
	}
	return nil
}

type SubmitAndWaitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the transaction that resulted from the submitted command.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The details of the offset field are described in “community/ledger-api/README.md“.
	//
	// Required
	CompletionOffset int64 `protobuf:"varint,2,opt,name=completion_offset,json=completionOffset,proto3" json:"completion_offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitAndWaitResponse) Reset() {
	*x = SubmitAndWaitResponse{}
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndWaitResponse) ProtoMessage() {}

func (x *SubmitAndWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndWaitResponse.ProtoReflect.Descriptor instead.
func (*SubmitAndWaitResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitAndWaitResponse) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *SubmitAndWaitResponse) GetCompletionOffset() int64 {
	if x != nil {
		return x.CompletionOffset
	}
	return 0
}

type SubmitAndWaitForTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction that resulted from the submitted command.
	// The transaction might contain no events (request conditions result in filtering out all of them).
	//
	// Required
	Transaction   *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAndWaitForTransactionResponse) Reset() {
	*x = SubmitAndWaitForTransactionResponse{}
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndWaitForTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndWaitForTransactionResponse) ProtoMessage() {}

func (x *SubmitAndWaitForTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndWaitForTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitAndWaitForTransactionResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitAndWaitForTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// This reassignment is executed as a single atomic update.
type SubmitAndWaitForReassignmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reassignment commands to be submitted.
	//
	// Required
	ReassignmentCommands *ReassignmentCommands `protobuf:"bytes,1,opt,name=reassignment_commands,json=reassignmentCommands,proto3" json:"reassignment_commands,omitempty"`
	// If no event_format provided, the result will contain no events.
	// The events in the result, will take shape TRANSACTION_SHAPE_ACS_DELTA.
	//
	// Optional
	EventFormat   *EventFormat `protobuf:"bytes,2,opt,name=event_format,json=eventFormat,proto3" json:"event_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAndWaitForReassignmentRequest) Reset() {
	*x = SubmitAndWaitForReassignmentRequest{}
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndWaitForReassignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndWaitForReassignmentRequest) ProtoMessage() {}

func (x *SubmitAndWaitForReassignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndWaitForReassignmentRequest.ProtoReflect.Descriptor instead.
func (*SubmitAndWaitForReassignmentRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAndWaitForReassignmentRequest) GetReassignmentCommands() *ReassignmentCommands {
	if x != nil {
		return x.ReassignmentCommands
	}
	return nil
}

func (x *SubmitAndWaitForReassignmentRequest) GetEventFormat() *EventFormat {
	if x != nil {
		return x.EventFormat
	}
	return nil
}

type SubmitAndWaitForReassignmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reassignment that resulted from the submitted reassignment command.
	// The reassignment might contain no events (request conditions result in filtering out all of them).
	//
	// Required
	Reassignment  *Reassignment `protobuf:"bytes,1,opt,name=reassignment,proto3" json:"reassignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAndWaitForReassignmentResponse) Reset() {
	*x = SubmitAndWaitForReassignmentResponse{}
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndWaitForReassignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndWaitForReassignmentResponse) ProtoMessage() {}

func (x *SubmitAndWaitForReassignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndWaitForReassignmentResponse.ProtoReflect.Descriptor instead.
func (*SubmitAndWaitForReassignmentResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAndWaitForReassignmentResponse) GetReassignment() *Reassignment {
	if x != nil {
		return x.Reassignment
	}
	return nil
}

var File_com_daml_ledger_api_v2_command_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_command_service_proto_rawDesc = "" +
	"\n" +
	",com/daml/ledger/api/v2/command_service.proto\x12\x16com.daml.ledger.api.v2\x1a%com/daml/ledger/api/v2/commands.proto\x1a)com/daml/ledger/api/v2/reassignment.proto\x1a2com/daml/ledger/api/v2/reassignment_commands.proto\x1a(com/daml/ledger/api/v2/transaction.proto\x1a/com/daml/ledger/api/v2/transaction_filter.proto\"T\n" +
	"\x14SubmitAndWaitRequest\x12<\n" +
	"\bcommands\x18\x01 \x01(\v2 .com.daml.ledger.api.v2.CommandsR\bcommands\"\xbc\x01\n" +
	"\"SubmitAndWaitForTransactionRequest\x12<\n" +
	"\bcommands\x18\x01 \x01(\v2 .com.daml.ledger.api.v2.CommandsR\bcommands\x12X\n" +
	"\x12transaction_format\x18\x02 \x01(\v2).com.daml.ledger.api.v2.TransactionFormatR\x11transactionFormat\"a\n" +
	"\x15SubmitAndWaitResponse\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12+\n" +
	"\x11completion_offset\x18\x02 \x01(\x03R\x10completionOffset\"l\n" +
	"#SubmitAndWaitForTransactionResponse\x12E\n" +
	"\vtransaction\x18\x01 \x01(\v2#.com.daml.ledger.api.v2.TransactionR\vtransaction\"\xd0\x01\n" +
	"#SubmitAndWaitForReassignmentRequest\x12a\n" +
	"\x15reassignment_commands\x18\x01 \x01(\v2,.com.daml.ledger.api.v2.ReassignmentCommandsR\x14reassignmentCommands\x12F\n" +
	"\fevent_format\x18\x02 \x01(\v2#.com.daml.ledger.api.v2.EventFormatR\veventFormat\"p\n" +
	"$SubmitAndWaitForReassignmentResponse\x12H\n" +
	"\freassignment\x18\x01 \x01(\v2$.com.daml.ledger.api.v2.ReassignmentR\freassignment2\xb3\x03\n" +
	"\x0eCommandService\x12l\n" +
	"\rSubmitAndWait\x12,.com.daml.ledger.api.v2.SubmitAndWaitRequest\x1a-.com.daml.ledger.api.v2.SubmitAndWaitResponse\x12\x96\x01\n" +
	"\x1bSubmitAndWaitForTransaction\x12:.com.daml.ledger.api.v2.SubmitAndWaitForTransactionRequest\x1a;.com.daml.ledger.api.v2.SubmitAndWaitForTransactionResponse\x12\x99\x01\n" +
	"\x1cSubmitAndWaitForReassignment\x12;.com.daml.ledger.api.v2.SubmitAndWaitForReassignmentRequest\x1a<.com.daml.ledger.api.v2.SubmitAndWaitForReassignmentResponseB\x80\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x13CommandServiceProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_command_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_command_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_command_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_command_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_command_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_command_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_command_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_command_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_command_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_com_daml_ledger_api_v2_command_service_proto_goTypes = []any{
	(*SubmitAndWaitRequest)(nil),                 // 0: com.daml.ledger.api.v2.SubmitAndWaitRequest
	(*SubmitAndWaitForTransactionRequest)(nil),   // 1: com.daml.ledger.api.v2.SubmitAndWaitForTransactionRequest
	(*SubmitAndWaitResponse)(nil),                // 2: com.daml.ledger.api.v2.SubmitAndWaitResponse
	(*SubmitAndWaitForTransactionResponse)(nil),  // 3: com.daml.ledger.api.v2.SubmitAndWaitForTransactionResponse
	(*SubmitAndWaitForReassignmentRequest)(nil),  // 4: com.daml.ledger.api.v2.SubmitAndWaitForReassignmentRequest
	(*SubmitAndWaitForReassignmentResponse)(nil), // 5: com.daml.ledger.api.v2.SubmitAndWaitForReassignmentResponse
	(*Commands)(nil),                             // 6: com.daml.ledger.api.v2.Commands
	(*TransactionFormat)(nil),                    // 7: com.daml.ledger.api.v2.TransactionFormat
	(*Transaction)(nil),                          // 8: com.daml.ledger.api.v2.Transaction
	(*ReassignmentCommands)(nil),                 // 9: com.daml.ledger.api.v2.ReassignmentCommands
	(*EventFormat)(nil),                          // 10: com.daml.ledger.api.v2.EventFormat
	(*Reassignment)(nil),                         // 11: com.daml.ledger.api.v2.Reassignment
}
var file_com_daml_ledger_api_v2_command_service_proto_depIdxs = []int32{
	6,  // 0: com.daml.ledger.api.v2.SubmitAndWaitRequest.commands:type_name -> com.daml.ledger.api.v2.Commands
	6,  // 1: com.daml.ledger.api.v2.SubmitAndWaitForTransactionRequest.commands:type_name -> com.daml.ledger.api.v2.Commands
	7,  // 2: com.daml.ledger.api.v2.SubmitAndWaitForTransactionRequest.transaction_format:type_name -> com.daml.ledger.api.v2.TransactionFormat
	8,  // 3: com.daml.ledger.api.v2.SubmitAndWaitForTransactionResponse.transaction:type_name -> com.daml.ledger.api.v2.Transaction
	9,  // 4: com.daml.ledger.api.v2.SubmitAndWaitForReassignmentRequest.reassignment_commands:type_name -> com.daml.ledger.api.v2.ReassignmentCommands
	10, // 5: com.daml.ledger.api.v2.SubmitAndWaitForReassignmentRequest.event_format:type_name -> com.daml.ledger.api.v2.EventFormat
	11, // 6: com.daml.ledger.api.v2.SubmitAndWaitForReassignmentResponse.reassignment:type_name -> com.daml.ledger.api.v2.Reassignment
	0,  // 7: com.daml.ledger.api.v2.CommandService.SubmitAndWait:input_type -> com.daml.ledger.api.v2.SubmitAndWaitRequest
	1,  // 8: com.daml.ledger.api.v2.CommandService.SubmitAndWaitForTransaction:input_type -> com.daml.ledger.api.v2.SubmitAndWaitForTransactionRequest
	4,  // 9: com.daml.ledger.api.v2.CommandService.SubmitAndWaitForReassignment:input_type -> com.daml.ledger.api.v2.SubmitAndWaitForReassignmentRequest
	2,  // 10: com.daml.ledger.api.v2.CommandService.SubmitAndWait:output_type -> com.daml.ledger.api.v2.SubmitAndWaitResponse
	3,  // 11: com.daml.ledger.api.v2.CommandService.SubmitAndWaitForTransaction:output_type -> com.daml.ledger.api.v2.SubmitAndWaitForTransactionResponse
	5,  // 12: com.daml.ledger.api.v2.CommandService.SubmitAndWaitForReassignment:output_type -> com.daml.ledger.api.v2.SubmitAndWaitForReassignmentResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_command_service_proto_init() }
func file_com_daml_ledger_api_v2_command_service_proto_init() {
	if File_com_daml_ledger_api_v2_command_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_commands_proto_init()
	file_com_daml_ledger_api_v2_reassignment_proto_init()
	file_com_daml_ledger_api_v2_reassignment_commands_proto_init()
	file_com_daml_ledger_api_v2_transaction_proto_init()
	file_com_daml_ledger_api_v2_transaction_filter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_command_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_command_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_command_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_command_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_command_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_command_service_proto = out.File
	file_com_daml_ledger_api_v2_command_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_command_service_proto_depIdxs = nil
}
