// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/commands.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A command can either create a new contract or exercise a choice on an existing contract.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	//
	// Types that are valid to be assigned to Command:
	//
	//	*Command_Create
	//	*Command_Exercise
	//	*Command_ExerciseByKey
	//	*Command_CreateAndExercise
	Command       isCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommand() isCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Command) GetCreate() *CreateCommand {
	if x != nil {
		if x, ok := x.Command.(*Command_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *Command) GetExercise() *ExerciseCommand {
	if x != nil {
		if x, ok := x.Command.(*Command_Exercise); ok {
			return x.Exercise
		}
	}
	return nil
}

func (x *Command) GetExerciseByKey() *ExerciseByKeyCommand {
	if x != nil {
		if x, ok := x.Command.(*Command_ExerciseByKey); ok {
			return x.ExerciseByKey
		}
	}
	return nil
}

func (x *Command) GetCreateAndExercise() *CreateAndExerciseCommand {
	if x != nil {
		if x, ok := x.Command.(*Command_CreateAndExercise); ok {
			return x.CreateAndExercise
		}
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_Create struct {
	Create *CreateCommand `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type Command_Exercise struct {
	Exercise *ExerciseCommand `protobuf:"bytes,2,opt,name=exercise,proto3,oneof"`
}

type Command_ExerciseByKey struct {
	ExerciseByKey *ExerciseByKeyCommand `protobuf:"bytes,4,opt,name=exercise_by_key,json=exerciseByKey,proto3,oneof"`
}

type Command_CreateAndExercise struct {
	CreateAndExercise *CreateAndExerciseCommand `protobuf:"bytes,3,opt,name=create_and_exercise,json=createAndExercise,proto3,oneof"`
}

func (*Command_Create) isCommand_Command() {}

func (*Command_Exercise) isCommand_Command() {}

func (*Command_ExerciseByKey) isCommand_Command() {}

func (*Command_CreateAndExercise) isCommand_Command() {}

// Create a new contract instance based on a template.
type CreateCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The template of contract the client wants to create.
	// Both package-name and package-id reference identifier formats for the template-id are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The arguments required for creating a contract from this template.
	//
	// Required
	CreateArguments *Record `protobuf:"bytes,2,opt,name=create_arguments,json=createArguments,proto3" json:"create_arguments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCommand) Reset() {
	*x = CreateCommand{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommand) ProtoMessage() {}

func (x *CreateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommand.ProtoReflect.Descriptor instead.
func (*CreateCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommand) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *CreateCommand) GetCreateArguments() *Record {
	if x != nil {
		return x.CreateArguments
	}
	return nil
}

// Exercise a choice on an existing contract.
type ExerciseCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The template or interface of the contract the client wants to exercise.
	// Both package-name and package-id reference identifier formats for the template-id are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	// To exercise a choice on an interface, specify the interface identifier in the template_id field.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The ID of the contract the client wants to exercise upon.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// The name of the choice the client wants to exercise.
	// Must be a valid NameString (as described in “value.proto“)
	//
	// Required
	Choice string `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	// The argument for this choice.
	//
	// Required
	ChoiceArgument *Value `protobuf:"bytes,4,opt,name=choice_argument,json=choiceArgument,proto3" json:"choice_argument,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExerciseCommand) Reset() {
	*x = ExerciseCommand{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseCommand) ProtoMessage() {}

func (x *ExerciseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseCommand.ProtoReflect.Descriptor instead.
func (*ExerciseCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ExerciseCommand) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *ExerciseCommand) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ExerciseCommand) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *ExerciseCommand) GetChoiceArgument() *Value {
	if x != nil {
		return x.ChoiceArgument
	}
	return nil
}

// Exercise a choice on an existing contract specified by its key.
type ExerciseByKeyCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The template of contract the client wants to exercise.
	// Both package-name and package-id reference identifier formats for the template-id are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The key of the contract the client wants to exercise upon.
	//
	// Required
	ContractKey *Value `protobuf:"bytes,2,opt,name=contract_key,json=contractKey,proto3" json:"contract_key,omitempty"`
	// The name of the choice the client wants to exercise.
	// Must be a valid NameString (as described in “value.proto“)
	//
	// Required
	Choice string `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	// The argument for this choice.
	//
	// Required
	ChoiceArgument *Value `protobuf:"bytes,4,opt,name=choice_argument,json=choiceArgument,proto3" json:"choice_argument,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExerciseByKeyCommand) Reset() {
	*x = ExerciseByKeyCommand{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseByKeyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseByKeyCommand) ProtoMessage() {}

func (x *ExerciseByKeyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseByKeyCommand.ProtoReflect.Descriptor instead.
func (*ExerciseByKeyCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{3}
}

func (x *ExerciseByKeyCommand) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *ExerciseByKeyCommand) GetContractKey() *Value {
	if x != nil {
		return x.ContractKey
	}
	return nil
}

func (x *ExerciseByKeyCommand) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *ExerciseByKeyCommand) GetChoiceArgument() *Value {
	if x != nil {
		return x.ChoiceArgument
	}
	return nil
}

// Create a contract and exercise a choice on it in the same transaction.
type CreateAndExerciseCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The template of the contract the client wants to create.
	// Both package-name and package-id reference identifier formats for the template-id are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The arguments required for creating a contract from this template.
	//
	// Required
	CreateArguments *Record `protobuf:"bytes,2,opt,name=create_arguments,json=createArguments,proto3" json:"create_arguments,omitempty"`
	// The name of the choice the client wants to exercise.
	// Must be a valid NameString (as described in “value.proto“).
	//
	// Required
	Choice string `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	// The argument for this choice.
	//
	// Required
	ChoiceArgument *Value `protobuf:"bytes,4,opt,name=choice_argument,json=choiceArgument,proto3" json:"choice_argument,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAndExerciseCommand) Reset() {
	*x = CreateAndExerciseCommand{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAndExerciseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAndExerciseCommand) ProtoMessage() {}

func (x *CreateAndExerciseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAndExerciseCommand.ProtoReflect.Descriptor instead.
func (*CreateAndExerciseCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAndExerciseCommand) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *CreateAndExerciseCommand) GetCreateArguments() *Record {
	if x != nil {
		return x.CreateArguments
	}
	return nil
}

func (x *CreateAndExerciseCommand) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *CreateAndExerciseCommand) GetChoiceArgument() *Value {
	if x != nil {
		return x.ChoiceArgument
	}
	return nil
}

// An additional contract that is used to resolve
// contract & contract key lookups.
type DisclosedContract struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The template id of the contract.
	// The identifier uses the package-id reference format.
	//
	// If provided, used to validate the template id of the contract serialized in the created_event_blob.
	//
	// Optional
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The contract id
	//
	// If provided, used to validate the contract id of the contract serialized in the created_event_blob.
	//
	// Optional
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Opaque byte string containing the complete payload required by the Daml engine
	// to reconstruct a contract not known to the receiving participant.
	//
	// Required: must be non-empty
	CreatedEventBlob []byte `protobuf:"bytes,3,opt,name=created_event_blob,json=createdEventBlob,proto3" json:"created_event_blob,omitempty"`
	// The ID of the synchronizer where the contract is currently assigned
	//
	// Optional
	SynchronizerId string `protobuf:"bytes,4,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DisclosedContract) Reset() {
	*x = DisclosedContract{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisclosedContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisclosedContract) ProtoMessage() {}

func (x *DisclosedContract) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisclosedContract.ProtoReflect.Descriptor instead.
func (*DisclosedContract) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{5}
}

func (x *DisclosedContract) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *DisclosedContract) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *DisclosedContract) GetCreatedEventBlob() []byte {
	if x != nil {
		return x.CreatedEventBlob
	}
	return nil
}

func (x *DisclosedContract) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

// A composite command that groups multiple commands together.
type Commands struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the on-ledger workflow that this command is a part of.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Optional
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Uniquely identifies the participant user that issued the command.
	// Must be a valid UserIdString (as described in “value.proto“).
	// Required unless authentication is used with a user token.
	// In that case, the token's user-id will be used for the request's user_id.
	//
	// Optional
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Uniquely identifies the command.
	// The triple (user_id, act_as, command_id) constitutes the change ID for the intended ledger change,
	// where act_as is interpreted as a set of party names.
	// The change ID can be used for matching the intended ledger changes with all their completions.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	CommandId string `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Individual elements of this atomic command. Must be non-empty.
	//
	// Required: must be non-empty
	Commands []*Command `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	// Specifies the deduplication period for the change ID.
	// If omitted, the participant will assume the configured maximum deduplication time.
	//
	// # Optional
	//
	// Types that are valid to be assigned to DeduplicationPeriod:
	//
	//	*Commands_DeduplicationDuration
	//	*Commands_DeduplicationOffset
	DeduplicationPeriod isCommands_DeduplicationPeriod `protobuf_oneof:"deduplication_period"`
	// Lower bound for the ledger time assigned to the resulting transaction.
	// Note: The ledger time of a transaction is assigned as part of command interpretation.
	// Use this property if you expect that command interpretation will take a considerate amount of time, such that by
	// the time the resulting transaction is sequenced, its assigned ledger time is not valid anymore.
	// Must not be set at the same time as min_ledger_time_rel.
	//
	// Optional
	MinLedgerTimeAbs *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=min_ledger_time_abs,json=minLedgerTimeAbs,proto3" json:"min_ledger_time_abs,omitempty"`
	// Same as min_ledger_time_abs, but specified as a duration, starting from the time the command is received by the server.
	// Must not be set at the same time as min_ledger_time_abs.
	//
	// Optional
	MinLedgerTimeRel *durationpb.Duration `protobuf:"bytes,8,opt,name=min_ledger_time_rel,json=minLedgerTimeRel,proto3" json:"min_ledger_time_rel,omitempty"`
	// Set of parties on whose behalf the command should be executed.
	// If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request
	// to act on behalf of each of the given parties.
	// Each element must be a valid PartyIdString (as described in “value.proto“).
	//
	// Required: must be non-empty
	ActAs []string `protobuf:"bytes,9,rep,name=act_as,json=actAs,proto3" json:"act_as,omitempty"`
	// Set of parties on whose behalf (in addition to all parties listed in “act_as“) contracts can be retrieved.
	// This affects Daml operations such as “fetch“, “fetchByKey“, “lookupByKey“, “exercise“, and “exerciseByKey“.
	// Note: A participant node of a Daml network can host multiple parties. Each contract present on the participant
	// node is only visible to a subset of these parties. A command can only use contracts that are visible to at least
	// one of the parties in “act_as“ or “read_as“. This visibility check is independent from the Daml authorization
	// rules for fetch operations.
	// If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request
	// to read contract data on behalf of each of the given parties.
	//
	// Optional: can be empty
	ReadAs []string `protobuf:"bytes,10,rep,name=read_as,json=readAs,proto3" json:"read_as,omitempty"`
	// A unique identifier to distinguish completions for different submissions with the same change ID.
	// Typically a random UUID. Applications are expected to use a different UUID for each retry of a submission
	// with the same change ID.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// If omitted, the participant or the committer may set a value of their choice.
	//
	// Optional
	SubmissionId string `protobuf:"bytes,11,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	// Additional contracts used to resolve contract & contract key lookups.
	//
	// Optional: can be empty
	DisclosedContracts []*DisclosedContract `protobuf:"bytes,12,rep,name=disclosed_contracts,json=disclosedContracts,proto3" json:"disclosed_contracts,omitempty"`
	// Must be a valid synchronizer id
	//
	// Optional
	SynchronizerId string `protobuf:"bytes,13,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// The package-id selection preference of the client for resolving
	// package names and interface instances in command submission and interpretation
	//
	// Optional: can be empty
	PackageIdSelectionPreference []string `protobuf:"bytes,14,rep,name=package_id_selection_preference,json=packageIdSelectionPreference,proto3" json:"package_id_selection_preference,omitempty"`
	// Fetches the contract keys into the caches to speed up the command processing.
	// Should only contain contract keys that are expected to be resolved during interpretation of the commands.
	// Keys of disclosed contracts do not need prefetching.
	//
	// Optional: can be empty
	PrefetchContractKeys []*PrefetchContractKey `protobuf:"bytes,15,rep,name=prefetch_contract_keys,json=prefetchContractKeys,proto3" json:"prefetch_contract_keys,omitempty"`
	// The maximum number of passes for the Topology-Aware Package Selection (TAPS).
	// Higher values can increase the chance of successful package selection for routing of interpreted transactions.
	// If unset, this defaults to the value defined in the participant configuration.
	// The provided value must not exceed the limit specified in the participant configuration.
	//
	// Optional
	TapsMaxPasses *uint32 `protobuf:"varint,16,opt,name=taps_max_passes,json=tapsMaxPasses,proto3,oneof" json:"taps_max_passes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commands) Reset() {
	*x = Commands{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commands) ProtoMessage() {}

func (x *Commands) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commands.ProtoReflect.Descriptor instead.
func (*Commands) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{6}
}

func (x *Commands) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Commands) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Commands) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Commands) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Commands) GetDeduplicationPeriod() isCommands_DeduplicationPeriod {
	if x != nil {
		return x.DeduplicationPeriod
	}
	return nil
}

func (x *Commands) GetDeduplicationDuration() *durationpb.Duration {
	if x != nil {
		if x, ok := x.DeduplicationPeriod.(*Commands_DeduplicationDuration); ok {
			return x.DeduplicationDuration
		}
	}
	return nil
}

func (x *Commands) GetDeduplicationOffset() int64 {
	if x != nil {
		if x, ok := x.DeduplicationPeriod.(*Commands_DeduplicationOffset); ok {
			return x.DeduplicationOffset
		}
	}
	return 0
}

func (x *Commands) GetMinLedgerTimeAbs() *timestamppb.Timestamp {
	if x != nil {
		return x.MinLedgerTimeAbs
	}
	return nil
}

func (x *Commands) GetMinLedgerTimeRel() *durationpb.Duration {
	if x != nil {
		return x.MinLedgerTimeRel
	}
	return nil
}

func (x *Commands) GetActAs() []string {
	if x != nil {
		return x.ActAs
	}
	return nil
}

func (x *Commands) GetReadAs() []string {
	if x != nil {
		return x.ReadAs
	}
	return nil
}

func (x *Commands) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Commands) GetDisclosedContracts() []*DisclosedContract {
	if x != nil {
		return x.DisclosedContracts
	}
	return nil
}

func (x *Commands) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *Commands) GetPackageIdSelectionPreference() []string {
	if x != nil {
		return x.PackageIdSelectionPreference
	}
	return nil
}

func (x *Commands) GetPrefetchContractKeys() []*PrefetchContractKey {
	if x != nil {
		return x.PrefetchContractKeys
	}
	return nil
}

func (x *Commands) GetTapsMaxPasses() uint32 {
	if x != nil && x.TapsMaxPasses != nil {
		return *x.TapsMaxPasses
	}
	return 0
}

type isCommands_DeduplicationPeriod interface {
	isCommands_DeduplicationPeriod()
}

type Commands_DeduplicationDuration struct {
	// Specifies the length of the deduplication period.
	// It is interpreted relative to the local clock at some point during the submission's processing.
	// Must be non-negative. Must not exceed the maximum deduplication time.
	DeduplicationDuration *durationpb.Duration `protobuf:"bytes,5,opt,name=deduplication_duration,json=deduplicationDuration,proto3,oneof"`
}

type Commands_DeduplicationOffset struct {
	// Specifies the start of the deduplication period by a completion stream offset (exclusive).
	// Must be a valid absolute offset (positive integer) or participant begin (zero).
	DeduplicationOffset int64 `protobuf:"varint,6,opt,name=deduplication_offset,json=deduplicationOffset,proto3,oneof"`
}

func (*Commands_DeduplicationDuration) isCommands_DeduplicationPeriod() {}

func (*Commands_DeduplicationOffset) isCommands_DeduplicationPeriod() {}

// Preload contracts
type PrefetchContractKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The template of contract the client wants to prefetch.
	// Both package-name and package-id reference identifier formats for the template-id are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// The key of the contract the client wants to prefetch.
	//
	// Required
	ContractKey   *Value `protobuf:"bytes,2,opt,name=contract_key,json=contractKey,proto3" json:"contract_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefetchContractKey) Reset() {
	*x = PrefetchContractKey{}
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchContractKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchContractKey) ProtoMessage() {}

func (x *PrefetchContractKey) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchContractKey.ProtoReflect.Descriptor instead.
func (*PrefetchContractKey) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP(), []int{7}
}

func (x *PrefetchContractKey) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *PrefetchContractKey) GetContractKey() *Value {
	if x != nil {
		return x.ContractKey
	}
	return nil
}

var File_com_daml_ledger_api_v2_commands_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_commands_proto_rawDesc = "" +
	"\n" +
	"%com/daml/ledger/api/v2/commands.proto\x12\x16com.daml.ledger.api.v2\x1a\"com/daml/ledger/api/v2/value.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x02\n" +
	"\aCommand\x12?\n" +
	"\x06create\x18\x01 \x01(\v2%.com.daml.ledger.api.v2.CreateCommandH\x00R\x06create\x12E\n" +
	"\bexercise\x18\x02 \x01(\v2'.com.daml.ledger.api.v2.ExerciseCommandH\x00R\bexercise\x12V\n" +
	"\x0fexercise_by_key\x18\x04 \x01(\v2,.com.daml.ledger.api.v2.ExerciseByKeyCommandH\x00R\rexerciseByKey\x12b\n" +
	"\x13create_and_exercise\x18\x03 \x01(\v20.com.daml.ledger.api.v2.CreateAndExerciseCommandH\x00R\x11createAndExerciseB\t\n" +
	"\acommand\"\x9f\x01\n" +
	"\rCreateCommand\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12I\n" +
	"\x10create_arguments\x18\x02 \x01(\v2\x1e.com.daml.ledger.api.v2.RecordR\x0fcreateArguments\"\xd7\x01\n" +
	"\x0fExerciseCommand\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06choice\x18\x03 \x01(\tR\x06choice\x12F\n" +
	"\x0fchoice_argument\x18\x04 \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\x0echoiceArgument\"\xfd\x01\n" +
	"\x14ExerciseByKeyCommand\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12@\n" +
	"\fcontract_key\x18\x02 \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\vcontractKey\x12\x16\n" +
	"\x06choice\x18\x03 \x01(\tR\x06choice\x12F\n" +
	"\x0fchoice_argument\x18\x04 \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\x0echoiceArgument\"\x8a\x02\n" +
	"\x18CreateAndExerciseCommand\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12I\n" +
	"\x10create_arguments\x18\x02 \x01(\v2\x1e.com.daml.ledger.api.v2.RecordR\x0fcreateArguments\x12\x16\n" +
	"\x06choice\x18\x03 \x01(\tR\x06choice\x12F\n" +
	"\x0fchoice_argument\x18\x04 \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\x0echoiceArgument\"\xd0\x01\n" +
	"\x11DisclosedContract\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12,\n" +
	"\x12created_event_blob\x18\x03 \x01(\fR\x10createdEventBlob\x12'\n" +
	"\x0fsynchronizer_id\x18\x04 \x01(\tR\x0esynchronizerId\"\x9b\a\n" +
	"\bCommands\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12;\n" +
	"\bcommands\x18\x04 \x03(\v2\x1f.com.daml.ledger.api.v2.CommandR\bcommands\x12R\n" +
	"\x16deduplication_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x00R\x15deduplicationDuration\x123\n" +
	"\x14deduplication_offset\x18\x06 \x01(\x03H\x00R\x13deduplicationOffset\x12I\n" +
	"\x13min_ledger_time_abs\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10minLedgerTimeAbs\x12H\n" +
	"\x13min_ledger_time_rel\x18\b \x01(\v2\x19.google.protobuf.DurationR\x10minLedgerTimeRel\x12\x15\n" +
	"\x06act_as\x18\t \x03(\tR\x05actAs\x12\x17\n" +
	"\aread_as\x18\n" +
	" \x03(\tR\x06readAs\x12#\n" +
	"\rsubmission_id\x18\v \x01(\tR\fsubmissionId\x12Z\n" +
	"\x13disclosed_contracts\x18\f \x03(\v2).com.daml.ledger.api.v2.DisclosedContractR\x12disclosedContracts\x12'\n" +
	"\x0fsynchronizer_id\x18\r \x01(\tR\x0esynchronizerId\x12E\n" +
	"\x1fpackage_id_selection_preference\x18\x0e \x03(\tR\x1cpackageIdSelectionPreference\x12a\n" +
	"\x16prefetch_contract_keys\x18\x0f \x03(\v2+.com.daml.ledger.api.v2.PrefetchContractKeyR\x14prefetchContractKeys\x12+\n" +
	"\x0ftaps_max_passes\x18\x10 \x01(\rH\x01R\rtapsMaxPasses\x88\x01\x01B\x16\n" +
	"\x14deduplication_periodB\x12\n" +
	"\x10_taps_max_passes\"\x9c\x01\n" +
	"\x13PrefetchContractKey\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12@\n" +
	"\fcontract_key\x18\x02 \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\vcontractKeyB\xfa\x01\n" +
	"\x1acom.com.daml.ledger.api.v2B\rCommandsProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_commands_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_commands_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_commands_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_commands_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_commands_proto_rawDesc), len(file_com_daml_ledger_api_v2_commands_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_commands_proto_rawDescData
}

var file_com_daml_ledger_api_v2_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_com_daml_ledger_api_v2_commands_proto_goTypes = []any{
	(*Command)(nil),                  // 0: com.daml.ledger.api.v2.Command
	(*CreateCommand)(nil),            // 1: com.daml.ledger.api.v2.CreateCommand
	(*ExerciseCommand)(nil),          // 2: com.daml.ledger.api.v2.ExerciseCommand
	(*ExerciseByKeyCommand)(nil),     // 3: com.daml.ledger.api.v2.ExerciseByKeyCommand
	(*CreateAndExerciseCommand)(nil), // 4: com.daml.ledger.api.v2.CreateAndExerciseCommand
	(*DisclosedContract)(nil),        // 5: com.daml.ledger.api.v2.DisclosedContract
	(*Commands)(nil),                 // 6: com.daml.ledger.api.v2.Commands
	(*PrefetchContractKey)(nil),      // 7: com.daml.ledger.api.v2.PrefetchContractKey
	(*Identifier)(nil),               // 8: com.daml.ledger.api.v2.Identifier
	(*Record)(nil),                   // 9: com.daml.ledger.api.v2.Record
	(*Value)(nil),                    // 10: com.daml.ledger.api.v2.Value
	(*durationpb.Duration)(nil),      // 11: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_com_daml_ledger_api_v2_commands_proto_depIdxs = []int32{
	1,  // 0: com.daml.ledger.api.v2.Command.create:type_name -> com.daml.ledger.api.v2.CreateCommand
	2,  // 1: com.daml.ledger.api.v2.Command.exercise:type_name -> com.daml.ledger.api.v2.ExerciseCommand
	3,  // 2: com.daml.ledger.api.v2.Command.exercise_by_key:type_name -> com.daml.ledger.api.v2.ExerciseByKeyCommand
	4,  // 3: com.daml.ledger.api.v2.Command.create_and_exercise:type_name -> com.daml.ledger.api.v2.CreateAndExerciseCommand
	8,  // 4: com.daml.ledger.api.v2.CreateCommand.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	9,  // 5: com.daml.ledger.api.v2.CreateCommand.create_arguments:type_name -> com.daml.ledger.api.v2.Record
	8,  // 6: com.daml.ledger.api.v2.ExerciseCommand.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	10, // 7: com.daml.ledger.api.v2.ExerciseCommand.choice_argument:type_name -> com.daml.ledger.api.v2.Value
	8,  // 8: com.daml.ledger.api.v2.ExerciseByKeyCommand.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	10, // 9: com.daml.ledger.api.v2.ExerciseByKeyCommand.contract_key:type_name -> com.daml.ledger.api.v2.Value
	10, // 10: com.daml.ledger.api.v2.ExerciseByKeyCommand.choice_argument:type_name -> com.daml.ledger.api.v2.Value
	8,  // 11: com.daml.ledger.api.v2.CreateAndExerciseCommand.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	9,  // 12: com.daml.ledger.api.v2.CreateAndExerciseCommand.create_arguments:type_name -> com.daml.ledger.api.v2.Record
	10, // 13: com.daml.ledger.api.v2.CreateAndExerciseCommand.choice_argument:type_name -> com.daml.ledger.api.v2.Value
	8,  // 14: com.daml.ledger.api.v2.DisclosedContract.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	0,  // 15: com.daml.ledger.api.v2.Commands.commands:type_name -> com.daml.ledger.api.v2.Command
	11, // 16: com.daml.ledger.api.v2.Commands.deduplication_duration:type_name -> google.protobuf.Duration
	12, // 17: com.daml.ledger.api.v2.Commands.min_ledger_time_abs:type_name -> google.protobuf.Timestamp
	11, // 18: com.daml.ledger.api.v2.Commands.min_ledger_time_rel:type_name -> google.protobuf.Duration
	5,  // 19: com.daml.ledger.api.v2.Commands.disclosed_contracts:type_name -> com.daml.ledger.api.v2.DisclosedContract
	7,  // 20: com.daml.ledger.api.v2.Commands.prefetch_contract_keys:type_name -> com.daml.ledger.api.v2.PrefetchContractKey
	8,  // 21: com.daml.ledger.api.v2.PrefetchContractKey.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	10, // 22: com.daml.ledger.api.v2.PrefetchContractKey.contract_key:type_name -> com.daml.ledger.api.v2.Value
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_commands_proto_init() }
func file_com_daml_ledger_api_v2_commands_proto_init() {
	if File_com_daml_ledger_api_v2_commands_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_value_proto_init()
	file_com_daml_ledger_api_v2_commands_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Create)(nil),
		(*Command_Exercise)(nil),
		(*Command_ExerciseByKey)(nil),
		(*Command_CreateAndExercise)(nil),
	}
	file_com_daml_ledger_api_v2_commands_proto_msgTypes[6].OneofWrappers = []any{
		(*Commands_DeduplicationDuration)(nil),
		(*Commands_DeduplicationOffset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_commands_proto_rawDesc), len(file_com_daml_ledger_api_v2_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_commands_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_commands_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_commands_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_commands_proto = out.File
	file_com_daml_ledger_api_v2_commands_proto_goTypes = nil
	file_com_daml_ledger_api_v2_commands_proto_depIdxs = nil
}
