// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/contract_service.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the contract.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// The list of querying parties
	// The stakeholders of the referenced contract must have an intersection with any of these parties
	// to return the result.
	// If no querying_parties specified, all possible contracts could be returned.
	//
	// Optional: can be empty
	QueryingParties []string `protobuf:"bytes,2,rep,name=querying_parties,json=queryingParties,proto3" json:"querying_parties,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_com_daml_ledger_api_v2_contract_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_contract_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_contract_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *GetContractRequest) GetQueryingParties() []string {
	if x != nil {
		return x.QueryingParties
	}
	return nil
}

type GetContractResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The representative_package_id will be always set to the contract package ID, therefore this endpoint should
	// not be used to lookup contract which entered the participant via party replication or repair service.
	// The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
	// The following fields of the created event cannot be populated, so those should not be used / parsed:
	//
	// - offset
	// - node_id
	// - created_event_blob
	// - interface_views
	// - acs_delta
	//
	// Required
	CreatedEvent  *CreatedEvent `protobuf:"bytes,1,opt,name=created_event,json=createdEvent,proto3" json:"created_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	mi := &file_com_daml_ledger_api_v2_contract_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_contract_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_contract_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetContractResponse) GetCreatedEvent() *CreatedEvent {
	if x != nil {
		return x.CreatedEvent
	}
	return nil
}

var File_com_daml_ledger_api_v2_contract_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_contract_service_proto_rawDesc = "" +
	"\n" +
	"-com/daml/ledger/api/v2/contract_service.proto\x12\x16com.daml.ledger.api.v2\x1a\"com/daml/ledger/api/v2/event.proto\"`\n" +
	"\x12GetContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12)\n" +
	"\x10querying_parties\x18\x02 \x03(\tR\x0fqueryingParties\"`\n" +
	"\x13GetContractResponse\x12I\n" +
	"\rcreated_event\x18\x01 \x01(\v2$.com.daml.ledger.api.v2.CreatedEventR\fcreatedEvent2y\n" +
	"\x0fContractService\x12f\n" +
	"\vGetContract\x12*.com.daml.ledger.api.v2.GetContractRequest\x1a+.com.daml.ledger.api.v2.GetContractResponseB\x81\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x14ContractServiceProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_contract_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_contract_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_contract_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_contract_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_contract_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_contract_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_contract_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_contract_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_contract_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_daml_ledger_api_v2_contract_service_proto_goTypes = []any{
	(*GetContractRequest)(nil),  // 0: com.daml.ledger.api.v2.GetContractRequest
	(*GetContractResponse)(nil), // 1: com.daml.ledger.api.v2.GetContractResponse
	(*CreatedEvent)(nil),        // 2: com.daml.ledger.api.v2.CreatedEvent
}
var file_com_daml_ledger_api_v2_contract_service_proto_depIdxs = []int32{
	2, // 0: com.daml.ledger.api.v2.GetContractResponse.created_event:type_name -> com.daml.ledger.api.v2.CreatedEvent
	0, // 1: com.daml.ledger.api.v2.ContractService.GetContract:input_type -> com.daml.ledger.api.v2.GetContractRequest
	1, // 2: com.daml.ledger.api.v2.ContractService.GetContract:output_type -> com.daml.ledger.api.v2.GetContractResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_contract_service_proto_init() }
func file_com_daml_ledger_api_v2_contract_service_proto_init() {
	if File_com_daml_ledger_api_v2_contract_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_contract_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_contract_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_contract_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_contract_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_contract_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_contract_service_proto = out.File
	file_com_daml_ledger_api_v2_contract_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_contract_service_proto_depIdxs = nil
}
