// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/crypto.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SigningKeySpec int32

const (
	SigningKeySpec_SIGNING_KEY_SPEC_UNSPECIFIED SigningKeySpec = 0
	// Elliptic Curve Key from Curve25519
	// as defined in http://ed25519.cr.yp.to/
	SigningKeySpec_SIGNING_KEY_SPEC_EC_CURVE25519 SigningKeySpec = 1
	// Elliptic Curve Key from the NIST P-256 curve (aka secp256r1)
	// as defined in https://doi.org/10.6028/NIST.FIPS.186-4
	SigningKeySpec_SIGNING_KEY_SPEC_EC_P256 SigningKeySpec = 2
	// Elliptic Curve Key from the NIST P-384 curve (aka secp384r1)
	// as defined in https://doi.org/10.6028/NIST.FIPS.186-4
	SigningKeySpec_SIGNING_KEY_SPEC_EC_P384 SigningKeySpec = 3
	// Elliptic Curve Key from SECG P256k1 curve (aka secp256k1)
	// commonly used in bitcoin and ethereum
	// as defined in https://www.secg.org/sec2-v2.pdf
	SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1 SigningKeySpec = 4
)

// Enum value maps for SigningKeySpec.
var (
	SigningKeySpec_name = map[int32]string{
		0: "SIGNING_KEY_SPEC_UNSPECIFIED",
		1: "SIGNING_KEY_SPEC_EC_CURVE25519",
		2: "SIGNING_KEY_SPEC_EC_P256",
		3: "SIGNING_KEY_SPEC_EC_P384",
		4: "SIGNING_KEY_SPEC_EC_SECP256K1",
	}
	SigningKeySpec_value = map[string]int32{
		"SIGNING_KEY_SPEC_UNSPECIFIED":   0,
		"SIGNING_KEY_SPEC_EC_CURVE25519": 1,
		"SIGNING_KEY_SPEC_EC_P256":       2,
		"SIGNING_KEY_SPEC_EC_P384":       3,
		"SIGNING_KEY_SPEC_EC_SECP256K1":  4,
	}
)

func (x SigningKeySpec) Enum() *SigningKeySpec {
	p := new(SigningKeySpec)
	*p = x
	return p
}

func (x SigningKeySpec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SigningKeySpec) Descriptor() protoreflect.EnumDescriptor {
	return file_com_daml_ledger_api_v2_crypto_proto_enumTypes[0].Descriptor()
}

func (SigningKeySpec) Type() protoreflect.EnumType {
	return &file_com_daml_ledger_api_v2_crypto_proto_enumTypes[0]
}

func (x SigningKeySpec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SigningKeySpec.Descriptor instead.
func (SigningKeySpec) EnumDescriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP(), []int{0}
}

// Serialization format for crypto keys and signatures
type CryptoKeyFormat int32

const (
	CryptoKeyFormat_CRYPTO_KEY_FORMAT_UNSPECIFIED CryptoKeyFormat = 0
	// ASN.1 + DER encoding
	// Legacy format no longer used, except for migrations
	CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER CryptoKeyFormat = 1
	// Raw encoding of a key
	CryptoKeyFormat_CRYPTO_KEY_FORMAT_RAW CryptoKeyFormat = 2
	// ASN.1 + DER-encoding of X.509 SubjectPublicKeyInfo structure: https://datatracker.ietf.org/doc/html/rfc5280#section-4.1
	CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO CryptoKeyFormat = 3
)

// Enum value maps for CryptoKeyFormat.
var (
	CryptoKeyFormat_name = map[int32]string{
		0: "CRYPTO_KEY_FORMAT_UNSPECIFIED",
		1: "CRYPTO_KEY_FORMAT_DER",
		2: "CRYPTO_KEY_FORMAT_RAW",
		3: "CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO",
	}
	CryptoKeyFormat_value = map[string]int32{
		"CRYPTO_KEY_FORMAT_UNSPECIFIED":                      0,
		"CRYPTO_KEY_FORMAT_DER":                              1,
		"CRYPTO_KEY_FORMAT_RAW":                              2,
		"CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO": 3,
	}
)

func (x CryptoKeyFormat) Enum() *CryptoKeyFormat {
	p := new(CryptoKeyFormat)
	*p = x
	return p
}

func (x CryptoKeyFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CryptoKeyFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_com_daml_ledger_api_v2_crypto_proto_enumTypes[1].Descriptor()
}

func (CryptoKeyFormat) Type() protoreflect.EnumType {
	return &file_com_daml_ledger_api_v2_crypto_proto_enumTypes[1]
}

func (x CryptoKeyFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CryptoKeyFormat.Descriptor instead.
func (CryptoKeyFormat) EnumDescriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP(), []int{1}
}

type SigningAlgorithmSpec int32

const (
	SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED SigningAlgorithmSpec = 0
	// EdDSA Signature based on Curve25519 with SHA-512
	// http://ed25519.cr.yp.to/
	SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_ED25519 SigningAlgorithmSpec = 1
	// Elliptic Curve Digital Signature Algorithm with SHA256
	SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256 SigningAlgorithmSpec = 2
	// Elliptic Curve Digital Signature Algorithm with SHA384
	SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384 SigningAlgorithmSpec = 3
)

// Enum value maps for SigningAlgorithmSpec.
var (
	SigningAlgorithmSpec_name = map[int32]string{
		0: "SIGNING_ALGORITHM_SPEC_UNSPECIFIED",
		1: "SIGNING_ALGORITHM_SPEC_ED25519",
		2: "SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256",
		3: "SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384",
	}
	SigningAlgorithmSpec_value = map[string]int32{
		"SIGNING_ALGORITHM_SPEC_UNSPECIFIED":    0,
		"SIGNING_ALGORITHM_SPEC_ED25519":        1,
		"SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256": 2,
		"SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384": 3,
	}
)

func (x SigningAlgorithmSpec) Enum() *SigningAlgorithmSpec {
	p := new(SigningAlgorithmSpec)
	*p = x
	return p
}

func (x SigningAlgorithmSpec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SigningAlgorithmSpec) Descriptor() protoreflect.EnumDescriptor {
	return file_com_daml_ledger_api_v2_crypto_proto_enumTypes[2].Descriptor()
}

func (SigningAlgorithmSpec) Type() protoreflect.EnumType {
	return &file_com_daml_ledger_api_v2_crypto_proto_enumTypes[2]
}

func (x SigningAlgorithmSpec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SigningAlgorithmSpec.Descriptor instead.
func (SigningAlgorithmSpec) EnumDescriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP(), []int{2}
}

type SignatureFormat int32

const (
	SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED SignatureFormat = 0
	// Signature scheme specific signature format
	// Legacy format no longer used, except for migrations
	SignatureFormat_SIGNATURE_FORMAT_RAW SignatureFormat = 1
	// ASN.1 + DER-encoding of the `r` and `s` integers, as defined in https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3
	// Used for ECDSA signatures
	SignatureFormat_SIGNATURE_FORMAT_DER SignatureFormat = 2
	// Concatenation of the integers `r || s` in little-endian form, as defined in https://datatracker.ietf.org/doc/html/rfc8032#section-3.3
	// Note that this is different from the format defined in IEEE P1363, which uses concatenation in big-endian form.
	// Used for EdDSA signatures
	SignatureFormat_SIGNATURE_FORMAT_CONCAT SignatureFormat = 3
	// Symbolic crypto, must only be used for testing
	SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC SignatureFormat = 10000
)

// Enum value maps for SignatureFormat.
var (
	SignatureFormat_name = map[int32]string{
		0:     "SIGNATURE_FORMAT_UNSPECIFIED",
		1:     "SIGNATURE_FORMAT_RAW",
		2:     "SIGNATURE_FORMAT_DER",
		3:     "SIGNATURE_FORMAT_CONCAT",
		10000: "SIGNATURE_FORMAT_SYMBOLIC",
	}
	SignatureFormat_value = map[string]int32{
		"SIGNATURE_FORMAT_UNSPECIFIED": 0,
		"SIGNATURE_FORMAT_RAW":         1,
		"SIGNATURE_FORMAT_DER":         2,
		"SIGNATURE_FORMAT_CONCAT":      3,
		"SIGNATURE_FORMAT_SYMBOLIC":    10000,
	}
)

func (x SignatureFormat) Enum() *SignatureFormat {
	p := new(SignatureFormat)
	*p = x
	return p
}

func (x SignatureFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_com_daml_ledger_api_v2_crypto_proto_enumTypes[3].Descriptor()
}

func (SignatureFormat) Type() protoreflect.EnumType {
	return &file_com_daml_ledger_api_v2_crypto_proto_enumTypes[3]
}

func (x SignatureFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureFormat.Descriptor instead.
func (SignatureFormat) EnumDescriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP(), []int{3}
}

type SigningPublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialization format of the public key
	//
	// Required
	Format CryptoKeyFormat `protobuf:"varint,1,opt,name=format,proto3,enum=com.daml.ledger.api.v2.CryptoKeyFormat" json:"format,omitempty"`
	// Serialized public key in the format specified above
	//
	// Required: must be non-empty
	KeyData []byte `protobuf:"bytes,2,opt,name=key_data,json=keyData,proto3" json:"key_data,omitempty"`
	// The key specification
	//
	// Required
	KeySpec       SigningKeySpec `protobuf:"varint,3,opt,name=key_spec,json=keySpec,proto3,enum=com.daml.ledger.api.v2.SigningKeySpec" json:"key_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningPublicKey) Reset() {
	*x = SigningPublicKey{}
	mi := &file_com_daml_ledger_api_v2_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningPublicKey) ProtoMessage() {}

func (x *SigningPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningPublicKey.ProtoReflect.Descriptor instead.
func (*SigningPublicKey) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *SigningPublicKey) GetFormat() CryptoKeyFormat {
	if x != nil {
		return x.Format
	}
	return CryptoKeyFormat_CRYPTO_KEY_FORMAT_UNSPECIFIED
}

func (x *SigningPublicKey) GetKeyData() []byte {
	if x != nil {
		return x.KeyData
	}
	return nil
}

func (x *SigningPublicKey) GetKeySpec() SigningKeySpec {
	if x != nil {
		return x.KeySpec
	}
	return SigningKeySpec_SIGNING_KEY_SPEC_UNSPECIFIED
}

type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	Format SignatureFormat `protobuf:"varint,1,opt,name=format,proto3,enum=com.daml.ledger.api.v2.SignatureFormat" json:"format,omitempty"`
	// Required: must be non-empty
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The fingerprint/id of the keypair used to create this signature and needed to verify.
	//
	// Required
	SignedBy string `protobuf:"bytes,3,opt,name=signed_by,json=signedBy,proto3" json:"signed_by,omitempty"`
	// The signing algorithm specification used to produce this signature
	//
	// Required
	SigningAlgorithmSpec SigningAlgorithmSpec `protobuf:"varint,4,opt,name=signing_algorithm_spec,json=signingAlgorithmSpec,proto3,enum=com.daml.ledger.api.v2.SigningAlgorithmSpec" json:"signing_algorithm_spec,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_com_daml_ledger_api_v2_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *Signature) GetFormat() SignatureFormat {
	if x != nil {
		return x.Format
	}
	return SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Signature) GetSignedBy() string {
	if x != nil {
		return x.SignedBy
	}
	return ""
}

func (x *Signature) GetSigningAlgorithmSpec() SigningAlgorithmSpec {
	if x != nil {
		return x.SigningAlgorithmSpec
	}
	return SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED
}

var File_com_daml_ledger_api_v2_crypto_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_crypto_proto_rawDesc = "" +
	"\n" +
	"#com/daml/ledger/api/v2/crypto.proto\x12\x16com.daml.ledger.api.v2\"\xb1\x01\n" +
	"\x10SigningPublicKey\x12?\n" +
	"\x06format\x18\x01 \x01(\x0e2'.com.daml.ledger.api.v2.CryptoKeyFormatR\x06format\x12\x19\n" +
	"\bkey_data\x18\x02 \x01(\fR\akeyData\x12A\n" +
	"\bkey_spec\x18\x03 \x01(\x0e2&.com.daml.ledger.api.v2.SigningKeySpecR\akeySpec\"\xeb\x01\n" +
	"\tSignature\x12?\n" +
	"\x06format\x18\x01 \x01(\x0e2'.com.daml.ledger.api.v2.SignatureFormatR\x06format\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigned_by\x18\x03 \x01(\tR\bsignedBy\x12b\n" +
	"\x16signing_algorithm_spec\x18\x04 \x01(\x0e2,.com.daml.ledger.api.v2.SigningAlgorithmSpecR\x14signingAlgorithmSpec*\xb5\x01\n" +
	"\x0eSigningKeySpec\x12 \n" +
	"\x1cSIGNING_KEY_SPEC_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSIGNING_KEY_SPEC_EC_CURVE25519\x10\x01\x12\x1c\n" +
	"\x18SIGNING_KEY_SPEC_EC_P256\x10\x02\x12\x1c\n" +
	"\x18SIGNING_KEY_SPEC_EC_P384\x10\x03\x12!\n" +
	"\x1dSIGNING_KEY_SPEC_EC_SECP256K1\x10\x04*\xaa\x01\n" +
	"\x0fCryptoKeyFormat\x12!\n" +
	"\x1dCRYPTO_KEY_FORMAT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CRYPTO_KEY_FORMAT_DER\x10\x01\x12\x19\n" +
	"\x15CRYPTO_KEY_FORMAT_RAW\x10\x02\x126\n" +
	"2CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO\x10\x03\"\x06\b\x90N\x10\x90N*\xb8\x01\n" +
	"\x14SigningAlgorithmSpec\x12&\n" +
	"\"SIGNING_ALGORITHM_SPEC_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSIGNING_ALGORITHM_SPEC_ED25519\x10\x01\x12)\n" +
	"%SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256\x10\x02\x12)\n" +
	"%SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384\x10\x03*\xa4\x01\n" +
	"\x0fSignatureFormat\x12 \n" +
	"\x1cSIGNATURE_FORMAT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SIGNATURE_FORMAT_RAW\x10\x01\x12\x18\n" +
	"\x14SIGNATURE_FORMAT_DER\x10\x02\x12\x1b\n" +
	"\x17SIGNATURE_FORMAT_CONCAT\x10\x03\x12\x1e\n" +
	"\x19SIGNATURE_FORMAT_SYMBOLIC\x10\x90NB\xf8\x01\n" +
	"\x1acom.com.daml.ledger.api.v2B\vCryptoProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_crypto_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_crypto_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_crypto_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_crypto_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_crypto_proto_rawDesc), len(file_com_daml_ledger_api_v2_crypto_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_crypto_proto_rawDescData
}

var file_com_daml_ledger_api_v2_crypto_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_com_daml_ledger_api_v2_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_daml_ledger_api_v2_crypto_proto_goTypes = []any{
	(SigningKeySpec)(0),       // 0: com.daml.ledger.api.v2.SigningKeySpec
	(CryptoKeyFormat)(0),      // 1: com.daml.ledger.api.v2.CryptoKeyFormat
	(SigningAlgorithmSpec)(0), // 2: com.daml.ledger.api.v2.SigningAlgorithmSpec
	(SignatureFormat)(0),      // 3: com.daml.ledger.api.v2.SignatureFormat
	(*SigningPublicKey)(nil),  // 4: com.daml.ledger.api.v2.SigningPublicKey
	(*Signature)(nil),         // 5: com.daml.ledger.api.v2.Signature
}
var file_com_daml_ledger_api_v2_crypto_proto_depIdxs = []int32{
	1, // 0: com.daml.ledger.api.v2.SigningPublicKey.format:type_name -> com.daml.ledger.api.v2.CryptoKeyFormat
	0, // 1: com.daml.ledger.api.v2.SigningPublicKey.key_spec:type_name -> com.daml.ledger.api.v2.SigningKeySpec
	3, // 2: com.daml.ledger.api.v2.Signature.format:type_name -> com.daml.ledger.api.v2.SignatureFormat
	2, // 3: com.daml.ledger.api.v2.Signature.signing_algorithm_spec:type_name -> com.daml.ledger.api.v2.SigningAlgorithmSpec
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_crypto_proto_init() }
func file_com_daml_ledger_api_v2_crypto_proto_init() {
	if File_com_daml_ledger_api_v2_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_crypto_proto_rawDesc), len(file_com_daml_ledger_api_v2_crypto_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_crypto_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_crypto_proto_depIdxs,
		EnumInfos:         file_com_daml_ledger_api_v2_crypto_proto_enumTypes,
		MessageInfos:      file_com_daml_ledger_api_v2_crypto_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_crypto_proto = out.File
	file_com_daml_ledger_api_v2_crypto_proto_goTypes = nil
	file_com_daml_ledger_api_v2_crypto_proto_depIdxs = nil
}
