// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: com/daml/ledger/api/v2/event_query_service.proto

package apiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventQueryService_GetEventsByContractId_FullMethodName = "/com.daml.ledger.api.v2.EventQueryService/GetEventsByContractId"
)

// EventQueryServiceClient is the client API for EventQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query events by contract id.
//
// Note that querying by contract key is not (yet) supported, as contract keys
// are not supported (yet) in multi-synchronizer scenarios.
type EventQueryServiceClient interface {
	// Get the create and the consuming exercise event for the contract with the provided ID.
	// No events will be returned for contracts that have been pruned because they
	// have already been archived before the latest pruning offset.
	// If the contract cannot be found for the request, or all the contract-events are filtered, a CONTRACT_EVENTS_NOT_FOUND error will be raised.
	GetEventsByContractId(ctx context.Context, in *GetEventsByContractIdRequest, opts ...grpc.CallOption) (*GetEventsByContractIdResponse, error)
}

type eventQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventQueryServiceClient(cc grpc.ClientConnInterface) EventQueryServiceClient {
	return &eventQueryServiceClient{cc}
}

func (c *eventQueryServiceClient) GetEventsByContractId(ctx context.Context, in *GetEventsByContractIdRequest, opts ...grpc.CallOption) (*GetEventsByContractIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByContractIdResponse)
	err := c.cc.Invoke(ctx, EventQueryService_GetEventsByContractId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventQueryServiceServer is the server API for EventQueryService service.
// All implementations must embed UnimplementedEventQueryServiceServer
// for forward compatibility.
//
// Query events by contract id.
//
// Note that querying by contract key is not (yet) supported, as contract keys
// are not supported (yet) in multi-synchronizer scenarios.
type EventQueryServiceServer interface {
	// Get the create and the consuming exercise event for the contract with the provided ID.
	// No events will be returned for contracts that have been pruned because they
	// have already been archived before the latest pruning offset.
	// If the contract cannot be found for the request, or all the contract-events are filtered, a CONTRACT_EVENTS_NOT_FOUND error will be raised.
	GetEventsByContractId(context.Context, *GetEventsByContractIdRequest) (*GetEventsByContractIdResponse, error)
	mustEmbedUnimplementedEventQueryServiceServer()
}

// UnimplementedEventQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventQueryServiceServer struct{}

func (UnimplementedEventQueryServiceServer) GetEventsByContractId(context.Context, *GetEventsByContractIdRequest) (*GetEventsByContractIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsByContractId not implemented")
}
func (UnimplementedEventQueryServiceServer) mustEmbedUnimplementedEventQueryServiceServer() {}
func (UnimplementedEventQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeEventQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventQueryServiceServer will
// result in compilation errors.
type UnsafeEventQueryServiceServer interface {
	mustEmbedUnimplementedEventQueryServiceServer()
}

func RegisterEventQueryServiceServer(s grpc.ServiceRegistrar, srv EventQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventQueryService_ServiceDesc, srv)
}

func _EventQueryService_GetEventsByContractId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByContractIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventQueryServiceServer).GetEventsByContractId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventQueryService_GetEventsByContractId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventQueryServiceServer).GetEventsByContractId(ctx, req.(*GetEventsByContractIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventQueryService_ServiceDesc is the grpc.ServiceDesc for EventQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.daml.ledger.api.v2.EventQueryService",
	HandlerType: (*EventQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventsByContractId",
			Handler:    _EventQueryService_GetEventsByContractId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/daml/ledger/api/v2/event_query_service.proto",
}
