// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/offset_checkpoint.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OffsetCheckpoints may be used to:
//
// - detect time out of commands.
// - provide an offset which can be used to restart consumption.
type OffsetCheckpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The participant's offset, the details of the offset field are described in “community/ledger-api/README.md“.
	// Must be a valid absolute offset (positive integer).
	//
	// Required
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// The times associated with each synchronizer at this offset.
	//
	// Optional: can be empty
	SynchronizerTimes []*SynchronizerTime `protobuf:"bytes,2,rep,name=synchronizer_times,json=synchronizerTimes,proto3" json:"synchronizer_times,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OffsetCheckpoint) Reset() {
	*x = OffsetCheckpoint{}
	mi := &file_com_daml_ledger_api_v2_offset_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffsetCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffsetCheckpoint) ProtoMessage() {}

func (x *OffsetCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_offset_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffsetCheckpoint.ProtoReflect.Descriptor instead.
func (*OffsetCheckpoint) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *OffsetCheckpoint) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *OffsetCheckpoint) GetSynchronizerTimes() []*SynchronizerTime {
	if x != nil {
		return x.SynchronizerTimes
	}
	return nil
}

type SynchronizerTime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the synchronizer.
	//
	// Required
	SynchronizerId string `protobuf:"bytes,1,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// All commands with a maximum record time below this value MUST be considered lost if their completion has not arrived before this checkpoint.
	//
	// Required
	RecordTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynchronizerTime) Reset() {
	*x = SynchronizerTime{}
	mi := &file_com_daml_ledger_api_v2_offset_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizerTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizerTime) ProtoMessage() {}

func (x *SynchronizerTime) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_offset_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizerTime.ProtoReflect.Descriptor instead.
func (*SynchronizerTime) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *SynchronizerTime) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *SynchronizerTime) GetRecordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordTime
	}
	return nil
}

var File_com_daml_ledger_api_v2_offset_checkpoint_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDesc = "" +
	"\n" +
	".com/daml/ledger/api/v2/offset_checkpoint.proto\x12\x16com.daml.ledger.api.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x10OffsetCheckpoint\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12W\n" +
	"\x12synchronizer_times\x18\x02 \x03(\v2(.com.daml.ledger.api.v2.SynchronizerTimeR\x11synchronizerTimes\"x\n" +
	"\x10SynchronizerTime\x12'\n" +
	"\x0fsynchronizer_id\x18\x01 \x01(\tR\x0esynchronizerId\x12;\n" +
	"\vrecord_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordTimeB\x82\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x15OffsetCheckpointProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDesc), len(file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDescData
}

var file_com_daml_ledger_api_v2_offset_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_daml_ledger_api_v2_offset_checkpoint_proto_goTypes = []any{
	(*OffsetCheckpoint)(nil),      // 0: com.daml.ledger.api.v2.OffsetCheckpoint
	(*SynchronizerTime)(nil),      // 1: com.daml.ledger.api.v2.SynchronizerTime
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_com_daml_ledger_api_v2_offset_checkpoint_proto_depIdxs = []int32{
	1, // 0: com.daml.ledger.api.v2.OffsetCheckpoint.synchronizer_times:type_name -> com.daml.ledger.api.v2.SynchronizerTime
	2, // 1: com.daml.ledger.api.v2.SynchronizerTime.record_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_offset_checkpoint_proto_init() }
func file_com_daml_ledger_api_v2_offset_checkpoint_proto_init() {
	if File_com_daml_ledger_api_v2_offset_checkpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDesc), len(file_com_daml_ledger_api_v2_offset_checkpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_offset_checkpoint_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_offset_checkpoint_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_offset_checkpoint_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_offset_checkpoint_proto = out.File
	file_com_daml_ledger_api_v2_offset_checkpoint_proto_goTypes = nil
	file_com_daml_ledger_api_v2_offset_checkpoint_proto_depIdxs = nil
}
