// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/package_reference.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Required
	PackageName string `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// Required
	PackageVersion string `protobuf:"bytes,3,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PackageReference) Reset() {
	*x = PackageReference{}
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageReference) ProtoMessage() {}

func (x *PackageReference) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageReference.ProtoReflect.Descriptor instead.
func (*PackageReference) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_package_reference_proto_rawDescGZIP(), []int{0}
}

func (x *PackageReference) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageReference) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PackageReference) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

// A package that is vetting on a given participant and synchronizer,
// modelled after “VettedPackage“ in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_,
// enriched with the package name and version.
type VettedPackage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID of this package
	//
	// Required
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// The time from which this package is vetted. Empty if vetting time has no
	// lower bound.
	//
	// Optional
	ValidFromInclusive *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=valid_from_inclusive,json=validFromInclusive,proto3" json:"valid_from_inclusive,omitempty"`
	// The time until which this package is vetted. Empty if vetting time has no
	// upper bound.
	//
	// Optional
	ValidUntilExclusive *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_until_exclusive,json=validUntilExclusive,proto3" json:"valid_until_exclusive,omitempty"`
	// Name of this package.
	// Only available if the package has been uploaded to the current participant.
	//
	// Optional
	PackageName string `protobuf:"bytes,4,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// Version of this package.
	// Only available if the package has been uploaded to the current participant.
	//
	// Optional
	PackageVersion string `protobuf:"bytes,5,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VettedPackage) Reset() {
	*x = VettedPackage{}
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VettedPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VettedPackage) ProtoMessage() {}

func (x *VettedPackage) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VettedPackage.ProtoReflect.Descriptor instead.
func (*VettedPackage) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_package_reference_proto_rawDescGZIP(), []int{1}
}

func (x *VettedPackage) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *VettedPackage) GetValidFromInclusive() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFromInclusive
	}
	return nil
}

func (x *VettedPackage) GetValidUntilExclusive() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntilExclusive
	}
	return nil
}

func (x *VettedPackage) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *VettedPackage) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

// The list of packages vetted on a given participant and synchronizer, modelled
// after “VettedPackages“ in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_.
// The list only contains packages that matched a filter in the query that
// originated it.
type VettedPackages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted by package_name and package_version where known, and package_id as a
	// last resort.
	//
	// Required: must be non-empty
	Packages []*VettedPackage `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	// Participant on which these packages are vetted.
	//
	// Required
	ParticipantId string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Synchronizer on which these packages are vetted.
	//
	// Required
	SynchronizerId string `protobuf:"bytes,3,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// Serial of last “VettedPackages“ topology transaction of this participant
	// and on this synchronizer.
	//
	// Required
	TopologySerial uint32 `protobuf:"varint,4,opt,name=topology_serial,json=topologySerial,proto3" json:"topology_serial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VettedPackages) Reset() {
	*x = VettedPackages{}
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VettedPackages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VettedPackages) ProtoMessage() {}

func (x *VettedPackages) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VettedPackages.ProtoReflect.Descriptor instead.
func (*VettedPackages) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_package_reference_proto_rawDescGZIP(), []int{2}
}

func (x *VettedPackages) GetPackages() []*VettedPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *VettedPackages) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *VettedPackages) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *VettedPackages) GetTopologySerial() uint32 {
	if x != nil {
		return x.TopologySerial
	}
	return 0
}

// The serial of last “VettedPackages“ topology transaction on a given
// participant and synchronizer.
type PriorTopologySerial struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional
	//
	// Types that are valid to be assigned to Serial:
	//
	//	*PriorTopologySerial_Prior
	//	*PriorTopologySerial_NoPrior
	Serial        isPriorTopologySerial_Serial `protobuf_oneof:"serial"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorTopologySerial) Reset() {
	*x = PriorTopologySerial{}
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorTopologySerial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorTopologySerial) ProtoMessage() {}

func (x *PriorTopologySerial) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorTopologySerial.ProtoReflect.Descriptor instead.
func (*PriorTopologySerial) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_package_reference_proto_rawDescGZIP(), []int{3}
}

func (x *PriorTopologySerial) GetSerial() isPriorTopologySerial_Serial {
	if x != nil {
		return x.Serial
	}
	return nil
}

func (x *PriorTopologySerial) GetPrior() uint32 {
	if x != nil {
		if x, ok := x.Serial.(*PriorTopologySerial_Prior); ok {
			return x.Prior
		}
	}
	return 0
}

func (x *PriorTopologySerial) GetNoPrior() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Serial.(*PriorTopologySerial_NoPrior); ok {
			return x.NoPrior
		}
	}
	return nil
}

type isPriorTopologySerial_Serial interface {
	isPriorTopologySerial_Serial()
}

type PriorTopologySerial_Prior struct {
	// Previous transaction's serial.
	Prior uint32 `protobuf:"varint,1,opt,name=prior,proto3,oneof"`
}

type PriorTopologySerial_NoPrior struct {
	// No previous transaction exists.
	NoPrior *emptypb.Empty `protobuf:"bytes,2,opt,name=no_prior,json=noPrior,proto3,oneof"`
}

func (*PriorTopologySerial_Prior) isPriorTopologySerial_Serial() {}

func (*PriorTopologySerial_NoPrior) isPriorTopologySerial_Serial() {}

var File_com_daml_ledger_api_v2_package_reference_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_package_reference_proto_rawDesc = "" +
	"\n" +
	".com/daml/ledger/api/v2/package_reference.proto\x12\x16com.daml.ledger.api.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x10PackageReference\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\x03 \x01(\tR\x0epackageVersion\"\x98\x02\n" +
	"\rVettedPackage\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12L\n" +
	"\x14valid_from_inclusive\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x12validFromInclusive\x12N\n" +
	"\x15valid_until_exclusive\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13validUntilExclusive\x12!\n" +
	"\fpackage_name\x18\x04 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\x05 \x01(\tR\x0epackageVersion\"\xcc\x01\n" +
	"\x0eVettedPackages\x12A\n" +
	"\bpackages\x18\x01 \x03(\v2%.com.daml.ledger.api.v2.VettedPackageR\bpackages\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12'\n" +
	"\x0fsynchronizer_id\x18\x03 \x01(\tR\x0esynchronizerId\x12'\n" +
	"\x0ftopology_serial\x18\x04 \x01(\rR\x0etopologySerial\"l\n" +
	"\x13PriorTopologySerial\x12\x16\n" +
	"\x05prior\x18\x01 \x01(\rH\x00R\x05prior\x123\n" +
	"\bno_prior\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\anoPriorB\b\n" +
	"\x06serialB\x82\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x15PackageReferenceProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_package_reference_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_package_reference_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_package_reference_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_package_reference_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_package_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_package_reference_proto_rawDesc), len(file_com_daml_ledger_api_v2_package_reference_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_package_reference_proto_rawDescData
}

var file_com_daml_ledger_api_v2_package_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_com_daml_ledger_api_v2_package_reference_proto_goTypes = []any{
	(*PackageReference)(nil),      // 0: com.daml.ledger.api.v2.PackageReference
	(*VettedPackage)(nil),         // 1: com.daml.ledger.api.v2.VettedPackage
	(*VettedPackages)(nil),        // 2: com.daml.ledger.api.v2.VettedPackages
	(*PriorTopologySerial)(nil),   // 3: com.daml.ledger.api.v2.PriorTopologySerial
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_com_daml_ledger_api_v2_package_reference_proto_depIdxs = []int32{
	4, // 0: com.daml.ledger.api.v2.VettedPackage.valid_from_inclusive:type_name -> google.protobuf.Timestamp
	4, // 1: com.daml.ledger.api.v2.VettedPackage.valid_until_exclusive:type_name -> google.protobuf.Timestamp
	1, // 2: com.daml.ledger.api.v2.VettedPackages.packages:type_name -> com.daml.ledger.api.v2.VettedPackage
	5, // 3: com.daml.ledger.api.v2.PriorTopologySerial.no_prior:type_name -> google.protobuf.Empty
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_package_reference_proto_init() }
func file_com_daml_ledger_api_v2_package_reference_proto_init() {
	if File_com_daml_ledger_api_v2_package_reference_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_package_reference_proto_msgTypes[3].OneofWrappers = []any{
		(*PriorTopologySerial_Prior)(nil),
		(*PriorTopologySerial_NoPrior)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_package_reference_proto_rawDesc), len(file_com_daml_ledger_api_v2_package_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_package_reference_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_package_reference_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_package_reference_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_package_reference_proto = out.File
	file_com_daml_ledger_api_v2_package_reference_proto_goTypes = nil
	file_com_daml_ledger_api_v2_package_reference_proto_depIdxs = nil
}
