// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/reassignment_commands.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReassignmentCommands struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the on-ledger workflow that this command is a part of.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Optional
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Uniquely identifies the participant user that issued the command.
	// Must be a valid UserIdString (as described in “value.proto“).
	// Required unless authentication is used with a user token.
	// In that case, the token's user-id will be used for the request's user_id.
	//
	// Optional
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Uniquely identifies the command.
	// The triple (user_id, submitter, command_id) constitutes the change ID for the intended ledger change.
	// The change ID can be used for matching the intended ledger changes with all their completions.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	CommandId string `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Party on whose behalf the command should be executed.
	// If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request
	// to act on behalf of the given party.
	// Must be a valid PartyIdString (as described in “value.proto“).
	//
	// Required
	Submitter string `protobuf:"bytes,4,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// A unique identifier to distinguish completions for different submissions with the same change ID.
	// Typically a random UUID. Applications are expected to use a different UUID for each retry of a submission
	// with the same change ID.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// If omitted, the participant or the committer may set a value of their choice.
	//
	// Optional
	SubmissionId string `protobuf:"bytes,5,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	// Individual elements of this reassignment. Must be non-empty.
	//
	// Required: must be non-empty
	Commands      []*ReassignmentCommand `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignmentCommands) Reset() {
	*x = ReassignmentCommands{}
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignmentCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignmentCommands) ProtoMessage() {}

func (x *ReassignmentCommands) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignmentCommands.ProtoReflect.Descriptor instead.
func (*ReassignmentCommands) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescGZIP(), []int{0}
}

func (x *ReassignmentCommands) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ReassignmentCommands) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReassignmentCommands) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ReassignmentCommands) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *ReassignmentCommands) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ReassignmentCommands) GetCommands() []*ReassignmentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ReassignmentCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	//
	// Types that are valid to be assigned to Command:
	//
	//	*ReassignmentCommand_UnassignCommand
	//	*ReassignmentCommand_AssignCommand
	Command       isReassignmentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignmentCommand) Reset() {
	*x = ReassignmentCommand{}
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignmentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignmentCommand) ProtoMessage() {}

func (x *ReassignmentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignmentCommand.ProtoReflect.Descriptor instead.
func (*ReassignmentCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescGZIP(), []int{1}
}

func (x *ReassignmentCommand) GetCommand() isReassignmentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ReassignmentCommand) GetUnassignCommand() *UnassignCommand {
	if x != nil {
		if x, ok := x.Command.(*ReassignmentCommand_UnassignCommand); ok {
			return x.UnassignCommand
		}
	}
	return nil
}

func (x *ReassignmentCommand) GetAssignCommand() *AssignCommand {
	if x != nil {
		if x, ok := x.Command.(*ReassignmentCommand_AssignCommand); ok {
			return x.AssignCommand
		}
	}
	return nil
}

type isReassignmentCommand_Command interface {
	isReassignmentCommand_Command()
}

type ReassignmentCommand_UnassignCommand struct {
	UnassignCommand *UnassignCommand `protobuf:"bytes,1,opt,name=unassign_command,json=unassignCommand,proto3,oneof"`
}

type ReassignmentCommand_AssignCommand struct {
	AssignCommand *AssignCommand `protobuf:"bytes,2,opt,name=assign_command,json=assignCommand,proto3,oneof"`
}

func (*ReassignmentCommand_UnassignCommand) isReassignmentCommand_Command() {}

func (*ReassignmentCommand_AssignCommand) isReassignmentCommand_Command() {}

// Unassign a contract
type UnassignCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the contract the client wants to unassign.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// The ID of the source synchronizer
	// Must be a valid synchronizer id
	//
	// Required
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The ID of the target synchronizer
	// Must be a valid synchronizer id
	//
	// Required
	Target        string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignCommand) Reset() {
	*x = UnassignCommand{}
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignCommand) ProtoMessage() {}

func (x *UnassignCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignCommand.ProtoReflect.Descriptor instead.
func (*UnassignCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescGZIP(), []int{2}
}

func (x *UnassignCommand) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *UnassignCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UnassignCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// Assign a contract
type AssignCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID from the unassigned event to be completed by this assignment.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	ReassignmentId string `protobuf:"bytes,1,opt,name=reassignment_id,json=reassignmentId,proto3" json:"reassignment_id,omitempty"`
	// The ID of the source synchronizer
	// Must be a valid synchronizer id
	//
	// Required
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The ID of the target synchronizer
	// Must be a valid synchronizer id
	//
	// Required
	Target        string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCommand) Reset() {
	*x = AssignCommand{}
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCommand) ProtoMessage() {}

func (x *AssignCommand) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCommand.ProtoReflect.Descriptor instead.
func (*AssignCommand) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescGZIP(), []int{3}
}

func (x *AssignCommand) GetReassignmentId() string {
	if x != nil {
		return x.ReassignmentId
	}
	return ""
}

func (x *AssignCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AssignCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_com_daml_ledger_api_v2_reassignment_commands_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDesc = "" +
	"\n" +
	"2com/daml/ledger/api/v2/reassignment_commands.proto\x12\x16com.daml.ledger.api.v2\"\xfb\x01\n" +
	"\x14ReassignmentCommands\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x1c\n" +
	"\tsubmitter\x18\x04 \x01(\tR\tsubmitter\x12#\n" +
	"\rsubmission_id\x18\x05 \x01(\tR\fsubmissionId\x12G\n" +
	"\bcommands\x18\x06 \x03(\v2+.com.daml.ledger.api.v2.ReassignmentCommandR\bcommands\"\xc6\x01\n" +
	"\x13ReassignmentCommand\x12T\n" +
	"\x10unassign_command\x18\x01 \x01(\v2'.com.daml.ledger.api.v2.UnassignCommandH\x00R\x0funassignCommand\x12N\n" +
	"\x0eassign_command\x18\x02 \x01(\v2%.com.daml.ledger.api.v2.AssignCommandH\x00R\rassignCommandB\t\n" +
	"\acommand\"b\n" +
	"\x0fUnassignCommand\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"h\n" +
	"\rAssignCommand\x12'\n" +
	"\x0freassignment_id\x18\x01 \x01(\tR\x0ereassignmentId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06targetB\x86\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x19ReassignmentCommandsProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDesc), len(file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDescData
}

var file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_com_daml_ledger_api_v2_reassignment_commands_proto_goTypes = []any{
	(*ReassignmentCommands)(nil), // 0: com.daml.ledger.api.v2.ReassignmentCommands
	(*ReassignmentCommand)(nil),  // 1: com.daml.ledger.api.v2.ReassignmentCommand
	(*UnassignCommand)(nil),      // 2: com.daml.ledger.api.v2.UnassignCommand
	(*AssignCommand)(nil),        // 3: com.daml.ledger.api.v2.AssignCommand
}
var file_com_daml_ledger_api_v2_reassignment_commands_proto_depIdxs = []int32{
	1, // 0: com.daml.ledger.api.v2.ReassignmentCommands.commands:type_name -> com.daml.ledger.api.v2.ReassignmentCommand
	2, // 1: com.daml.ledger.api.v2.ReassignmentCommand.unassign_command:type_name -> com.daml.ledger.api.v2.UnassignCommand
	3, // 2: com.daml.ledger.api.v2.ReassignmentCommand.assign_command:type_name -> com.daml.ledger.api.v2.AssignCommand
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_reassignment_commands_proto_init() }
func file_com_daml_ledger_api_v2_reassignment_commands_proto_init() {
	if File_com_daml_ledger_api_v2_reassignment_commands_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes[1].OneofWrappers = []any{
		(*ReassignmentCommand_UnassignCommand)(nil),
		(*ReassignmentCommand_AssignCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDesc), len(file_com_daml_ledger_api_v2_reassignment_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_reassignment_commands_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_reassignment_commands_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_reassignment_commands_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_reassignment_commands_proto = out.File
	file_com_daml_ledger_api_v2_reassignment_commands_proto_goTypes = nil
	file_com_daml_ledger_api_v2_reassignment_commands_proto_depIdxs = nil
}
