// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/topology_transaction.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopologyTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned by the server. Useful for correlating logs.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The absolute offset. The details of this field are described in “community/ledger-api/README.md“.
	// It is a valid absolute offset (positive integer).
	//
	// Required
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// A valid synchronizer id.
	// Identifies the synchronizer that synchronized the topology transaction.
	//
	// Required
	SynchronizerId string `protobuf:"bytes,3,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// The time at which the changes in the topology transaction become effective. There is a small delay between a
	// topology transaction being sequenced and the changes it contains becoming effective. Topology transactions appear
	// in order relative to a synchronizer based on their effective time rather than their sequencing time.
	//
	// Required
	RecordTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	// A non-empty list of topology events.
	//
	// Required: must be non-empty
	Events []*TopologyEvent `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	// Ledger API trace context
	//
	// The trace context transported in this message corresponds to the trace context supplied
	// by the client application in a HTTP2 header of the original command submission.
	// We typically use a header to transfer this type of information. Here we use message
	// body, because it is used in gRPC streams which do not support per message headers.
	// This field will be populated with the trace context contained in the original submission.
	// If that was not provided, a unique ledger-api-server generated trace context will be used
	// instead.
	//
	// Optional
	TraceContext  *TraceContext `protobuf:"bytes,6,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyTransaction) Reset() {
	*x = TopologyTransaction{}
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyTransaction) ProtoMessage() {}

func (x *TopologyTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyTransaction.ProtoReflect.Descriptor instead.
func (*TopologyTransaction) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TopologyTransaction) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *TopologyTransaction) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TopologyTransaction) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *TopologyTransaction) GetRecordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordTime
	}
	return nil
}

func (x *TopologyTransaction) GetEvents() []*TopologyEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *TopologyTransaction) GetTraceContext() *TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

type TopologyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	//
	// Types that are valid to be assigned to Event:
	//
	//	*TopologyEvent_ParticipantAuthorizationChanged
	//	*TopologyEvent_ParticipantAuthorizationRevoked
	//	*TopologyEvent_ParticipantAuthorizationAdded
	//	*TopologyEvent_ParticipantAuthorizationOnboarding
	Event         isTopologyEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyEvent) Reset() {
	*x = TopologyEvent{}
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyEvent) ProtoMessage() {}

func (x *TopologyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyEvent.ProtoReflect.Descriptor instead.
func (*TopologyEvent) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TopologyEvent) GetEvent() isTopologyEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TopologyEvent) GetParticipantAuthorizationChanged() *ParticipantAuthorizationChanged {
	if x != nil {
		if x, ok := x.Event.(*TopologyEvent_ParticipantAuthorizationChanged); ok {
			return x.ParticipantAuthorizationChanged
		}
	}
	return nil
}

func (x *TopologyEvent) GetParticipantAuthorizationRevoked() *ParticipantAuthorizationRevoked {
	if x != nil {
		if x, ok := x.Event.(*TopologyEvent_ParticipantAuthorizationRevoked); ok {
			return x.ParticipantAuthorizationRevoked
		}
	}
	return nil
}

func (x *TopologyEvent) GetParticipantAuthorizationAdded() *ParticipantAuthorizationAdded {
	if x != nil {
		if x, ok := x.Event.(*TopologyEvent_ParticipantAuthorizationAdded); ok {
			return x.ParticipantAuthorizationAdded
		}
	}
	return nil
}

func (x *TopologyEvent) GetParticipantAuthorizationOnboarding() *ParticipantAuthorizationOnboarding {
	if x != nil {
		if x, ok := x.Event.(*TopologyEvent_ParticipantAuthorizationOnboarding); ok {
			return x.ParticipantAuthorizationOnboarding
		}
	}
	return nil
}

type isTopologyEvent_Event interface {
	isTopologyEvent_Event()
}

type TopologyEvent_ParticipantAuthorizationChanged struct {
	ParticipantAuthorizationChanged *ParticipantAuthorizationChanged `protobuf:"bytes,1,opt,name=participant_authorization_changed,json=participantAuthorizationChanged,proto3,oneof"`
}

type TopologyEvent_ParticipantAuthorizationRevoked struct {
	ParticipantAuthorizationRevoked *ParticipantAuthorizationRevoked `protobuf:"bytes,2,opt,name=participant_authorization_revoked,json=participantAuthorizationRevoked,proto3,oneof"`
}

type TopologyEvent_ParticipantAuthorizationAdded struct {
	ParticipantAuthorizationAdded *ParticipantAuthorizationAdded `protobuf:"bytes,3,opt,name=participant_authorization_added,json=participantAuthorizationAdded,proto3,oneof"`
}

type TopologyEvent_ParticipantAuthorizationOnboarding struct {
	ParticipantAuthorizationOnboarding *ParticipantAuthorizationOnboarding `protobuf:"bytes,4,opt,name=participant_authorization_onboarding,json=participantAuthorizationOnboarding,proto3,oneof"`
}

func (*TopologyEvent_ParticipantAuthorizationChanged) isTopologyEvent_Event() {}

func (*TopologyEvent_ParticipantAuthorizationRevoked) isTopologyEvent_Event() {}

func (*TopologyEvent_ParticipantAuthorizationAdded) isTopologyEvent_Event() {}

func (*TopologyEvent_ParticipantAuthorizationOnboarding) isTopologyEvent_Event() {}

type ParticipantAuthorizationAdded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Required
	ParticipantId string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Required
	ParticipantPermission ParticipantPermission `protobuf:"varint,3,opt,name=participant_permission,json=participantPermission,proto3,enum=com.daml.ledger.api.v2.ParticipantPermission" json:"participant_permission,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ParticipantAuthorizationAdded) Reset() {
	*x = ParticipantAuthorizationAdded{}
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantAuthorizationAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantAuthorizationAdded) ProtoMessage() {}

func (x *ParticipantAuthorizationAdded) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantAuthorizationAdded.ProtoReflect.Descriptor instead.
func (*ParticipantAuthorizationAdded) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ParticipantAuthorizationAdded) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ParticipantAuthorizationAdded) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *ParticipantAuthorizationAdded) GetParticipantPermission() ParticipantPermission {
	if x != nil {
		return x.ParticipantPermission
	}
	return ParticipantPermission_PARTICIPANT_PERMISSION_UNSPECIFIED
}

type ParticipantAuthorizationChanged struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Required
	ParticipantId string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Required
	ParticipantPermission ParticipantPermission `protobuf:"varint,3,opt,name=participant_permission,json=participantPermission,proto3,enum=com.daml.ledger.api.v2.ParticipantPermission" json:"participant_permission,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ParticipantAuthorizationChanged) Reset() {
	*x = ParticipantAuthorizationChanged{}
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantAuthorizationChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantAuthorizationChanged) ProtoMessage() {}

func (x *ParticipantAuthorizationChanged) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantAuthorizationChanged.ProtoReflect.Descriptor instead.
func (*ParticipantAuthorizationChanged) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ParticipantAuthorizationChanged) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ParticipantAuthorizationChanged) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *ParticipantAuthorizationChanged) GetParticipantPermission() ParticipantPermission {
	if x != nil {
		return x.ParticipantPermission
	}
	return ParticipantPermission_PARTICIPANT_PERMISSION_UNSPECIFIED
}

type ParticipantAuthorizationRevoked struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Required
	ParticipantId string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantAuthorizationRevoked) Reset() {
	*x = ParticipantAuthorizationRevoked{}
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantAuthorizationRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantAuthorizationRevoked) ProtoMessage() {}

func (x *ParticipantAuthorizationRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantAuthorizationRevoked.ProtoReflect.Descriptor instead.
func (*ParticipantAuthorizationRevoked) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *ParticipantAuthorizationRevoked) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ParticipantAuthorizationRevoked) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type ParticipantAuthorizationOnboarding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Required
	ParticipantId string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Required
	ParticipantPermission ParticipantPermission `protobuf:"varint,3,opt,name=participant_permission,json=participantPermission,proto3,enum=com.daml.ledger.api.v2.ParticipantPermission" json:"participant_permission,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ParticipantAuthorizationOnboarding) Reset() {
	*x = ParticipantAuthorizationOnboarding{}
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantAuthorizationOnboarding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantAuthorizationOnboarding) ProtoMessage() {}

func (x *ParticipantAuthorizationOnboarding) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantAuthorizationOnboarding.ProtoReflect.Descriptor instead.
func (*ParticipantAuthorizationOnboarding) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *ParticipantAuthorizationOnboarding) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ParticipantAuthorizationOnboarding) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *ParticipantAuthorizationOnboarding) GetParticipantPermission() ParticipantPermission {
	if x != nil {
		return x.ParticipantPermission
	}
	return ParticipantPermission_PARTICIPANT_PERMISSION_UNSPECIFIED
}

var File_com_daml_ledger_api_v2_topology_transaction_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_topology_transaction_proto_rawDesc = "" +
	"\n" +
	"1com/daml/ledger/api/v2/topology_transaction.proto\x12\x16com.daml.ledger.api.v2\x1a*com/daml/ledger/api/v2/state_service.proto\x1a*com/daml/ledger/api/v2/trace_context.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n" +
	"\x13TopologyTransaction\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12'\n" +
	"\x0fsynchronizer_id\x18\x03 \x01(\tR\x0esynchronizerId\x12;\n" +
	"\vrecord_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordTime\x12=\n" +
	"\x06events\x18\x05 \x03(\v2%.com.daml.ledger.api.v2.TopologyEventR\x06events\x12I\n" +
	"\rtrace_context\x18\x06 \x01(\v2$.com.daml.ledger.api.v2.TraceContextR\ftraceContext\"\xba\x04\n" +
	"\rTopologyEvent\x12\x85\x01\n" +
	"!participant_authorization_changed\x18\x01 \x01(\v27.com.daml.ledger.api.v2.ParticipantAuthorizationChangedH\x00R\x1fparticipantAuthorizationChanged\x12\x85\x01\n" +
	"!participant_authorization_revoked\x18\x02 \x01(\v27.com.daml.ledger.api.v2.ParticipantAuthorizationRevokedH\x00R\x1fparticipantAuthorizationRevoked\x12\x7f\n" +
	"\x1fparticipant_authorization_added\x18\x03 \x01(\v25.com.daml.ledger.api.v2.ParticipantAuthorizationAddedH\x00R\x1dparticipantAuthorizationAdded\x12\x8e\x01\n" +
	"$participant_authorization_onboarding\x18\x04 \x01(\v2:.com.daml.ledger.api.v2.ParticipantAuthorizationOnboardingH\x00R\"participantAuthorizationOnboardingB\a\n" +
	"\x05event\"\xc7\x01\n" +
	"\x1dParticipantAuthorizationAdded\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12d\n" +
	"\x16participant_permission\x18\x03 \x01(\x0e2-.com.daml.ledger.api.v2.ParticipantPermissionR\x15participantPermission\"\xc9\x01\n" +
	"\x1fParticipantAuthorizationChanged\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12d\n" +
	"\x16participant_permission\x18\x03 \x01(\x0e2-.com.daml.ledger.api.v2.ParticipantPermissionR\x15participantPermission\"c\n" +
	"\x1fParticipantAuthorizationRevoked\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"\xcc\x01\n" +
	"\"ParticipantAuthorizationOnboarding\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12d\n" +
	"\x16participant_permission\x18\x03 \x01(\x0e2-.com.daml.ledger.api.v2.ParticipantPermissionR\x15participantPermissionB\x85\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x18TopologyTransactionProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_topology_transaction_proto_rawDesc), len(file_com_daml_ledger_api_v2_topology_transaction_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_topology_transaction_proto_rawDescData
}

var file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_com_daml_ledger_api_v2_topology_transaction_proto_goTypes = []any{
	(*TopologyTransaction)(nil),                // 0: com.daml.ledger.api.v2.TopologyTransaction
	(*TopologyEvent)(nil),                      // 1: com.daml.ledger.api.v2.TopologyEvent
	(*ParticipantAuthorizationAdded)(nil),      // 2: com.daml.ledger.api.v2.ParticipantAuthorizationAdded
	(*ParticipantAuthorizationChanged)(nil),    // 3: com.daml.ledger.api.v2.ParticipantAuthorizationChanged
	(*ParticipantAuthorizationRevoked)(nil),    // 4: com.daml.ledger.api.v2.ParticipantAuthorizationRevoked
	(*ParticipantAuthorizationOnboarding)(nil), // 5: com.daml.ledger.api.v2.ParticipantAuthorizationOnboarding
	(*timestamppb.Timestamp)(nil),              // 6: google.protobuf.Timestamp
	(*TraceContext)(nil),                       // 7: com.daml.ledger.api.v2.TraceContext
	(ParticipantPermission)(0),                 // 8: com.daml.ledger.api.v2.ParticipantPermission
}
var file_com_daml_ledger_api_v2_topology_transaction_proto_depIdxs = []int32{
	6,  // 0: com.daml.ledger.api.v2.TopologyTransaction.record_time:type_name -> google.protobuf.Timestamp
	1,  // 1: com.daml.ledger.api.v2.TopologyTransaction.events:type_name -> com.daml.ledger.api.v2.TopologyEvent
	7,  // 2: com.daml.ledger.api.v2.TopologyTransaction.trace_context:type_name -> com.daml.ledger.api.v2.TraceContext
	3,  // 3: com.daml.ledger.api.v2.TopologyEvent.participant_authorization_changed:type_name -> com.daml.ledger.api.v2.ParticipantAuthorizationChanged
	4,  // 4: com.daml.ledger.api.v2.TopologyEvent.participant_authorization_revoked:type_name -> com.daml.ledger.api.v2.ParticipantAuthorizationRevoked
	2,  // 5: com.daml.ledger.api.v2.TopologyEvent.participant_authorization_added:type_name -> com.daml.ledger.api.v2.ParticipantAuthorizationAdded
	5,  // 6: com.daml.ledger.api.v2.TopologyEvent.participant_authorization_onboarding:type_name -> com.daml.ledger.api.v2.ParticipantAuthorizationOnboarding
	8,  // 7: com.daml.ledger.api.v2.ParticipantAuthorizationAdded.participant_permission:type_name -> com.daml.ledger.api.v2.ParticipantPermission
	8,  // 8: com.daml.ledger.api.v2.ParticipantAuthorizationChanged.participant_permission:type_name -> com.daml.ledger.api.v2.ParticipantPermission
	8,  // 9: com.daml.ledger.api.v2.ParticipantAuthorizationOnboarding.participant_permission:type_name -> com.daml.ledger.api.v2.ParticipantPermission
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_topology_transaction_proto_init() }
func file_com_daml_ledger_api_v2_topology_transaction_proto_init() {
	if File_com_daml_ledger_api_v2_topology_transaction_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_state_service_proto_init()
	file_com_daml_ledger_api_v2_trace_context_proto_init()
	file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes[1].OneofWrappers = []any{
		(*TopologyEvent_ParticipantAuthorizationChanged)(nil),
		(*TopologyEvent_ParticipantAuthorizationRevoked)(nil),
		(*TopologyEvent_ParticipantAuthorizationAdded)(nil),
		(*TopologyEvent_ParticipantAuthorizationOnboarding)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_topology_transaction_proto_rawDesc), len(file_com_daml_ledger_api_v2_topology_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_topology_transaction_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_topology_transaction_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_topology_transaction_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_topology_transaction_proto = out.File
	file_com_daml_ledger_api_v2_topology_transaction_proto_goTypes = nil
	file_com_daml_ledger_api_v2_topology_transaction_proto_depIdxs = nil
}
