// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/transaction.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Filtered view of an on-ledger transaction's create and archive events.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned by the server. Useful for correlating logs.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The ID of the command which resulted in this transaction. Missing for everyone except the submitting party.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Optional
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The workflow ID used in command submission.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Optional
	WorkflowId string `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Ledger effective time.
	//
	// Required
	EffectiveAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// The collection of events.
	// Contains:
	//
	// - “CreatedEvent“ or “ArchivedEvent“ in case of ACS_DELTA transaction shape
	// - “CreatedEvent“ or “ExercisedEvent“ in case of LEDGER_EFFECTS transaction shape
	//
	// Required: must be non-empty
	Events []*Event `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	// The absolute offset. The details of this field are described in “community/ledger-api/README.md“.
	// It is a valid absolute offset (positive integer).
	//
	// Required
	Offset int64 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	// A valid synchronizer id.
	// Identifies the synchronizer that synchronized the transaction.
	//
	// Required
	SynchronizerId string `protobuf:"bytes,7,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// Ledger API trace context
	//
	// The trace context transported in this message corresponds to the trace context supplied
	// by the client application in a HTTP2 header of the original command submission.
	// We typically use a header to transfer this type of information. Here we use message
	// body, because it is used in gRPC streams which do not support per message headers.
	// This field will be populated with the trace context contained in the original submission.
	// If that was not provided, a unique ledger-api-server generated trace context will be used
	// instead.
	//
	// Optional
	TraceContext *TraceContext `protobuf:"bytes,8,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	// The time at which the transaction was recorded. The record time refers to the synchronizer
	// which synchronized the transaction.
	//
	// Required
	RecordTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	// For transaction externally signed, contains the external transaction hash
	// signed by the external party. Can be used to correlate an external submission with a committed transaction.
	//
	// Optional: can be empty
	ExternalTransactionHash []byte `protobuf:"bytes,10,opt,name=external_transaction_hash,json=externalTransactionHash,proto3,oneof" json:"external_transaction_hash,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_com_daml_ledger_api_v2_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *Transaction) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Transaction) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Transaction) GetEffectiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveAt
	}
	return nil
}

func (x *Transaction) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Transaction) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Transaction) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *Transaction) GetTraceContext() *TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *Transaction) GetRecordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordTime
	}
	return nil
}

func (x *Transaction) GetExternalTransactionHash() []byte {
	if x != nil {
		return x.ExternalTransactionHash
	}
	return nil
}

var File_com_daml_ledger_api_v2_transaction_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_transaction_proto_rawDesc = "" +
	"\n" +
	"(com/daml/ledger/api/v2/transaction.proto\x12\x16com.daml.ledger.api.v2\x1a\"com/daml/ledger/api/v2/event.proto\x1a*com/daml/ledger/api/v2/trace_context.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x04\n" +
	"\vTransaction\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12=\n" +
	"\feffective_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\veffectiveAt\x125\n" +
	"\x06events\x18\x05 \x03(\v2\x1d.com.daml.ledger.api.v2.EventR\x06events\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\x12'\n" +
	"\x0fsynchronizer_id\x18\a \x01(\tR\x0esynchronizerId\x12I\n" +
	"\rtrace_context\x18\b \x01(\v2$.com.daml.ledger.api.v2.TraceContextR\ftraceContext\x12;\n" +
	"\vrecord_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordTime\x12?\n" +
	"\x19external_transaction_hash\x18\n" +
	" \x01(\fH\x00R\x17externalTransactionHash\x88\x01\x01B\x1c\n" +
	"\x1a_external_transaction_hashB\xfd\x01\n" +
	"\x1acom.com.daml.ledger.api.v2B\x10TransactionProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_transaction_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_transaction_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_transaction_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_transaction_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_transaction_proto_rawDescData
}

var file_com_daml_ledger_api_v2_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_daml_ledger_api_v2_transaction_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: com.daml.ledger.api.v2.Transaction
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Event)(nil),                 // 2: com.daml.ledger.api.v2.Event
	(*TraceContext)(nil),          // 3: com.daml.ledger.api.v2.TraceContext
}
var file_com_daml_ledger_api_v2_transaction_proto_depIdxs = []int32{
	1, // 0: com.daml.ledger.api.v2.Transaction.effective_at:type_name -> google.protobuf.Timestamp
	2, // 1: com.daml.ledger.api.v2.Transaction.events:type_name -> com.daml.ledger.api.v2.Event
	3, // 2: com.daml.ledger.api.v2.Transaction.trace_context:type_name -> com.daml.ledger.api.v2.TraceContext
	1, // 3: com.daml.ledger.api.v2.Transaction.record_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_transaction_proto_init() }
func file_com_daml_ledger_api_v2_transaction_proto_init() {
	if File_com_daml_ledger_api_v2_transaction_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_event_proto_init()
	file_com_daml_ledger_api_v2_trace_context_proto_init()
	file_com_daml_ledger_api_v2_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_transaction_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_transaction_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_transaction_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_transaction_proto = out.File
	file_com_daml_ledger_api_v2_transaction_proto_goTypes = nil
	file_com_daml_ledger_api_v2_transaction_proto_depIdxs = nil
}
