// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/transaction_filter.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event shape for Transactions.
// Shapes are exclusive and only one of them can be defined in queries.
type TransactionShape int32

const (
	// Following official proto3 convention, not intended for actual use.
	TransactionShape_TRANSACTION_SHAPE_UNSPECIFIED TransactionShape = 0
	// Transaction shape that is sufficient to maintain an accurate ACS view.
	// The field witness_parties in events are populated as stakeholders, transaction filter will apply accordingly.
	// This translates to create and archive events.
	TransactionShape_TRANSACTION_SHAPE_ACS_DELTA TransactionShape = 1
	// Transaction shape that allows maintaining an ACS and also conveys detailed information about
	// all exercises.
	// The field witness_parties in events are populated as cumulative informees, transaction filter will apply accordingly.
	// This translates to create, consuming exercise and non-consuming exercise.
	TransactionShape_TRANSACTION_SHAPE_LEDGER_EFFECTS TransactionShape = 2
)

// Enum value maps for TransactionShape.
var (
	TransactionShape_name = map[int32]string{
		0: "TRANSACTION_SHAPE_UNSPECIFIED",
		1: "TRANSACTION_SHAPE_ACS_DELTA",
		2: "TRANSACTION_SHAPE_LEDGER_EFFECTS",
	}
	TransactionShape_value = map[string]int32{
		"TRANSACTION_SHAPE_UNSPECIFIED":    0,
		"TRANSACTION_SHAPE_ACS_DELTA":      1,
		"TRANSACTION_SHAPE_LEDGER_EFFECTS": 2,
	}
)

func (x TransactionShape) Enum() *TransactionShape {
	p := new(TransactionShape)
	*p = x
	return p
}

func (x TransactionShape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionShape) Descriptor() protoreflect.EnumDescriptor {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_enumTypes[0].Descriptor()
}

func (TransactionShape) Type() protoreflect.EnumType {
	return &file_com_daml_ledger_api_v2_transaction_filter_proto_enumTypes[0]
}

func (x TransactionShape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionShape.Descriptor instead.
func (TransactionShape) EnumDescriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{0}
}

// The union of a set of template filters, interface filters, or a wildcard.
type Filters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every filter in the cumulative list expands the scope of the resulting stream. Each interface,
	// template or wildcard filter means additional events that will match the query.
	// The impact of include_interface_view and include_created_event_blob fields in the filters will
	// also be accumulated.
	// A template or an interface SHOULD NOT appear twice in the accumulative field.
	// A wildcard filter SHOULD NOT be defined more than once in the accumulative field.
	// If no “CumulativeFilter“ defined, the default of a single “WildcardFilter“ with
	// include_created_event_blob unset is used.
	//
	// Optional: can be empty
	Cumulative    []*CumulativeFilter `protobuf:"bytes,1,rep,name=cumulative,proto3" json:"cumulative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Filters) GetCumulative() []*CumulativeFilter {
	if x != nil {
		return x.Cumulative
	}
	return nil
}

// A filter that matches all contracts that are either an instance of one of
// the “template_filters“ or that match one of the “interface_filters“.
type CumulativeFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	//
	// Types that are valid to be assigned to IdentifierFilter:
	//
	//	*CumulativeFilter_WildcardFilter
	//	*CumulativeFilter_InterfaceFilter
	//	*CumulativeFilter_TemplateFilter
	IdentifierFilter isCumulativeFilter_IdentifierFilter `protobuf_oneof:"identifier_filter"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CumulativeFilter) Reset() {
	*x = CumulativeFilter{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CumulativeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CumulativeFilter) ProtoMessage() {}

func (x *CumulativeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CumulativeFilter.ProtoReflect.Descriptor instead.
func (*CumulativeFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{1}
}

func (x *CumulativeFilter) GetIdentifierFilter() isCumulativeFilter_IdentifierFilter {
	if x != nil {
		return x.IdentifierFilter
	}
	return nil
}

func (x *CumulativeFilter) GetWildcardFilter() *WildcardFilter {
	if x != nil {
		if x, ok := x.IdentifierFilter.(*CumulativeFilter_WildcardFilter); ok {
			return x.WildcardFilter
		}
	}
	return nil
}

func (x *CumulativeFilter) GetInterfaceFilter() *InterfaceFilter {
	if x != nil {
		if x, ok := x.IdentifierFilter.(*CumulativeFilter_InterfaceFilter); ok {
			return x.InterfaceFilter
		}
	}
	return nil
}

func (x *CumulativeFilter) GetTemplateFilter() *TemplateFilter {
	if x != nil {
		if x, ok := x.IdentifierFilter.(*CumulativeFilter_TemplateFilter); ok {
			return x.TemplateFilter
		}
	}
	return nil
}

type isCumulativeFilter_IdentifierFilter interface {
	isCumulativeFilter_IdentifierFilter()
}

type CumulativeFilter_WildcardFilter struct {
	// A wildcard filter that matches all templates
	//
	// Optional
	WildcardFilter *WildcardFilter `protobuf:"bytes,1,opt,name=wildcard_filter,json=wildcardFilter,proto3,oneof"`
}

type CumulativeFilter_InterfaceFilter struct {
	// Include an “InterfaceView“ for every “InterfaceFilter“ matching a contract.
	// The “InterfaceFilter“ instances MUST each use a unique “interface_id“.
	//
	// Optional
	InterfaceFilter *InterfaceFilter `protobuf:"bytes,2,opt,name=interface_filter,json=interfaceFilter,proto3,oneof"`
}

type CumulativeFilter_TemplateFilter struct {
	// A template for which the data will be included in the
	// “create_arguments“ of a matching “CreatedEvent“.
	// If a contract is simultaneously selected by a template filter and one or more interface filters,
	// the corresponding “include_created_event_blob“ are consolidated using an OR operation.
	//
	// Optional
	TemplateFilter *TemplateFilter `protobuf:"bytes,3,opt,name=template_filter,json=templateFilter,proto3,oneof"`
}

func (*CumulativeFilter_WildcardFilter) isCumulativeFilter_IdentifierFilter() {}

func (*CumulativeFilter_InterfaceFilter) isCumulativeFilter_IdentifierFilter() {}

func (*CumulativeFilter_TemplateFilter) isCumulativeFilter_IdentifierFilter() {}

// This filter matches all templates.
type WildcardFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to include a “created_event_blob“ in the returned “CreatedEvent“.
	// Use this to access the contract create event payload in your API client
	// for submitting it as a disclosed contract with future commands.
	//
	// Optional
	IncludeCreatedEventBlob bool `protobuf:"varint,1,opt,name=include_created_event_blob,json=includeCreatedEventBlob,proto3" json:"include_created_event_blob,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WildcardFilter) Reset() {
	*x = WildcardFilter{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildcardFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildcardFilter) ProtoMessage() {}

func (x *WildcardFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildcardFilter.ProtoReflect.Descriptor instead.
func (*WildcardFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{2}
}

func (x *WildcardFilter) GetIncludeCreatedEventBlob() bool {
	if x != nil {
		return x.IncludeCreatedEventBlob
	}
	return false
}

// This filter matches contracts that implement a specific interface.
type InterfaceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interface that a matching contract must implement.
	// The “interface_id“ needs to be valid: corresponding interface should be defined in
	// one of the available packages at the time of the query.
	// Both package-name and package-id reference formats for the identifier are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	//
	// Required
	InterfaceId *Identifier `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	// Whether to include the interface view on the contract in the returned “CreatedEvent“.
	// Use this to access contract data in a uniform manner in your API client.
	//
	// Optional
	IncludeInterfaceView bool `protobuf:"varint,2,opt,name=include_interface_view,json=includeInterfaceView,proto3" json:"include_interface_view,omitempty"`
	// Whether to include a “created_event_blob“ in the returned “CreatedEvent“.
	// Use this to access the contract create event payload in your API client
	// for submitting it as a disclosed contract with future commands.
	//
	// Optional
	IncludeCreatedEventBlob bool `protobuf:"varint,3,opt,name=include_created_event_blob,json=includeCreatedEventBlob,proto3" json:"include_created_event_blob,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InterfaceFilter) Reset() {
	*x = InterfaceFilter{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceFilter) ProtoMessage() {}

func (x *InterfaceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceFilter.ProtoReflect.Descriptor instead.
func (*InterfaceFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceFilter) GetInterfaceId() *Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *InterfaceFilter) GetIncludeInterfaceView() bool {
	if x != nil {
		return x.IncludeInterfaceView
	}
	return false
}

func (x *InterfaceFilter) GetIncludeCreatedEventBlob() bool {
	if x != nil {
		return x.IncludeCreatedEventBlob
	}
	return false
}

// This filter matches contracts of a specific template.
type TemplateFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A template for which the payload should be included in the response.
	// The “template_id“ needs to be valid: corresponding template should be defined in
	// one of the available packages at the time of the query.
	// Both package-name and package-id reference formats for the identifier are supported.
	// Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Whether to include a “created_event_blob“ in the returned “CreatedEvent“.
	// Use this to access the contract event payload in your API client
	// for submitting it as a disclosed contract with future commands.
	//
	// Optional
	IncludeCreatedEventBlob bool `protobuf:"varint,2,opt,name=include_created_event_blob,json=includeCreatedEventBlob,proto3" json:"include_created_event_blob,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TemplateFilter) Reset() {
	*x = TemplateFilter{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateFilter) ProtoMessage() {}

func (x *TemplateFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateFilter.ProtoReflect.Descriptor instead.
func (*TemplateFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateFilter) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *TemplateFilter) GetIncludeCreatedEventBlob() bool {
	if x != nil {
		return x.IncludeCreatedEventBlob
	}
	return false
}

// A format for events which defines both which events should be included
// and what data should be computed and included for them.
//
// Note that some of the filtering behavior depends on the `TransactionShape`,
// which is expected to be specified alongside usages of `EventFormat`.
type EventFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each key must be a valid PartyIdString (as described in “value.proto“).
	// The interpretation of the filter depends on the transaction-shape being filtered:
	//
	//  1. For **ledger-effects** create and exercise events are returned, for which the witnesses include at least one of
	//     the listed parties and match the per-party filter.
	//  2. For **transaction and active-contract-set streams** create and archive events are returned for all contracts whose
	//     stakeholders include at least one of the listed parties and match the per-party filter.
	//
	// Optional: can be empty
	FiltersByParty map[string]*Filters `protobuf:"bytes,1,rep,name=filters_by_party,json=filtersByParty,proto3" json:"filters_by_party,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Wildcard filters that apply to all the parties existing on the participant. The interpretation of the filters is the same
	// with the per-party filter as described above.
	//
	// Optional
	FiltersForAnyParty *Filters `protobuf:"bytes,2,opt,name=filters_for_any_party,json=filtersForAnyParty,proto3" json:"filters_for_any_party,omitempty"`
	// If enabled, values served over the API will contain more information than strictly necessary to interpret the data.
	// In particular, setting the verbose flag to true triggers the ledger to include labels for record fields.
	//
	// Optional
	Verbose       bool `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFormat) Reset() {
	*x = EventFormat{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFormat) ProtoMessage() {}

func (x *EventFormat) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFormat.ProtoReflect.Descriptor instead.
func (*EventFormat) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{5}
}

func (x *EventFormat) GetFiltersByParty() map[string]*Filters {
	if x != nil {
		return x.FiltersByParty
	}
	return nil
}

func (x *EventFormat) GetFiltersForAnyParty() *Filters {
	if x != nil {
		return x.FiltersForAnyParty
	}
	return nil
}

func (x *EventFormat) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

// A format that specifies what events to include in Daml transactions
// and what data to compute and include for them.
type TransactionFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	EventFormat *EventFormat `protobuf:"bytes,1,opt,name=event_format,json=eventFormat,proto3" json:"event_format,omitempty"`
	// What transaction shape to use for interpreting the filters of the event format.
	//
	// Required
	TransactionShape TransactionShape `protobuf:"varint,2,opt,name=transaction_shape,json=transactionShape,proto3,enum=com.daml.ledger.api.v2.TransactionShape" json:"transaction_shape,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionFormat) Reset() {
	*x = TransactionFormat{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFormat) ProtoMessage() {}

func (x *TransactionFormat) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFormat.ProtoReflect.Descriptor instead.
func (*TransactionFormat) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionFormat) GetEventFormat() *EventFormat {
	if x != nil {
		return x.EventFormat
	}
	return nil
}

func (x *TransactionFormat) GetTransactionShape() TransactionShape {
	if x != nil {
		return x.TransactionShape
	}
	return TransactionShape_TRANSACTION_SHAPE_UNSPECIFIED
}

// A format specifying which topology transactions to include and how to render them.
type TopologyFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include participant authorization topology events in streams.
	// If unset, no participant authorization topology events are emitted in the stream.
	//
	// Optional
	IncludeParticipantAuthorizationEvents *ParticipantAuthorizationTopologyFormat `protobuf:"bytes,1,opt,name=include_participant_authorization_events,json=includeParticipantAuthorizationEvents,proto3" json:"include_participant_authorization_events,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *TopologyFormat) Reset() {
	*x = TopologyFormat{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyFormat) ProtoMessage() {}

func (x *TopologyFormat) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyFormat.ProtoReflect.Descriptor instead.
func (*TopologyFormat) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{7}
}

func (x *TopologyFormat) GetIncludeParticipantAuthorizationEvents() *ParticipantAuthorizationTopologyFormat {
	if x != nil {
		return x.IncludeParticipantAuthorizationEvents
	}
	return nil
}

// A format specifying which participant authorization topology transactions to include and how to render them.
type ParticipantAuthorizationTopologyFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of parties for which the topology transactions should be sent.
	// Empty means: for all parties.
	//
	// Optional: can be empty
	Parties       []string `protobuf:"bytes,1,rep,name=parties,proto3" json:"parties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantAuthorizationTopologyFormat) Reset() {
	*x = ParticipantAuthorizationTopologyFormat{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantAuthorizationTopologyFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantAuthorizationTopologyFormat) ProtoMessage() {}

func (x *ParticipantAuthorizationTopologyFormat) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantAuthorizationTopologyFormat.ProtoReflect.Descriptor instead.
func (*ParticipantAuthorizationTopologyFormat) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{8}
}

func (x *ParticipantAuthorizationTopologyFormat) GetParties() []string {
	if x != nil {
		return x.Parties
	}
	return nil
}

// A format specifying what updates to include and how to render them.
type UpdateFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include Daml transactions in streams.
	// If unset, no transactions are emitted in the stream.
	//
	// Optional
	IncludeTransactions *TransactionFormat `protobuf:"bytes,1,opt,name=include_transactions,json=includeTransactions,proto3" json:"include_transactions,omitempty"`
	// Include (un)assignments in the stream.
	// The events in the result take the shape TRANSACTION_SHAPE_ACS_DELTA.
	// If unset, no (un)assignments are emitted in the stream.
	//
	// Optional
	IncludeReassignments *EventFormat `protobuf:"bytes,2,opt,name=include_reassignments,json=includeReassignments,proto3" json:"include_reassignments,omitempty"`
	// Include topology events in streams.
	// If unset no topology events are emitted in the stream.
	//
	// Optional
	IncludeTopologyEvents *TopologyFormat `protobuf:"bytes,3,opt,name=include_topology_events,json=includeTopologyEvents,proto3" json:"include_topology_events,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateFormat) Reset() {
	*x = UpdateFormat{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormat) ProtoMessage() {}

func (x *UpdateFormat) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormat.ProtoReflect.Descriptor instead.
func (*UpdateFormat) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFormat) GetIncludeTransactions() *TransactionFormat {
	if x != nil {
		return x.IncludeTransactions
	}
	return nil
}

func (x *UpdateFormat) GetIncludeReassignments() *EventFormat {
	if x != nil {
		return x.IncludeReassignments
	}
	return nil
}

func (x *UpdateFormat) GetIncludeTopologyEvents() *TopologyFormat {
	if x != nil {
		return x.IncludeTopologyEvents
	}
	return nil
}

var File_com_daml_ledger_api_v2_transaction_filter_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc = "" +
	"\n" +
	"/com/daml/ledger/api/v2/transaction_filter.proto\x12\x16com.daml.ledger.api.v2\x1a\"com/daml/ledger/api/v2/value.proto\"S\n" +
	"\aFilters\x12H\n" +
	"\n" +
	"cumulative\x18\x01 \x03(\v2(.com.daml.ledger.api.v2.CumulativeFilterR\n" +
	"cumulative\"\xa3\x02\n" +
	"\x10CumulativeFilter\x12Q\n" +
	"\x0fwildcard_filter\x18\x01 \x01(\v2&.com.daml.ledger.api.v2.WildcardFilterH\x00R\x0ewildcardFilter\x12T\n" +
	"\x10interface_filter\x18\x02 \x01(\v2'.com.daml.ledger.api.v2.InterfaceFilterH\x00R\x0finterfaceFilter\x12Q\n" +
	"\x0ftemplate_filter\x18\x03 \x01(\v2&.com.daml.ledger.api.v2.TemplateFilterH\x00R\x0etemplateFilterB\x13\n" +
	"\x11identifier_filter\"M\n" +
	"\x0eWildcardFilter\x12;\n" +
	"\x1ainclude_created_event_blob\x18\x01 \x01(\bR\x17includeCreatedEventBlob\"\xcb\x01\n" +
	"\x0fInterfaceFilter\x12E\n" +
	"\finterface_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\vinterfaceId\x124\n" +
	"\x16include_interface_view\x18\x02 \x01(\bR\x14includeInterfaceView\x12;\n" +
	"\x1ainclude_created_event_blob\x18\x03 \x01(\bR\x17includeCreatedEventBlob\"\x92\x01\n" +
	"\x0eTemplateFilter\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12;\n" +
	"\x1ainclude_created_event_blob\x18\x02 \x01(\bR\x17includeCreatedEventBlob\"\xc2\x02\n" +
	"\vEventFormat\x12a\n" +
	"\x10filters_by_party\x18\x01 \x03(\v27.com.daml.ledger.api.v2.EventFormat.FiltersByPartyEntryR\x0efiltersByParty\x12R\n" +
	"\x15filters_for_any_party\x18\x02 \x01(\v2\x1f.com.daml.ledger.api.v2.FiltersR\x12filtersForAnyParty\x12\x18\n" +
	"\averbose\x18\x03 \x01(\bR\averbose\x1ab\n" +
	"\x13FiltersByPartyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.com.daml.ledger.api.v2.FiltersR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x11TransactionFormat\x12F\n" +
	"\fevent_format\x18\x01 \x01(\v2#.com.daml.ledger.api.v2.EventFormatR\veventFormat\x12U\n" +
	"\x11transaction_shape\x18\x02 \x01(\x0e2(.com.daml.ledger.api.v2.TransactionShapeR\x10transactionShape\"\xaa\x01\n" +
	"\x0eTopologyFormat\x12\x97\x01\n" +
	"(include_participant_authorization_events\x18\x01 \x01(\v2>.com.daml.ledger.api.v2.ParticipantAuthorizationTopologyFormatR%includeParticipantAuthorizationEvents\"B\n" +
	"&ParticipantAuthorizationTopologyFormat\x12\x18\n" +
	"\aparties\x18\x01 \x03(\tR\aparties\"\xa6\x02\n" +
	"\fUpdateFormat\x12\\\n" +
	"\x14include_transactions\x18\x01 \x01(\v2).com.daml.ledger.api.v2.TransactionFormatR\x13includeTransactions\x12X\n" +
	"\x15include_reassignments\x18\x02 \x01(\v2#.com.daml.ledger.api.v2.EventFormatR\x14includeReassignments\x12^\n" +
	"\x17include_topology_events\x18\x03 \x01(\v2&.com.daml.ledger.api.v2.TopologyFormatR\x15includeTopologyEvents*|\n" +
	"\x10TransactionShape\x12!\n" +
	"\x1dTRANSACTION_SHAPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRANSACTION_SHAPE_ACS_DELTA\x10\x01\x12$\n" +
	" TRANSACTION_SHAPE_LEDGER_EFFECTS\x10\x02B\x83\x02\n" +
	"\x1acom.com.daml.ledger.api.v2B\x16TransactionFilterProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescData
}

var file_com_daml_ledger_api_v2_transaction_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_com_daml_ledger_api_v2_transaction_filter_proto_goTypes = []any{
	(TransactionShape)(0),                          // 0: com.daml.ledger.api.v2.TransactionShape
	(*Filters)(nil),                                // 1: com.daml.ledger.api.v2.Filters
	(*CumulativeFilter)(nil),                       // 2: com.daml.ledger.api.v2.CumulativeFilter
	(*WildcardFilter)(nil),                         // 3: com.daml.ledger.api.v2.WildcardFilter
	(*InterfaceFilter)(nil),                        // 4: com.daml.ledger.api.v2.InterfaceFilter
	(*TemplateFilter)(nil),                         // 5: com.daml.ledger.api.v2.TemplateFilter
	(*EventFormat)(nil),                            // 6: com.daml.ledger.api.v2.EventFormat
	(*TransactionFormat)(nil),                      // 7: com.daml.ledger.api.v2.TransactionFormat
	(*TopologyFormat)(nil),                         // 8: com.daml.ledger.api.v2.TopologyFormat
	(*ParticipantAuthorizationTopologyFormat)(nil), // 9: com.daml.ledger.api.v2.ParticipantAuthorizationTopologyFormat
	(*UpdateFormat)(nil),                           // 10: com.daml.ledger.api.v2.UpdateFormat
	nil,                                            // 11: com.daml.ledger.api.v2.EventFormat.FiltersByPartyEntry
	(*Identifier)(nil),                             // 12: com.daml.ledger.api.v2.Identifier
}
var file_com_daml_ledger_api_v2_transaction_filter_proto_depIdxs = []int32{
	2,  // 0: com.daml.ledger.api.v2.Filters.cumulative:type_name -> com.daml.ledger.api.v2.CumulativeFilter
	3,  // 1: com.daml.ledger.api.v2.CumulativeFilter.wildcard_filter:type_name -> com.daml.ledger.api.v2.WildcardFilter
	4,  // 2: com.daml.ledger.api.v2.CumulativeFilter.interface_filter:type_name -> com.daml.ledger.api.v2.InterfaceFilter
	5,  // 3: com.daml.ledger.api.v2.CumulativeFilter.template_filter:type_name -> com.daml.ledger.api.v2.TemplateFilter
	12, // 4: com.daml.ledger.api.v2.InterfaceFilter.interface_id:type_name -> com.daml.ledger.api.v2.Identifier
	12, // 5: com.daml.ledger.api.v2.TemplateFilter.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	11, // 6: com.daml.ledger.api.v2.EventFormat.filters_by_party:type_name -> com.daml.ledger.api.v2.EventFormat.FiltersByPartyEntry
	1,  // 7: com.daml.ledger.api.v2.EventFormat.filters_for_any_party:type_name -> com.daml.ledger.api.v2.Filters
	6,  // 8: com.daml.ledger.api.v2.TransactionFormat.event_format:type_name -> com.daml.ledger.api.v2.EventFormat
	0,  // 9: com.daml.ledger.api.v2.TransactionFormat.transaction_shape:type_name -> com.daml.ledger.api.v2.TransactionShape
	9,  // 10: com.daml.ledger.api.v2.TopologyFormat.include_participant_authorization_events:type_name -> com.daml.ledger.api.v2.ParticipantAuthorizationTopologyFormat
	7,  // 11: com.daml.ledger.api.v2.UpdateFormat.include_transactions:type_name -> com.daml.ledger.api.v2.TransactionFormat
	6,  // 12: com.daml.ledger.api.v2.UpdateFormat.include_reassignments:type_name -> com.daml.ledger.api.v2.EventFormat
	8,  // 13: com.daml.ledger.api.v2.UpdateFormat.include_topology_events:type_name -> com.daml.ledger.api.v2.TopologyFormat
	1,  // 14: com.daml.ledger.api.v2.EventFormat.FiltersByPartyEntry.value:type_name -> com.daml.ledger.api.v2.Filters
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_transaction_filter_proto_init() }
func file_com_daml_ledger_api_v2_transaction_filter_proto_init() {
	if File_com_daml_ledger_api_v2_transaction_filter_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_value_proto_init()
	file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[1].OneofWrappers = []any{
		(*CumulativeFilter_WildcardFilter)(nil),
		(*CumulativeFilter_InterfaceFilter)(nil),
		(*CumulativeFilter_TemplateFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_transaction_filter_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_transaction_filter_proto_depIdxs,
		EnumInfos:         file_com_daml_ledger_api_v2_transaction_filter_proto_enumTypes,
		MessageInfos:      file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_transaction_filter_proto = out.File
	file_com_daml_ledger_api_v2_transaction_filter_proto_goTypes = nil
	file_com_daml_ledger_api_v2_transaction_filter_proto_depIdxs = nil
}
