// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/update_service.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUpdatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	BeginExclusive int64 `protobuf:"varint,1,opt,name=begin_exclusive,json=beginExclusive,proto3" json:"begin_exclusive,omitempty"`
	// Inclusive higher bound offset of the requested ledger section.
	// If specified the response will only contain transactions whose offset is less than or equal to this.
	// If not specified,
	//
	// - the descending_order must not be selected,
	// - the stream will not terminate.
	//
	// Optional
	EndInclusive *int64 `protobuf:"varint,2,opt,name=end_inclusive,json=endInclusive,proto3,oneof" json:"end_inclusive,omitempty"`
	// The update format for this request
	//
	// Required
	UpdateFormat *UpdateFormat `protobuf:"bytes,5,opt,name=update_format,json=updateFormat,proto3" json:"update_format,omitempty"`
	// If set, the stream will populate the elements in descending order.
	//
	// Optional
	DescendingOrder bool `protobuf:"varint,6,opt,name=descending_order,json=descendingOrder,proto3" json:"descending_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUpdatesRequest) Reset() {
	*x = GetUpdatesRequest{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesRequest) ProtoMessage() {}

func (x *GetUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUpdatesRequest) GetBeginExclusive() int64 {
	if x != nil {
		return x.BeginExclusive
	}
	return 0
}

func (x *GetUpdatesRequest) GetEndInclusive() int64 {
	if x != nil && x.EndInclusive != nil {
		return *x.EndInclusive
	}
	return 0
}

func (x *GetUpdatesRequest) GetUpdateFormat() *UpdateFormat {
	if x != nil {
		return x.UpdateFormat
	}
	return nil
}

func (x *GetUpdatesRequest) GetDescendingOrder() bool {
	if x != nil {
		return x.DescendingOrder
	}
	return false
}

type GetUpdatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The update that matches the filter in the request.
	//
	// # Required
	//
	// Types that are valid to be assigned to Update:
	//
	//	*GetUpdatesResponse_Transaction
	//	*GetUpdatesResponse_Reassignment
	//	*GetUpdatesResponse_OffsetCheckpoint
	//	*GetUpdatesResponse_TopologyTransaction
	Update        isGetUpdatesResponse_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdatesResponse) Reset() {
	*x = GetUpdatesResponse{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesResponse) ProtoMessage() {}

func (x *GetUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUpdatesResponse) GetUpdate() isGetUpdatesResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *GetUpdatesResponse) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Update.(*GetUpdatesResponse_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *GetUpdatesResponse) GetReassignment() *Reassignment {
	if x != nil {
		if x, ok := x.Update.(*GetUpdatesResponse_Reassignment); ok {
			return x.Reassignment
		}
	}
	return nil
}

func (x *GetUpdatesResponse) GetOffsetCheckpoint() *OffsetCheckpoint {
	if x != nil {
		if x, ok := x.Update.(*GetUpdatesResponse_OffsetCheckpoint); ok {
			return x.OffsetCheckpoint
		}
	}
	return nil
}

func (x *GetUpdatesResponse) GetTopologyTransaction() *TopologyTransaction {
	if x != nil {
		if x, ok := x.Update.(*GetUpdatesResponse_TopologyTransaction); ok {
			return x.TopologyTransaction
		}
	}
	return nil
}

type isGetUpdatesResponse_Update interface {
	isGetUpdatesResponse_Update()
}

type GetUpdatesResponse_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type GetUpdatesResponse_Reassignment struct {
	Reassignment *Reassignment `protobuf:"bytes,2,opt,name=reassignment,proto3,oneof"`
}

type GetUpdatesResponse_OffsetCheckpoint struct {
	OffsetCheckpoint *OffsetCheckpoint `protobuf:"bytes,3,opt,name=offset_checkpoint,json=offsetCheckpoint,proto3,oneof"`
}

type GetUpdatesResponse_TopologyTransaction struct {
	TopologyTransaction *TopologyTransaction `protobuf:"bytes,4,opt,name=topology_transaction,json=topologyTransaction,proto3,oneof"`
}

func (*GetUpdatesResponse_Transaction) isGetUpdatesResponse_Update() {}

func (*GetUpdatesResponse_Reassignment) isGetUpdatesResponse_Update() {}

func (*GetUpdatesResponse_OffsetCheckpoint) isGetUpdatesResponse_Update() {}

func (*GetUpdatesResponse_TopologyTransaction) isGetUpdatesResponse_Update() {}

type GetUpdateByOffsetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The offset of the update being looked up.
	// Must be a valid absolute offset (positive integer).
	//
	// Required
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// The format for the update.
	//
	// Required
	UpdateFormat  *UpdateFormat `protobuf:"bytes,2,opt,name=update_format,json=updateFormat,proto3" json:"update_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateByOffsetRequest) Reset() {
	*x = GetUpdateByOffsetRequest{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateByOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateByOffsetRequest) ProtoMessage() {}

func (x *GetUpdateByOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateByOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetUpdateByOffsetRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUpdateByOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUpdateByOffsetRequest) GetUpdateFormat() *UpdateFormat {
	if x != nil {
		return x.UpdateFormat
	}
	return nil
}

type GetUpdateByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a particular update.
	// Must be a valid LedgerString (as described in “value.proto“).
	//
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The format for the update.
	//
	// Required
	UpdateFormat  *UpdateFormat `protobuf:"bytes,2,opt,name=update_format,json=updateFormat,proto3" json:"update_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateByIdRequest) Reset() {
	*x = GetUpdateByIdRequest{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateByIdRequest) ProtoMessage() {}

func (x *GetUpdateByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUpdateByIdRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUpdateByIdRequest) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *GetUpdateByIdRequest) GetUpdateFormat() *UpdateFormat {
	if x != nil {
		return x.UpdateFormat
	}
	return nil
}

type GetUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The update that matches the filter in the request.
	//
	// # Required
	//
	// Types that are valid to be assigned to Update:
	//
	//	*GetUpdateResponse_Transaction
	//	*GetUpdateResponse_Reassignment
	//	*GetUpdateResponse_TopologyTransaction
	Update        isGetUpdateResponse_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateResponse) Reset() {
	*x = GetUpdateResponse{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateResponse) ProtoMessage() {}

func (x *GetUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetUpdateResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpdateResponse) GetUpdate() isGetUpdateResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *GetUpdateResponse) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Update.(*GetUpdateResponse_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *GetUpdateResponse) GetReassignment() *Reassignment {
	if x != nil {
		if x, ok := x.Update.(*GetUpdateResponse_Reassignment); ok {
			return x.Reassignment
		}
	}
	return nil
}

func (x *GetUpdateResponse) GetTopologyTransaction() *TopologyTransaction {
	if x != nil {
		if x, ok := x.Update.(*GetUpdateResponse_TopologyTransaction); ok {
			return x.TopologyTransaction
		}
	}
	return nil
}

type isGetUpdateResponse_Update interface {
	isGetUpdateResponse_Update()
}

type GetUpdateResponse_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type GetUpdateResponse_Reassignment struct {
	Reassignment *Reassignment `protobuf:"bytes,2,opt,name=reassignment,proto3,oneof"`
}

type GetUpdateResponse_TopologyTransaction struct {
	TopologyTransaction *TopologyTransaction `protobuf:"bytes,3,opt,name=topology_transaction,json=topologyTransaction,proto3,oneof"`
}

func (*GetUpdateResponse_Transaction) isGetUpdateResponse_Update() {}

func (*GetUpdateResponse_Reassignment) isGetUpdateResponse_Update() {}

func (*GetUpdateResponse_TopologyTransaction) isGetUpdateResponse_Update() {}

var File_com_daml_ledger_api_v2_update_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_update_service_proto_rawDesc = "" +
	"\n" +
	"+com/daml/ledger/api/v2/update_service.proto\x12\x16com.daml.ledger.api.v2\x1a.com/daml/ledger/api/v2/offset_checkpoint.proto\x1a)com/daml/ledger/api/v2/reassignment.proto\x1a1com/daml/ledger/api/v2/topology_transaction.proto\x1a(com/daml/ledger/api/v2/transaction.proto\x1a/com/daml/ledger/api/v2/transaction_filter.proto\"\x8b\x02\n" +
	"\x11GetUpdatesRequest\x12'\n" +
	"\x0fbegin_exclusive\x18\x01 \x01(\x03R\x0ebeginExclusive\x12(\n" +
	"\rend_inclusive\x18\x02 \x01(\x03H\x00R\fendInclusive\x88\x01\x01\x12I\n" +
	"\rupdate_format\x18\x05 \x01(\v2$.com.daml.ledger.api.v2.UpdateFormatR\fupdateFormat\x12)\n" +
	"\x10descending_order\x18\x06 \x01(\bR\x0fdescendingOrderB\x10\n" +
	"\x0e_end_inclusiveJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\x06filterR\averbose\"\xee\x02\n" +
	"\x12GetUpdatesResponse\x12G\n" +
	"\vtransaction\x18\x01 \x01(\v2#.com.daml.ledger.api.v2.TransactionH\x00R\vtransaction\x12J\n" +
	"\freassignment\x18\x02 \x01(\v2$.com.daml.ledger.api.v2.ReassignmentH\x00R\freassignment\x12W\n" +
	"\x11offset_checkpoint\x18\x03 \x01(\v2(.com.daml.ledger.api.v2.OffsetCheckpointH\x00R\x10offsetCheckpoint\x12`\n" +
	"\x14topology_transaction\x18\x04 \x01(\v2+.com.daml.ledger.api.v2.TopologyTransactionH\x00R\x13topologyTransactionB\b\n" +
	"\x06update\"}\n" +
	"\x18GetUpdateByOffsetRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12I\n" +
	"\rupdate_format\x18\x02 \x01(\v2$.com.daml.ledger.api.v2.UpdateFormatR\fupdateFormat\"~\n" +
	"\x14GetUpdateByIdRequest\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12I\n" +
	"\rupdate_format\x18\x02 \x01(\v2$.com.daml.ledger.api.v2.UpdateFormatR\fupdateFormat\"\x94\x02\n" +
	"\x11GetUpdateResponse\x12G\n" +
	"\vtransaction\x18\x01 \x01(\v2#.com.daml.ledger.api.v2.TransactionH\x00R\vtransaction\x12J\n" +
	"\freassignment\x18\x02 \x01(\v2$.com.daml.ledger.api.v2.ReassignmentH\x00R\freassignment\x12`\n" +
	"\x14topology_transaction\x18\x03 \x01(\v2+.com.daml.ledger.api.v2.TopologyTransactionH\x00R\x13topologyTransactionB\b\n" +
	"\x06update2\xd2\x02\n" +
	"\rUpdateService\x12e\n" +
	"\n" +
	"GetUpdates\x12).com.daml.ledger.api.v2.GetUpdatesRequest\x1a*.com.daml.ledger.api.v2.GetUpdatesResponse0\x01\x12p\n" +
	"\x11GetUpdateByOffset\x120.com.daml.ledger.api.v2.GetUpdateByOffsetRequest\x1a).com.daml.ledger.api.v2.GetUpdateResponse\x12h\n" +
	"\rGetUpdateById\x12,.com.daml.ledger.api.v2.GetUpdateByIdRequest\x1a).com.daml.ledger.api.v2.GetUpdateResponseB\xff\x01\n" +
	"\x1acom.com.daml.ledger.api.v2B\x12UpdateServiceProtoP\x01ZPgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2;apiv2\xa2\x02\x04CDLA\xaa\x02\x16Com.Daml.Ledger.Api.V2\xca\x02\x16Com\\Daml\\Ledger\\Api\\V2\xe2\x02\"Com\\Daml\\Ledger\\Api\\V2\\GPBMetadata\xea\x02\x1aCom::Daml::Ledger::Api::V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_update_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_update_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_update_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_update_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_update_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_update_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_update_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_com_daml_ledger_api_v2_update_service_proto_goTypes = []any{
	(*GetUpdatesRequest)(nil),        // 0: com.daml.ledger.api.v2.GetUpdatesRequest
	(*GetUpdatesResponse)(nil),       // 1: com.daml.ledger.api.v2.GetUpdatesResponse
	(*GetUpdateByOffsetRequest)(nil), // 2: com.daml.ledger.api.v2.GetUpdateByOffsetRequest
	(*GetUpdateByIdRequest)(nil),     // 3: com.daml.ledger.api.v2.GetUpdateByIdRequest
	(*GetUpdateResponse)(nil),        // 4: com.daml.ledger.api.v2.GetUpdateResponse
	(*UpdateFormat)(nil),             // 5: com.daml.ledger.api.v2.UpdateFormat
	(*Transaction)(nil),              // 6: com.daml.ledger.api.v2.Transaction
	(*Reassignment)(nil),             // 7: com.daml.ledger.api.v2.Reassignment
	(*OffsetCheckpoint)(nil),         // 8: com.daml.ledger.api.v2.OffsetCheckpoint
	(*TopologyTransaction)(nil),      // 9: com.daml.ledger.api.v2.TopologyTransaction
}
var file_com_daml_ledger_api_v2_update_service_proto_depIdxs = []int32{
	5,  // 0: com.daml.ledger.api.v2.GetUpdatesRequest.update_format:type_name -> com.daml.ledger.api.v2.UpdateFormat
	6,  // 1: com.daml.ledger.api.v2.GetUpdatesResponse.transaction:type_name -> com.daml.ledger.api.v2.Transaction
	7,  // 2: com.daml.ledger.api.v2.GetUpdatesResponse.reassignment:type_name -> com.daml.ledger.api.v2.Reassignment
	8,  // 3: com.daml.ledger.api.v2.GetUpdatesResponse.offset_checkpoint:type_name -> com.daml.ledger.api.v2.OffsetCheckpoint
	9,  // 4: com.daml.ledger.api.v2.GetUpdatesResponse.topology_transaction:type_name -> com.daml.ledger.api.v2.TopologyTransaction
	5,  // 5: com.daml.ledger.api.v2.GetUpdateByOffsetRequest.update_format:type_name -> com.daml.ledger.api.v2.UpdateFormat
	5,  // 6: com.daml.ledger.api.v2.GetUpdateByIdRequest.update_format:type_name -> com.daml.ledger.api.v2.UpdateFormat
	6,  // 7: com.daml.ledger.api.v2.GetUpdateResponse.transaction:type_name -> com.daml.ledger.api.v2.Transaction
	7,  // 8: com.daml.ledger.api.v2.GetUpdateResponse.reassignment:type_name -> com.daml.ledger.api.v2.Reassignment
	9,  // 9: com.daml.ledger.api.v2.GetUpdateResponse.topology_transaction:type_name -> com.daml.ledger.api.v2.TopologyTransaction
	0,  // 10: com.daml.ledger.api.v2.UpdateService.GetUpdates:input_type -> com.daml.ledger.api.v2.GetUpdatesRequest
	2,  // 11: com.daml.ledger.api.v2.UpdateService.GetUpdateByOffset:input_type -> com.daml.ledger.api.v2.GetUpdateByOffsetRequest
	3,  // 12: com.daml.ledger.api.v2.UpdateService.GetUpdateById:input_type -> com.daml.ledger.api.v2.GetUpdateByIdRequest
	1,  // 13: com.daml.ledger.api.v2.UpdateService.GetUpdates:output_type -> com.daml.ledger.api.v2.GetUpdatesResponse
	4,  // 14: com.daml.ledger.api.v2.UpdateService.GetUpdateByOffset:output_type -> com.daml.ledger.api.v2.GetUpdateResponse
	4,  // 15: com.daml.ledger.api.v2.UpdateService.GetUpdateById:output_type -> com.daml.ledger.api.v2.GetUpdateResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_update_service_proto_init() }
func file_com_daml_ledger_api_v2_update_service_proto_init() {
	if File_com_daml_ledger_api_v2_update_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_offset_checkpoint_proto_init()
	file_com_daml_ledger_api_v2_reassignment_proto_init()
	file_com_daml_ledger_api_v2_topology_transaction_proto_init()
	file_com_daml_ledger_api_v2_transaction_proto_init()
	file_com_daml_ledger_api_v2_transaction_filter_proto_init()
	file_com_daml_ledger_api_v2_update_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_com_daml_ledger_api_v2_update_service_proto_msgTypes[1].OneofWrappers = []any{
		(*GetUpdatesResponse_Transaction)(nil),
		(*GetUpdatesResponse_Reassignment)(nil),
		(*GetUpdatesResponse_OffsetCheckpoint)(nil),
		(*GetUpdatesResponse_TopologyTransaction)(nil),
	}
	file_com_daml_ledger_api_v2_update_service_proto_msgTypes[4].OneofWrappers = []any{
		(*GetUpdateResponse_Transaction)(nil),
		(*GetUpdateResponse_Reassignment)(nil),
		(*GetUpdateResponse_TopologyTransaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_update_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_update_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_update_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_update_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_update_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_update_service_proto = out.File
	file_com_daml_ledger_api_v2_update_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_update_service_proto_depIdxs = nil
}
