// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: com/daml/ledger/api/v2/update_service.proto

package apiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateService_GetUpdates_FullMethodName        = "/com.daml.ledger.api.v2.UpdateService/GetUpdates"
	UpdateService_GetUpdateByOffset_FullMethodName = "/com.daml.ledger.api.v2.UpdateService/GetUpdateByOffset"
	UpdateService_GetUpdateById_FullMethodName     = "/com.daml.ledger.api.v2.UpdateService/GetUpdateById"
)

// UpdateServiceClient is the client API for UpdateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Allows clients to read updates (transactions, (un)assignments, topology events) from the ledger.
//
// “GetUpdates“ provides a comprehensive stream of updates/changes
// which happened on the virtual shared ledger. These streams are indexed with ledger
// offsets, which are strictly increasing.
// The virtual shared ledger consist of changes happening on multiple synchronizers which are
// connected to the serving participant. Each update belongs to one synchronizer, this is
// provided in the result (the “synchronizer_id“ field in “Transaction“
// for transactions, the “source“ field in “UnassignedEvent“ and the “target“ field in “AssignedEvent“).
// Consumers can rely on strong causal guarantees on the virtual shared ledger for a single
// synchronizer: updates which have greater offsets are happened after than updates with smaller
// offsets for the same synchronizer. Across different synchronizers this is not guaranteed.
type UpdateServiceClient interface {
	// Read the ledger's filtered update stream for the specified contents and filters.
	// It returns the event types in accordance with the stream contents selected. Also the selection criteria
	// for individual events depends on the transaction shape chosen.
	//
	// - ACS delta: a requesting party must be a stakeholder of an event for it to be included.
	// - ledger effects: a requesting party must be a witness of an event for it to be included.
	GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUpdatesResponse], error)
	// Lookup an update by its offset.
	// If there is no update with this offset, or all the events are filtered, an UPDATE_NOT_FOUND error will be raised.
	GetUpdateByOffset(ctx context.Context, in *GetUpdateByOffsetRequest, opts ...grpc.CallOption) (*GetUpdateResponse, error)
	// Lookup an update by its ID.
	// If there is no update with this ID, or all the events are filtered, an UPDATE_NOT_FOUND error will be raised.
	GetUpdateById(ctx context.Context, in *GetUpdateByIdRequest, opts ...grpc.CallOption) (*GetUpdateResponse, error)
}

type updateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateServiceClient(cc grpc.ClientConnInterface) UpdateServiceClient {
	return &updateServiceClient{cc}
}

func (c *updateServiceClient) GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpdateService_ServiceDesc.Streams[0], UpdateService_GetUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUpdatesRequest, GetUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdateService_GetUpdatesClient = grpc.ServerStreamingClient[GetUpdatesResponse]

func (c *updateServiceClient) GetUpdateByOffset(ctx context.Context, in *GetUpdateByOffsetRequest, opts ...grpc.CallOption) (*GetUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpdateResponse)
	err := c.cc.Invoke(ctx, UpdateService_GetUpdateByOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateServiceClient) GetUpdateById(ctx context.Context, in *GetUpdateByIdRequest, opts ...grpc.CallOption) (*GetUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpdateResponse)
	err := c.cc.Invoke(ctx, UpdateService_GetUpdateById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateServiceServer is the server API for UpdateService service.
// All implementations must embed UnimplementedUpdateServiceServer
// for forward compatibility.
//
// Allows clients to read updates (transactions, (un)assignments, topology events) from the ledger.
//
// “GetUpdates“ provides a comprehensive stream of updates/changes
// which happened on the virtual shared ledger. These streams are indexed with ledger
// offsets, which are strictly increasing.
// The virtual shared ledger consist of changes happening on multiple synchronizers which are
// connected to the serving participant. Each update belongs to one synchronizer, this is
// provided in the result (the “synchronizer_id“ field in “Transaction“
// for transactions, the “source“ field in “UnassignedEvent“ and the “target“ field in “AssignedEvent“).
// Consumers can rely on strong causal guarantees on the virtual shared ledger for a single
// synchronizer: updates which have greater offsets are happened after than updates with smaller
// offsets for the same synchronizer. Across different synchronizers this is not guaranteed.
type UpdateServiceServer interface {
	// Read the ledger's filtered update stream for the specified contents and filters.
	// It returns the event types in accordance with the stream contents selected. Also the selection criteria
	// for individual events depends on the transaction shape chosen.
	//
	// - ACS delta: a requesting party must be a stakeholder of an event for it to be included.
	// - ledger effects: a requesting party must be a witness of an event for it to be included.
	GetUpdates(*GetUpdatesRequest, grpc.ServerStreamingServer[GetUpdatesResponse]) error
	// Lookup an update by its offset.
	// If there is no update with this offset, or all the events are filtered, an UPDATE_NOT_FOUND error will be raised.
	GetUpdateByOffset(context.Context, *GetUpdateByOffsetRequest) (*GetUpdateResponse, error)
	// Lookup an update by its ID.
	// If there is no update with this ID, or all the events are filtered, an UPDATE_NOT_FOUND error will be raised.
	GetUpdateById(context.Context, *GetUpdateByIdRequest) (*GetUpdateResponse, error)
	mustEmbedUnimplementedUpdateServiceServer()
}

// UnimplementedUpdateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateServiceServer struct{}

func (UnimplementedUpdateServiceServer) GetUpdates(*GetUpdatesRequest, grpc.ServerStreamingServer[GetUpdatesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetUpdates not implemented")
}
func (UnimplementedUpdateServiceServer) GetUpdateByOffset(context.Context, *GetUpdateByOffsetRequest) (*GetUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpdateByOffset not implemented")
}
func (UnimplementedUpdateServiceServer) GetUpdateById(context.Context, *GetUpdateByIdRequest) (*GetUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpdateById not implemented")
}
func (UnimplementedUpdateServiceServer) mustEmbedUnimplementedUpdateServiceServer() {}
func (UnimplementedUpdateServiceServer) testEmbeddedByValue()                       {}

// UnsafeUpdateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateServiceServer will
// result in compilation errors.
type UnsafeUpdateServiceServer interface {
	mustEmbedUnimplementedUpdateServiceServer()
}

func RegisterUpdateServiceServer(s grpc.ServiceRegistrar, srv UpdateServiceServer) {
	// If the following call pancis, it indicates UnimplementedUpdateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateService_ServiceDesc, srv)
}

func _UpdateService_GetUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdateServiceServer).GetUpdates(m, &grpc.GenericServerStream[GetUpdatesRequest, GetUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdateService_GetUpdatesServer = grpc.ServerStreamingServer[GetUpdatesResponse]

func _UpdateService_GetUpdateByOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdateByOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServiceServer).GetUpdateByOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateService_GetUpdateByOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServiceServer).GetUpdateByOffset(ctx, req.(*GetUpdateByOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateService_GetUpdateById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdateByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServiceServer).GetUpdateById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateService_GetUpdateById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServiceServer).GetUpdateById(ctx, req.(*GetUpdateByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateService_ServiceDesc is the grpc.ServiceDesc for UpdateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.daml.ledger.api.v2.UpdateService",
	HandlerType: (*UpdateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUpdateByOffset",
			Handler:    _UpdateService_GetUpdateByOffset_Handler,
		},
		{
			MethodName: "GetUpdateById",
			Handler:    _UpdateService_GetUpdateById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUpdates",
			Handler:       _UpdateService_GetUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "com/daml/ledger/api/v2/update_service.proto",
}
