// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data.proto

package transactionv1

import (
	v2 "github.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fetch node
type Fetch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	//
	// Required
	LfVersion string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	// Required
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Required
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	//
	// Required
	TemplateId *v2.Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Required: must be non-empty
	Signatories []string `protobuf:"bytes,5,rep,name=signatories,proto3" json:"signatories,omitempty"`
	// Required: must be non-empty
	Stakeholders []string `protobuf:"bytes,6,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	// Required: must be non-empty
	ActingParties []string `protobuf:"bytes,7,rep,name=acting_parties,json=actingParties,proto3" json:"acting_parties,omitempty"`
	// Optional
	InterfaceId   *v2.Identifier `protobuf:"bytes,8,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fetch) Reset() {
	*x = Fetch{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fetch) ProtoMessage() {}

func (x *Fetch) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fetch.ProtoReflect.Descriptor instead.
func (*Fetch) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescGZIP(), []int{0}
}

func (x *Fetch) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *Fetch) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Fetch) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Fetch) GetTemplateId() *v2.Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *Fetch) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *Fetch) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

func (x *Fetch) GetActingParties() []string {
	if x != nil {
		return x.ActingParties
	}
	return nil
}

func (x *Fetch) GetInterfaceId() *v2.Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

// Exercise node
type Exercise struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	//
	// Required
	LfVersion string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	// Required
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Required
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	//
	// Required
	TemplateId *v2.Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Required: must be non-empty
	Signatories []string `protobuf:"bytes,5,rep,name=signatories,proto3" json:"signatories,omitempty"`
	// Required: must be non-empty
	Stakeholders []string `protobuf:"bytes,6,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	// Required: must be non-empty
	ActingParties []string `protobuf:"bytes,7,rep,name=acting_parties,json=actingParties,proto3" json:"acting_parties,omitempty"`
	// The identifier uses the package-id reference format.
	//
	// Optional
	InterfaceId *v2.Identifier `protobuf:"bytes,8,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	// Required
	ChoiceId string `protobuf:"bytes,9,opt,name=choice_id,json=choiceId,proto3" json:"choice_id,omitempty"`
	// Required
	ChosenValue *v2.Value `protobuf:"bytes,10,opt,name=chosen_value,json=chosenValue,proto3" json:"chosen_value,omitempty"`
	// Required
	Consuming bool `protobuf:"varint,11,opt,name=consuming,proto3" json:"consuming,omitempty"`
	// Optional: can be empty
	Children []string `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	// Optional
	ExerciseResult *v2.Value `protobuf:"bytes,13,opt,name=exercise_result,json=exerciseResult,proto3" json:"exercise_result,omitempty"`
	// Optional: can be empty
	ChoiceObservers []string `protobuf:"bytes,14,rep,name=choice_observers,json=choiceObservers,proto3" json:"choice_observers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescGZIP(), []int{1}
}

func (x *Exercise) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *Exercise) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Exercise) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Exercise) GetTemplateId() *v2.Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *Exercise) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *Exercise) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

func (x *Exercise) GetActingParties() []string {
	if x != nil {
		return x.ActingParties
	}
	return nil
}

func (x *Exercise) GetInterfaceId() *v2.Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *Exercise) GetChoiceId() string {
	if x != nil {
		return x.ChoiceId
	}
	return ""
}

func (x *Exercise) GetChosenValue() *v2.Value {
	if x != nil {
		return x.ChosenValue
	}
	return nil
}

func (x *Exercise) GetConsuming() bool {
	if x != nil {
		return x.Consuming
	}
	return false
}

func (x *Exercise) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Exercise) GetExerciseResult() *v2.Value {
	if x != nil {
		return x.ExerciseResult
	}
	return nil
}

func (x *Exercise) GetChoiceObservers() []string {
	if x != nil {
		return x.ChoiceObservers
	}
	return nil
}

// Create Node
type Create struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	//
	// Required
	LfVersion string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	// Required
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Required
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	//
	// Required
	TemplateId *v2.Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Required
	Argument *v2.Value `protobuf:"bytes,5,opt,name=argument,proto3" json:"argument,omitempty"`
	// Required: must be non-empty
	Signatories []string `protobuf:"bytes,6,rep,name=signatories,proto3" json:"signatories,omitempty"`
	// Required: must be non-empty
	Stakeholders  []string `protobuf:"bytes,7,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescGZIP(), []int{2}
}

func (x *Create) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *Create) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Create) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Create) GetTemplateId() *v2.Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *Create) GetArgument() *v2.Value {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *Create) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *Create) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

// Rollback Node
type Rollback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: must be non-empty
	Children      []string `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rollback) Reset() {
	*x = Rollback{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rollback) ProtoMessage() {}

func (x *Rollback) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rollback.ProtoReflect.Descriptor instead.
func (*Rollback) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescGZIP(), []int{3}
}

func (x *Rollback) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	//
	// Types that are valid to be assigned to NodeType:
	//
	//	*Node_Create
	//	*Node_Fetch
	//	*Node_Exercise
	//	*Node_Rollback
	NodeType      isNode_NodeType `protobuf_oneof:"node_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescGZIP(), []int{4}
}

func (x *Node) GetNodeType() isNode_NodeType {
	if x != nil {
		return x.NodeType
	}
	return nil
}

func (x *Node) GetCreate() *Create {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *Node) GetFetch() *Fetch {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Fetch); ok {
			return x.Fetch
		}
	}
	return nil
}

func (x *Node) GetExercise() *Exercise {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Exercise); ok {
			return x.Exercise
		}
	}
	return nil
}

func (x *Node) GetRollback() *Rollback {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

type isNode_NodeType interface {
	isNode_NodeType()
}

type Node_Create struct {
	Create *Create `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type Node_Fetch struct {
	Fetch *Fetch `protobuf:"bytes,2,opt,name=fetch,proto3,oneof"`
}

type Node_Exercise struct {
	Exercise *Exercise `protobuf:"bytes,3,opt,name=exercise,proto3,oneof"`
}

type Node_Rollback struct {
	Rollback *Rollback `protobuf:"bytes,4,opt,name=rollback,proto3,oneof"`
}

func (*Node_Create) isNode_NodeType() {}

func (*Node_Fetch) isNode_NodeType() {}

func (*Node_Exercise) isNode_NodeType() {}

func (*Node_Rollback) isNode_NodeType() {}

var File_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDesc = "" +
	"\n" +
	"Scom/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data.proto\x121com.daml.ledger.api.v2.interactive.transaction.v1\x1a\"com/daml/ledger/api/v2/value.proto\"\xe3\x02\n" +
	"\x05Fetch\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12C\n" +
	"\vtemplate_id\x18\x04 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12 \n" +
	"\vsignatories\x18\x05 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\x06 \x03(\tR\fstakeholders\x12%\n" +
	"\x0eacting_parties\x18\a \x03(\tR\ractingParties\x12E\n" +
	"\finterface_id\x18\b \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\vinterfaceId\"\xf2\x04\n" +
	"\bExercise\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12C\n" +
	"\vtemplate_id\x18\x04 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x12 \n" +
	"\vsignatories\x18\x05 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\x06 \x03(\tR\fstakeholders\x12%\n" +
	"\x0eacting_parties\x18\a \x03(\tR\ractingParties\x12E\n" +
	"\finterface_id\x18\b \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\vinterfaceId\x12\x1b\n" +
	"\tchoice_id\x18\t \x01(\tR\bchoiceId\x12@\n" +
	"\fchosen_value\x18\n" +
	" \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\vchosenValue\x12\x1c\n" +
	"\tconsuming\x18\v \x01(\bR\tconsuming\x12\x1a\n" +
	"\bchildren\x18\f \x03(\tR\bchildren\x12F\n" +
	"\x0fexercise_result\x18\r \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\x0eexerciseResult\x12)\n" +
	"\x10choice_observers\x18\x0e \x03(\tR\x0fchoiceObservers\"\xb1\x02\n" +
	"\x06Create\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12C\n" +
	"\vtemplate_id\x18\x04 \x01(\v2\".com.daml.ledger.api.v2.IdentifierR\n" +
	"templateId\x129\n" +
	"\bargument\x18\x05 \x01(\v2\x1d.com.daml.ledger.api.v2.ValueR\bargument\x12 \n" +
	"\vsignatories\x18\x06 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\a \x03(\tR\fstakeholders\"&\n" +
	"\bRollback\x12\x1a\n" +
	"\bchildren\x18\x01 \x03(\tR\bchildren\"\xf0\x02\n" +
	"\x04Node\x12S\n" +
	"\x06create\x18\x01 \x01(\v29.com.daml.ledger.api.v2.interactive.transaction.v1.CreateH\x00R\x06create\x12P\n" +
	"\x05fetch\x18\x02 \x01(\v28.com.daml.ledger.api.v2.interactive.transaction.v1.FetchH\x00R\x05fetch\x12Y\n" +
	"\bexercise\x18\x03 \x01(\v2;.com.daml.ledger.api.v2.interactive.transaction.v1.ExerciseH\x00R\bexercise\x12Y\n" +
	"\brollback\x18\x04 \x01(\v2;.com.daml.ledger.api.v2.interactive.transaction.v1.RollbackH\x00R\brollbackB\v\n" +
	"\tnode_typeB\xbb\x03\n" +
	"5com.com.daml.ledger.api.v2.interactive.transaction.v1B\x1eInteractiveSubmissionDataProtoP\x01Zsgithub.com/cordialsys/crosschain/chain/canton/types/com/daml/ledger/api/v2/interactive/transaction/v1;transactionv1\xa2\x02\aCDLAVIT\xaa\x021Com.Daml.Ledger.Api.V2.Interactive.Transaction.V1\xca\x021Com\\Daml\\Ledger\\Api\\V2\\Interactive\\Transaction\\V1\xe2\x02=Com\\Daml\\Ledger\\Api\\V2\\Interactive\\Transaction\\V1\\GPBMetadata\xea\x028Com::Daml::Ledger::Api::V2::Interactive::Transaction::V1b\x06proto3"

var (
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDesc), len(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDescData
}

var file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_goTypes = []any{
	(*Fetch)(nil),         // 0: com.daml.ledger.api.v2.interactive.transaction.v1.Fetch
	(*Exercise)(nil),      // 1: com.daml.ledger.api.v2.interactive.transaction.v1.Exercise
	(*Create)(nil),        // 2: com.daml.ledger.api.v2.interactive.transaction.v1.Create
	(*Rollback)(nil),      // 3: com.daml.ledger.api.v2.interactive.transaction.v1.Rollback
	(*Node)(nil),          // 4: com.daml.ledger.api.v2.interactive.transaction.v1.Node
	(*v2.Identifier)(nil), // 5: com.daml.ledger.api.v2.Identifier
	(*v2.Value)(nil),      // 6: com.daml.ledger.api.v2.Value
}
var file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_depIdxs = []int32{
	5,  // 0: com.daml.ledger.api.v2.interactive.transaction.v1.Fetch.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	5,  // 1: com.daml.ledger.api.v2.interactive.transaction.v1.Fetch.interface_id:type_name -> com.daml.ledger.api.v2.Identifier
	5,  // 2: com.daml.ledger.api.v2.interactive.transaction.v1.Exercise.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	5,  // 3: com.daml.ledger.api.v2.interactive.transaction.v1.Exercise.interface_id:type_name -> com.daml.ledger.api.v2.Identifier
	6,  // 4: com.daml.ledger.api.v2.interactive.transaction.v1.Exercise.chosen_value:type_name -> com.daml.ledger.api.v2.Value
	6,  // 5: com.daml.ledger.api.v2.interactive.transaction.v1.Exercise.exercise_result:type_name -> com.daml.ledger.api.v2.Value
	5,  // 6: com.daml.ledger.api.v2.interactive.transaction.v1.Create.template_id:type_name -> com.daml.ledger.api.v2.Identifier
	6,  // 7: com.daml.ledger.api.v2.interactive.transaction.v1.Create.argument:type_name -> com.daml.ledger.api.v2.Value
	2,  // 8: com.daml.ledger.api.v2.interactive.transaction.v1.Node.create:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.Create
	0,  // 9: com.daml.ledger.api.v2.interactive.transaction.v1.Node.fetch:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.Fetch
	1,  // 10: com.daml.ledger.api.v2.interactive.transaction.v1.Node.exercise:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.Exercise
	3,  // 11: com.daml.ledger.api.v2.interactive.transaction.v1.Node.rollback:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.Rollback
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() {
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_init()
}
func file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_init() {
	if File_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes[4].OneofWrappers = []any{
		(*Node_Create)(nil),
		(*Node_Fetch)(nil),
		(*Node_Exercise)(nil),
		(*Node_Rollback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDesc), len(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto = out.File
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_goTypes = nil
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_proto_depIdxs = nil
}
