name: Test Crosschain
on:
  push:
    branches:
      - "**"

env:
  NOTHANKS: 1

jobs:
  test:
    name: "Test crosschain"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: make lint test

  ci:
    strategy:
      matrix:
        chain:
          - chain: SOL
            image: us-docker.pkg.dev/cordialsys/crosschain/solana:latest
          - chain: SOL
            image: us-docker.pkg.dev/cordialsys/crosschain/solana:latest
            contract: "So11111111111111111111111111111111111111112"
            decimals: 9
          - chain: SOL
            image: us-docker.pkg.dev/cordialsys/crosschain/solana:latest
            contract: "So11111111111111111111111111111111111111112"
            decimals: 9
            fee-payer: true
          - chain: ETH
            image: us-docker.pkg.dev/cordialsys/crosschain/evm:latest
          - chain: ETH
            image: us-docker.pkg.dev/cordialsys/crosschain/evm:latest
            contract: "0xe1D98dC57ea81d94Bb15b9a8ca5c0075C3d7a0C1"
            decimals: 6
          - chain: ETH
            image: us-docker.pkg.dev/cordialsys/crosschain/evm:latest
            contract: "0xe1D98dC57ea81d94Bb15b9a8ca5c0075C3d7a0C1"
            decimals: 6
            fee-payer: true
          - chain: XPLA
            image: us-docker.pkg.dev/cordialsys/crosschain/cosmos:latest
          - chain: XPLA
            image: us-docker.pkg.dev/cordialsys/crosschain/cosmos:latest
            fee-payer: true
          - chain: BTC
            image: us-docker.pkg.dev/cordialsys/crosschain/bitcoin:latest
            network: regtest
          - chain: BTC
            algorithm: schnorr
            image: us-docker.pkg.dev/cordialsys/crosschain/bitcoin:latest
            network: regtest
          - chain: BTC
            image: us-docker.pkg.dev/cordialsys/crosschain/bitcoin:latest
            network: regtest
            tests: ["TestMultiTransfer"]
          - chain: TAO
            image: us-docker.pkg.dev/cordialsys/crosschain/bittensor:latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dagger
        run: curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.14.0 BIN_DIR=/usr/bin sudo -E sh
      - name: test-param
        run: echo "tests; ${{join(matrix.chain.tests, ',')}}"
      - name: chain
        run: >
          dagger --progress plain -v call test-chain
          --chain ${{matrix.chain.chain}}
          --image ${{matrix.chain.image}}
          --network "${{matrix.chain.network}}"
          --source .
          --algorithm "${{matrix.chain.algorithm}}"
          --contract "${{matrix.chain.contract}}"
          --decimals "${{matrix.chain.decimals}}"
          --fee-payer "${{matrix.chain.fee-payer}}"
          --tests "${{join(matrix.chain.tests, ',')}}"
